openstax/os-webview

src/app/components/shell/header/header.js
src/app/helpers/backbone/view.js
src/app/pages/home/home.js

This PR fixes a few issues related to Babel transpilation, which breaks Firefox.
Firefox also correctly throws an error when `Reflect.apply()` is not passed an argument list as the third parameter (Chrome and Safari were not throwing an error).

Fix Transpilation and Reflect errors

---

src/app/components/shell/footer/footer.js
src/app/components/shell/header/header.js
src/app/components/shell/shell.js
src/app/main.js
src/app/pages/home/home.js
src/app/router.js

Because the header view was being loaded asynchronously, it was creating a race condition where it was sometimes not loaded prior to a page attempting to access its methods.

Resolve header race condition

---

gulp/.scss-lint.yml

This disables SCSS Lint's default settings that enforce [sorting properties in alphabetical order](https://github.com/brigade/scss-lint/blob/master/lib/scss_lint/linter/README.md#propertysortorder).
Rule is being disabled per request.

Disable SCSS Lint's Default PropertySortOrder

---

src/app/pages/accessibility-statement/accessibility-statement.hbs
src/app/pages/accessibility-statement/accessibility-statement.scss
src/app/pages/license/license.hbs
src/app/pages/license/license.scss
src/app/pages/tos/tos.hbs
src/app/pages/tos/tos.scss
src/styles/main.scss

Add global styles to boxed view pages.

---

src/app/pages/subjects/subjects.js
src/app/router.js

Router only loads Subjects page if it is not the currently-loaded page.
Subjects page listens to the router and updates selected filter
accordingly.

Make Subject selection work with router

---

src/app/components/get-this-title/get-this-title.hbs
src/app/pages/adoption-confirmation/adoption-confirmation.js
src/app/pages/interest-confirmation/interest-confirmation.hbs
src/app/pages/interest-confirmation/interest-confirmation.js
src/app/pages/interest/interest.hbs
src/app/router.js

After handling interest form, Salesforce should redirect to
interest-confirmation.
No asterisk on View on Web menu item (download menu)
Hide unavailable download options (get print copy, daisy/BRF)

Create interest confirmation page, fix download menu issues

---

src/app/models/salesforce-model.js

Salesforce’s redirect after form submission is a new page load, so our
models don’t persist. Saved attributes to cookies so they do persist.
Didn’t really need a model, so converted salesforceModel implementation
to just a structure.

Persist salesforce model in cookies

---

src/app/components/get-this-title/get-this-title.scss

Correct padding so concept coach link text wraps correctly on get this title menu of subjects and details page.

Fix text wrapping on concept coach link

---

src/app/pages/details/details.js
src/app/pages/details/details.scss

When scrolling down fast, the get-this-title menu on the details page would fall below the footer. Fixed issue by making menu move up slightly faster when above the footer.

Fix get title menu scrolling

---

src/app/components/shell/header/header.js
src/app/components/shell/header/header.scss
src/app/pages/home/home.scss
src/styles/main.scss

Body would scroll when mobile menu was open without position: fixed on body. However, using fixed positioning caused regressions with click events. Instead, I use a `touchmove` eventlistener on page-header to prevent scrolling.

Add touchmove eventlistener to prevent body scrolling

---

src/app/models/pagemodel.js
src/app/models/usermodel.js
src/app/pages/allies/allies.js
src/app/pages/details/ally/ally.js
src/app/pages/details/details.js

Previously the API gave a link to a data block that contains the logo
URL. Now the logo URL is included in the data instead.

Use logo URLs directly

---

src/app/components/shell/footer/footer.hbs

Adds a link to the OpenStax source code in the footer.
@openstax/ux: thoughts on placement/phrasing? I just put it somewhere but it could also be a circle, like the linkedin link but with a black-and-white :octocat:

add link to source code

---

src/app/components/shell/header/header.scss

Font color of the flyout menu had changed after the svg arrow updates. Corrected the color back to neutral-medium variable.

fix mobile flyout menu font color

---

src/app/pages/details/details.scss

When authors section is last section on the details page
it was missing padding. The fix adds padding only when
author section is the last section on the page.

fix authors section padding

---

src/app/pages/about-us/bios.js
src/app/pages/subjects/subjects.js

Putting `<sup>reg;</sup>` in the tag made it stop matching the path
element. Edited canonicalizer to strip that out.

Fix AP filter button

---

src/app/components/filter-button/filter-button.js
src/app/components/product-box/product-box.hbs
src/app/components/product-box/product-box.js
src/app/components/products-boxes/products-boxes.hbs
src/app/components/products-boxes/products-boxes.js
src/app/components/products-boxes/products-boxes.scss
src/app/pages/allies/allies.js
src/app/pages/higher-ed/higher-ed.js
src/app/pages/k-12/k-12.js
src/app/pages/subjects/subjects.js
src/app/router.js

Allies page now takes filter path like Subjects page
ProductBox is now a separate component
ProductsBoxes is called a little differently; Higher Ed and K-12
updated accordingly

Componentize product boxes, update pages to use them

---

src/app/components/quotes/quotes.scss
src/app/pages/allies/allies.scss
src/app/pages/higher-ed/higher-ed.scss
src/app/pages/k-12/banner/banner.scss
src/index.html
src/styles/main.scss

Added shim for classList (using rawgit CDN)
Added margin for banner overlays
Set z-index of #main to keep elements from passing in front of menu

Fix IE styling for quotes, buckets, banner overlays

---

src/app/components/shell/shell.js

This allows cross-page #links to work.
Because of dynamic loading, the location of a #link will likely change
from where it is when the page initially loads. To compensate, I’ve put
an interval that will re-adjust the scroll position a few times. A
fully correct solution would require each page to signal when it was
stable, which would require significant work on each page.

Make page loader recognize URL with #

---

src/app/helpers/backbone/loading-view.js
src/app/pages/about-us/about-us.hbs
src/app/pages/about-us/about-us.js
src/app/pages/about-us/about-us.scss
src/app/pages/details/details.hbs
src/app/pages/details/details.js
src/styles/main.scss

Updated loader to hide/show header and footer, take up entire screen.
Applied loader to About Us and Details pages.

Apply loader to About Us and Details

---

src/app/components/shell/footer/footer.hbs
src/app/components/shell/footer/footer.scss
src/app/components/shell/header/header.hbs
src/app/components/shell/header/header.scss
src/app/components/shell/shell.js
src/app/pages/adopters/adopter-column.hbs
src/app/pages/adopters/adopters.js
src/app/pages/adopters/adopters.scss
src/app/pages/details/details.hbs
src/app/pages/details/details.scss
src/app/pages/impact/impact.hbs
src/app/pages/impact/impact.scss
src/styles/main.scss

Created no-bullets class for ULs that should have no bullets
Tidied footer, centered social icon group
Fixed the menu chevron placement in IE without breaking it in Chrome
Put adopters in columns (displays faster and correctly in IE)

Clean up Adopters, footer, and ULs where IE leaves bullets

---

gulp/config.js
gulp/tasks/copy.js
gulp/tasks/html.js
gulp/tasks/images.js
gulp/tasks/scripts.js
gulp/tasks/service-worker.js
gulp/tasks/styles.js
gulp/tasks/systemjs-builder.js
gulp/tasks/templates.js

Drastically reduce gulp CPU usage, especially on OS X, and also ensure files are done writing before re-loading to prevent empty reloads.

Reduce gulp watch CPU usage

---

src/app/components/single-select/single-select.hbs
src/app/components/single-select/single-select.js
src/app/components/tag-multi-select/tag-multi-select.hbs
src/app/components/tag-multi-select/tag-multi-select.js
src/app/helpers/backbone/view.js
src/app/pages/details/details.hbs
src/styles/components/option-list.scss
src/styles/main.scss

Moved Mac scrollbar fix into main.css, attached to `mac-scroll` class
Applied to TOC on details page
Moved freeze-main-window-when-scrolling-popover functionality into
BaseView (requires call to `super.onRender()` in derived class to
activate)

Create mac-scroll class that fixes disappearing scrollbar problem

---

src/app/components/loading-section/loading-section.hbs

Firefox ignores @keyframes in scoped styles.

Remove scoped from stylesheet

---

src/app/components/remover/remover.js
src/app/components/shell/header/header.js
src/app/components/single-select/single-select.js
src/app/components/tag-multi-select/tag-multi-select.js
src/app/helpers/$.js
src/app/helpers/backbone/view.js
src/app/pages/details/details.hbs
src/app/pages/details/details.js
src/app/pages/subjects/category-section/category-section.js

Having `@on` events defined in the BaseView broke `@on` events in the
derived views. Created `$.applyScrollFix()` instead.

Fix scrolling issues

---

src/app/pages/allies/allies.js
src/app/pages/details/details.js
src/app/pages/subjects/subjects.js

On Allies, Subjects, and Details pages, if an invalid subdirectory is given, route to 404

Route bogus subjects to 404

---

gulp/config.js
package.json

The latest Gulp 4 commit using the glob-watcher wrapper
around chokidar appears to have broken reloading.
This commit pins to an older version of Gulp 4 until that
bug can be addressed in Gulp or on our end.

Use previous Gulp 4 commit

---

src/app/helpers/$.js
src/app/pages/details/details.hbs
src/app/pages/details/details.scss

Made License section display: block
Removed touch handlers and added max-height to scrolling TOC container,
so it would be a scrolling region

Fix license display and (again) TOC scrolling

---

src/styles/main.scss

Firefox by default does not render text in `<strong>` tags as bold.

Ensure strong tag is rendered as bold

---

gulp/config.js
gulp/tasks/copy.js
gulp/tasks/env.js
gulp/tasks/flags.js
gulp/tasks/html.js
gulp/tasks/images.js
gulp/tasks/scripts.js
gulp/tasks/service-worker.js
gulp/tasks/styles.js
gulp/tasks/systemjs-builder.js
gulp/tasks/templates.js
gulpfile.js
package.json

- Only minify images with flag `--images=min`
- MUCH faster dist builds
- Fix how tasks are watched with gulp 4
- Support `--production` and `--development` flags
- Stream CSS changes rather than reloading browser (depends on #309)

Improve build process

---

src/index.html

Fixes a warning about improper CSS in Safari and iOS due to IE8 hacks in Font Awesome.

Upgrade to Font Awesome 4.6.1

---

src/app/pages/foundation/foundation.scss
src/app/pages/higher-ed/higher-ed.hbs
src/app/pages/higher-ed/higher-ed.scss
src/app/pages/impact/impact.hbs
src/app/pages/impact/impact.scss
src/app/pages/k-12/hero/hero.scss
src/styles/components/hero.scss

Fix bugs on Impact, K-12, Foundation & Higher-Ed

---

src/app/pages/details/details.js
src/app/pages/finish-profile/finish-profile.scss

Float it instead of having a full-width div
Also: modify details title to accept HTML so `<sup>` can be used with
AP books

Fix finish-profile submit button overlap problem

---

src/styles/fonts.css

change fonts.com import link from `//` to `https://`

force fonts to use secure connection

---

src/app/components/shell/header/header.hbs
src/app/components/shell/header/header.js

This allows some unnecessary event handlers to be removed, cleans up the template code, and fixes clicking the login/logout links in Edge.

Set login/logout links in template

---

src/app/pages/details/details.js
src/app/pages/home/banners/us-history/us-history.hbs
src/app/pages/subjects/category-section/book/book.hbs
src/app/router.js

Was accepting details/subject or details?subject
This made email links they want to use not workable

Stop using query string on details page

---

src/app/pages/about-us/about-us.scss
src/app/pages/about-us/headshot/headshot.js
src/app/pages/subjects/subjects.hbs
src/app/pages/subjects/subjects.scss

Make Book covers on Subjects page and color blocks on About Us resize
to keep limited between-block margins, and span the width of the screen
(up to 1200)

Improve resizing of blocks

---

src/app/components/shell/shell.js
src/app/helpers/$.js
src/app/helpers/backbone/loading-view.js
src/app/pages/details/details.js
src/app/pages/higher-ed/higher-ed.js
src/app/pages/home/home.js
src/app/pages/impact/impact.js
src/app/pages/k-12/k-12.js
src/app/pages/partners/icon/icon.js
src/app/pages/partners/partners.js
src/app/pages/subjects/subjects.js
src/styles/main.scss

On Details page only, clicking down-page link modifies history (and location) with hash
Also fixed scroll-to-hash for newly loaded pages

Include hashclicks in history

---

src/app/helpers/backbone/view.js

Events were not being detached ever because they were being saved on `listener` but passing the value from `handler` to remove them.

Detach events properly

---

src/app/pages/faculty-verification/faculty-verification.hbs

Last form field was added to the right column, I moved it to the left column to match the alignment of the fields on the rest of the website.

fix form field alignment on faculty-verification page

---

src/app/components/bucket/bucket.hbs
src/app/components/buckets/buckets.js
src/app/components/buckets/buckets.scss
src/app/components/quotes/quotes.scss
src/app/components/shell/header/header.hbs
src/app/pages/about-us/about-us.hbs
src/app/pages/details/author/author.hbs
src/app/pages/higher-ed/higher-ed.js
src/app/pages/higher-ed/higher-ed.scss
src/app/pages/home/home.js

On home page, continue to use default images/data
On Higher Ed, pass data from CMS to Buckets, and display it properly
Fixed bucket display issues on IE11

Fix quote boxes to pull from CMS

---

src/app/pages/article/article.js
src/app/pages/blog/pinned-article/pinned-article.hbs

If article data does not contain a subheading entry, remove the
corresponding DOM element.

Handle blog articles that have not subheading

---

src/app/pages/mass-renewal/mass-renewal.hbs

Require “How many students” to be >= 0
Mark optional fields as such

Fix mass renewal form validation

---

package.json
src/app/config.js

Relevant code: https://github.com/philschatz/recordo.js/commit/fcc77bb0a0d46e786f82ca57c20070516e197360
The website was always adding 3 buttons to the bottom of the page, even when debugging was not enabled. Now, debugging is only enabled when `?collect=true` is added to the URL.
- Does updating a package version _really_ require changing it in 3 places? /cc @dak

update recordo so it does not inject buttons all the time

---

src/styles/components/forms.scss

Allow word wrapping and scroll bar for texture
Also make it use our default font and not so bold in the fields.

Fix Contact Us Comments box

---

src/app/pages/impact/impact.hbs

Remove text inviting them to Institutional Partnership Program
Replace Get the application button with “Contact us to learn more”
button that takes them to /contact with “College/University
Partnerships” selected.

Remove partnership link from Impact page

---

src/app/pages/details/details.hbs
src/app/pages/details/details.js

Plug in text and url from CMS, if available. Otherwise, it’s labeled
UNAVAILABLE and links to /404

Implement Community Content Portal Link

---

src/app/pages/details/details.js

Because of the superscript, it’s HTML, not text.

Fix Community Resources for AP books (superscript)

---

src/app/helpers/book-titles.js
src/app/pages/interest/interest.hbs

Use new copy to remove deprecated `OpenStax College` branding, and add the book `Chemistry: Atoms First`.

Hotfix: Update Interest Form Copy and Book List

---

src/app/models/book-titles.js
src/app/pages/interest/interest.html

Use new copy to remove deprecated `OpenStax College` branding, and add the book `Chemistry: Atoms First`.

Update Interest Form Copy and Book List

---

gulp/tasks/scripts.js
package.json
src/app/components/quotes/quote/quote.html
src/app/controllers/cms.js

API was unable to be updated to include image urls for this release, so we've had to fallback to loading images with additional roundtrip requests.
CMSPageController will automatically traverse the JSON and find any `image` property with a number and create a separate call to fetch the image's url and insert it in place of the number.
`onDataLoaded` will not be called until all images have loaded, to avoid any potential issues that may exist with calling it multiple times.

Load images using old API

---

src/app/pages/about/about.js

Prevent seeing "unefined" when the page is loading.

Add default template values to about page

---

src/app/pages/foundation/foundation.html
src/app/pages/partners/partners.js

Use `allies` data that comes with pageData to populate `allPartners`
Fix in-page scrolling:
- account for header
- use animated scrolling
- replace state rather than accumulating history
Also: remove links to foundations from Foundation page

Remove extra fetch from Partners page

---

src/app/components/popup/popup.js

Hide popup instead of detaching. Clean-up code tries to detach it and
gets error.

Fix popup issue

---

src/app/pages/about/about.scss

Reduce maximum sizes
Position relative to bottom instead of top
Make hidden photos height 0 so there is not a big gap between photo
sections

Adjust advisor photo sizes

---

src/app/pages/faculty-verification/faculty-verification.html
src/app/pages/faculty-verification/faculty-verification.js

Make page wait for SalesForce data before displaying form
Do not display form if verification is pending or completed

Hotfix: Make Faculty Verification use Salesforce data correctly

---

src/app/pages/details/details-loaded.html
src/app/pages/details/details-loaded.js

Add `skip=“true”` to resources regions
Remove unused regions

Hotfix: Scroll to Student Resource

---

src/app/components/select/select.html
src/app/components/select/select.js
src/app/pages/adoption/adoption.html

Required multiselect prompt is now “Please select…”
if select has `data-require-none`, and a None item with value “”, the
None item clears other items, and other items clear None

Add optional special None behavior to multi-select

---

src/app/pages/details/details.scss

change flex-wrap from nowrap back to wrap to fix
instructor resources alignment on details page

fix instructor resources alignment

---

src/app/pages/details/details.scss

Book cover would shift position at certain screen widths. Remove
justify-content on desktop screen width to preserve book cover
placement.

fix book cover position on details page

---

src/app/helpers/link.js

Only accept /openstax.org as a local domain. Other domains are still external.

Fix login link

---

.codecov.yml
.travis.yml
gulp/tasks/jspm-builder.js
gulp/tasks/scripts.js
package.json
script/postprocess-coverage

As part of https://github.com/openstax/napkin-notes/issues/68 this adds code coverage reporting. See the napkin-note Issue for links to other repos being converted.
[Click here for example coverage report](https://codecov.io/gh/openstax/os-webview/src/d4b84d4cd0d122ce0f9383474f28f45ae88271a4/src/app/helpers/link.js)
You can find the coverage link near the "All checks have passed" below. It says "not affected" because there is no data about `/master` yet:
- Read more of [avajs/ava:./docs/recipes/code-coverage.md](https://github.com/avajs/ava/blob/master/docs/recipes/code-coverage.md)
- include sourcemaps so not just the test is covered
- maybe https://docs.travis-ci.com/user/gui-and-headless-browsers/ would be useful?
- maybe useful notes on JSPM and istanbuljs: …

adds code coverage reporting

---

src/app/helpers/analytics.js
src/app/models/usermodel.js

Make supermodel cache results for 15 seconds
In analytics, use the book fetch to add partner information to the
lookup tables, reducing a second fetch of book data

Improve errata form load time

---

src/app/components/shell/shell.js
src/app/main.js
src/index.html

Remove page-hiding css from index.html
Wait for #main to get content before attaching header and footer
Determine whether page-loader is being used; if not, add page-loaded
class to prevent its running later

Fix: pages that don't use the loader animation stay hidden

---

src/app/pages/bulk-order/bulk-order.js

Though the field showed quantity of 25 because its min was 25, the actual quantity value was zero, and zero-quantity entries aren't included. Set initial quantity to 25.

Bulk order: Set initial quantity to 25, since min is 25

---

src/app/router.js

Apparently when Firefox “blocks a pop-up” it does not return a null as
the window, which it does when window.open fails. Behavior is different
on dev than on local, so this is a testing PR.

Debugging: log message when opening new window

---

src/app/components/popup/popup.html
src/app/components/shell/header/upper-menu/upper-menu.html
src/app/pages/details/details.scss
src/app/pages/subjects/subjects.scss

Popup dismiss
Change “Support” menu to “Help”
Handle “Get this title” floating menu at the bottom of the page
Make “Get this title” hover menu wider so the button doesn’t hang off

Bug fixes for 10/9 release

---

.travis.yml

This should speed up tests because the packages should only need to be installed when package versions change (in `yarn.lock`)
See https://blog.travis-ci.com/2016-11-21-travis-ci-now-supports-yarn

cache node packages in travis

---

script/setup

This is because deployment servers did not have yarn installed globally.
You can test this by doing: 
```
brew uninstall yarn
npm uninstall -g yarn
./script/setup && ./script/test
```

always use yarn

---

script/bootstrap

If we are using rbenv, there is a possibility that `which bundle` might
return the global system `/usr/local/bin/bundle` or
`/var/lib/rundeck/.rbenv/shims/bundle` which does not ensure bundler is
actually installed for the ruby version we are using.
This is the error message we are seeing on bastion:
```
==> Installing gem dependencies…
rbenv: bundle: command not found
The `bundle' command exists in these Ruby versions:
2.4.2
```
So although `which bundle` works, it is not for the version of ruby we are
using.
The solution we came up with is to check by doing `gem list -i bundler` which
checks whether bundler is installed for the version of ruby we are using.  It
installs bundler if bundler is not installed.

Use "gem list -i bundler" in bootstrap to check if it is installed

---

Brewfile
script/bootstrap
script/setup

Refs https://github.com/openstax/napkin-notes/issues/83
If the person running `./script/setup` is a Mac, yarn is installed via Homebrew (no need for sudo).
If Debian, then they are prompted to install it (defaults to *no*).

fix how yarn is installed so it is more consistent

---

src/app/pages/give/give.js

Code was moved into a function, but the function wasn’t called.

Call sendToSalesforce after donation

---

script/bootstrap

Error message:
```
mktemp: too few X's in template 'stdout'
mktemp: too few X's in template 'stderr'
```

fix for ansible

---

gulp/tasks/scripts.js
gulp/tasks/styles.js
gulp/tasks/templates.js
gulp/tasks/webpack.js
gulpfile.js
package.json
yarn.lock

Changes were reviewed and approved by Phil, but merged into a different branch; it needs to be merged to master now.
Drop sourcemaps, as they do not seem to be used
Remove redundant webpack step and config
Copy settings-example.js for dev
* Stop webpack warnings
* Separate webpack task so both scripts and templates can use it
Reload browser works for html updates as well as script updates
* Use webpack to minify code
Drop sourcemaps, as they do not seem to be used
Remove redundant webpack step and config
Copy settings-example.js for dev
Use global SETTINGS variable
Remove dead build scripts, keep fiddling with settings
* Add source map calls back in

Merge 1002 to master

---

src/app/pages/openstax-tutor/openstax-tutor.html
src/app/pages/openstax-tutor/openstax-tutor.js
src/app/pages/openstax-tutor/openstax-tutor.scss

Make sky solid
Display video titles
Display features with alternate_text as available, and show the text
Arrange banner images so text tends to be in the sky on all screen
configurations

More marketing page fixes

---

src/app/pages/home/home.scss

The generic css for the banners sets background image for .book and
.second-book to be ${subject}.svg. There is no math.svg. Although the
css overrides that generic css, we are still getting requests. I have
put in an if-directive to prevent the setting of the background image
in the generic css when subject is math.

Fix request for nonexistent math.svg

---

src/app/pages/details/let-us-know/let-us-know.html

In “Let Us Know”, they were set to interest instead of adoption.

Fix adoption links

---

src/app/helpers/analytics.js
src/settings-example.js

Devops will need to update `settings.js` on dev and qa to use the new analyticsID values from the Trello cards and remove analyticsID2.

Enable Google Analytics for non-production

---

src/app/pages/errata/form/form.js
src/app/pages/faq/faq.html

I cannot test locally in Edge. The problem was that I was using an unsupported feature to clean up the form data for Safari. I used a different approach and tested that Safari still works. Will have to verify that it works in Edge on Dev.

Fix errata submission for Edge

---

src/app/controllers/salesforce-form.js

Adoption and interest form show covers for old books because the Salesforce book list does not distinguish between editions and uses the data from the first entry for (say) Biology that comes from the CMS. Filter out entries whose `book_state` is not "live" to avoid using obsolete information.

Only include "live" books in Salesforce book list

---

src/app/components/shell/header/main-menu/main-menu.js

Log out should be two words.  Accounts and Tutor have "Log out", too.

Log out should be two words

---

src/app/pages/rover-by-openstax/rover-by-openstax.html
src/app/pages/rover-by-openstax/rover-by-openstax.js
src/app/pages/rover-by-openstax/signup-form/signup-form.js

It is possible to submit the Rover form without selecting a Role (or doing anything else). Hiding the Submit button until a Role is selected ensures that the form is displayed and required fields must be entered.

Hide Submit until Role is selected

---

src/app/pages/footer-page/footer-page.js

The footer page slug was being set once for the session rather than once per page creation.

Fix footer page not changing

---

src/app/components/form-header/form-header.js

Adoption and Interest forms were not working because I hadn't changed CMSPageContoller to componentType() call.

Fix: Form Header

---

src/app/pages/rover-by-openstax/sections/getting-started.scss

Leave more space for Rover logo so it doesn't overlay text

Fix Rover logo placement for mobile, Getting Started section

---

src/app/helpers/analytics.js
src/app/pages/hero-journey/hero-journey.js

Checks for 5 seconds at half-second intervals for Google Analytics to be available. If at the end of that time it is not available, issues a warning in the console.

Wait for Analytics to load before sending

---

src/app/pages/subjects/book-viewer/book-viewer.js

Use `subjects` field to categorize books (also still uses special AP flag).
No longer uses `subject` field from CMS at all. Will require that books be categorized using the `subjects` field to show up on the Subjects page.

Allow books to be in multiple subject categories

---

src/app/pages/rover-by-openstax/sections/meet-rover.scss

Avoid too many cards per row on narrow screens

Fix Rover card layout for mobile

---

.editorconfig
gulp/config.js
gulp/tasks/html.js
gulp/tasks/humans.js
gulpfile.js
package.json
src/index.html
yarn.lock

Adds a content segment to the script and style files and references them by their name.
I **think** this also fixes a few bugs:
* The `src/index.html` file had hard-coded versions used as the query parameter, so the original regex in html.js would never match since the placeholders were not present
* The 'humans.js` grunt task would overwrite `dist/index.html` with `src/index.html`.  So even if the `html.js`  substation had worked, it would have been overwritten.
Also while I'm personally a big fan of 4 space indent, my editor was setup to use 2 space for all OX projects.  I added an `.editorconfig` file so that it'd behave.

Hash generated script and style files

---

src/app/helpers/controller/salesforce-form-mixin.js
src/app/pages/contact/contact.js

It was loading the Subjects page data as well as the Contact page data because the SalesforceFormMixin did that. I separated out the subject-loading functionality from the form functionality so the Contact page could use just the latter.

Fix Contact page header

---

gulp/config.js
gulp/tasks/html.js
gulp/tasks/webpack.js
gulpfile.js

and also call the distHTML grunt task as part of the default task
Otherwise the substations don't happen and the build is broken utterly
I'm unsure of the `/cms/assets` prefix.  Maybe that should be set somewhere else since I don't think cloud front is active yet

remove hashing from secrets.js, scripts in subdirectory

---

gulp/tasks/html.js
gulp/tasks/styles.js

This way unified can read the manifest.json and re-load the fonts if needed

add fonts.css to hashed styles

---

gulp/tasks/copy.js
src/app/pages/details/details-tab/details-tab.js
src/app/pages/details/phone-view/phone-view.js

If salesforce abbreviation for a book is unset, the Let Us Know component blows up.

Do not insert Let Us Know if salesforce abbreviation is unset

---

src/app/pages/rover-by-openstax/rover-by-openstax.js

I had converted names to camelCase, but was using underscore_separators

Fix data item spellings on Rover page

---

src/app/pages/partners/partners.scss

Height was set to 100% for some reason.

Fix stretched ally logo on Partners page

---

src/app/components/shell/header/main-menu/dropdown/dropdown.scss

The login menu used to be aligned with the left edge of the name; with short names that didn't give enough room onscreen for the menu itself. I initially overcorrected, but now have lined the login menu up with the right edge of the name.

Align rightmost menu dropdown with right edge

---

src/app/components/shell/header/header.js

settings.apiOrigin is now an empty string, so we don't get the expected fully qualified path

Use location.origin for path

---

src/app/pages/rover-by-openstax/sections/getting-started.scss
src/app/pages/rover-by-openstax/sections/meet-rover.scss
src/app/pages/rover-by-openstax/sections/navigator/navigator.html
src/app/pages/rover-by-openstax/sections/navigator/navigator.js
src/app/pages/rover-by-openstax/sections/navigator/navigator.scss

Tweak Rover image placement so that it does not overlay the text on any size screen. (Except 601 pixels, which is a pattern library issue for which a fix PR is up.)

Get Rover image out of the way of text

---

package.json
src/app/pages/errata-summary/errata-summary.scss

In breaking out the three errata page types, some CSS was lost (and some that didn't apply was retained).

Fix errata summary layout

---

package.json
src/app/pages/openstax-tutor/openstax-tutor.js

Fixes the issue of no popup displaying when you hover on the !-dot. Pulsing and stopping pulsing when clicked was not broken.

Pass pop up text to pulsing dot widget

---

src/app/components/shell/header/main-menu/main-menu.html

Remove `nav-menu-item` class from the `Hi, <name>` menu, because it has extra margin.

Fix nav items position on login

---

src/app/router.js

This was in the last release but somehow didn't get committed to master.

Test fully-qualified url when checking for external links

---

package.json
src/app/components/body-units/aligned-image.html
src/app/components/body-units/body-units.js
src/app/pages/blog/article/article.scss
src/app/pages/blog/blog.scss

If the alignment is "left" and not on phone, the image will be 50% of the text width and floated left. Similarly, "right" will float right.
Otherwise, the image will be up to the full width of the text.

Handle different-sizes of blog article images

---

src/app/pages/general/general.js

`slug` key in spec was indicating it should do standard CMS data fetch. It should not.

Fix general pages

---

src/app/components/dialog/dialog.js
src/app/pages/errata-form/banned-notice/banned-notice.html
src/app/pages/errata-form/banned-notice/banned-notice.js
src/app/pages/errata-form/banned-notice/banned-notice.scss
src/app/pages/errata-form/form/form.js

When the CMS rejects errata submission, display the returned message in a dialog.

Notify blocked users that they cannot submit errata

---

src/app/components/dialog/dialog.js
src/app/components/modal-content/modal-content.js
src/app/components/popup/popup.js
src/app/components/shell/shell.js
src/styles/main.scss
test/src/components/modal-content.test.js

Previously, menus were visible when a modal message was displayed. Now they are hidden behind the overlay. Page scrolling is also disabled when a modal is up.

Make dialog cover menus

---

src/app/components/dialog/dialog.scss
src/app/components/shell/cookie-notice/cookie-notice.js
src/app/components/shell/cookie-notice/cookie-notice.scss
src/app/helpers/analytics.js

I have set this up to look for JP's proposed `is_gdpr_location` and to not show the notice or set the tracking cookie unless that is explicitly false. That unblocks this and leaves the cookie/notice inactive until Accounts is serving that new flag.

Enable userid tracking for non-GDPR countries

---

package.json
src/index.html

We are now using our own Crazy Egg account instead of trial-piggybacking on our consultant's.

Update Crazy Egg, remove Optimizely

---

src/app/helpers/link.js

Test for external URL needed to exclude OpenStax addresses.
(Formerly OS domain was pre-stripped, but don't want to do that with the new umbrella domain.)

Fix local links opening in new tabs

---

src/app/pages/details/details.scss

It only gets set when it is open, and when it is closed, the text gets wrapped into something very tall.
Set height to zero when it is closed: solved.

Fix TOC drawer height when closed

---

src/app/pages/separatemap/separatemap.js

Was displaying a new form every time the window opened, but only removing the previous form on submit. So closing the window caused duplicate form.

Fix duplicate testimonial form on close and reopen

---

package.json
src/app/components/salesforce-form/salesforce-form.html
src/app/components/salesforce-form/salesforce-form.js
src/app/helpers/controller/bus-mixin.js
src/app/pages/adoption-confirmation/supplemental-form.html
src/app/pages/contact/contact-form/contact-form.html
src/app/pages/contact/contact-form/contact-form.js
src/app/pages/contact/contact.html
src/app/pages/contact/contact.js
src/app/pages/contact/contact.scss
src/app/pages/details/request-form/request-form.html
src/app/pages/give/give.html
src/app/pages/separatemap/separatemap.js

I recently discovered that there are two ways to insert a component. The "new" way doesn't create in intermediate container element, so I started using it. Due to a still-not-understood quirk in the framework, using that method caused form targeting to fail.
Investigating the problem gave me a chance to refactor the Contact form. The new components will be useful in refactoring adoption and interest forms, reducing redundant code.

Fix iframe as target of forms issue

---

src/app/components/shell/adoption-dialog/adoption-dialog.js
src/app/components/shell/header/main-menu/login-menu/login-menu.js
src/app/components/shell/header/main-menu/main-menu.js
src/app/models/usermodel.js
test/src/components/shell/header.test.js
test/src/components/shell/main-menu.test.js

Redid the user info cache (which was broken). Cache is invalidated by leaving the window (like by going to another tab), and data refreshes when tab is re-entered. This way you might login in another tab and when you come back, the Login menu updates.

Minimize use of /api/user

---

src/app/helpers/link.js
src/app/helpers/map-api.js
src/app/pages/separatemap/separatemap.js
src/app/pages/separatemap/separatemap.scss

They close if you click elsewhere on the map, but that may not be obvious.
I don't think this part of the code is testable.

Allow closing school info tooltips on map

---

src/app/components/shell/footer/footer.html
src/app/pages/interest/interest.js

Issue #700
Behavior consistent with an update overwriting inserted HTML. Noticed the element did not have `skip` which prevents such overwrites.

Fix missing footer-copyright

---

src/app/pages/details/details.js
src/app/pages/details/videos-tab/videos-tab.html
src/app/pages/details/videos-tab/videos-tab.js
src/app/pages/details/videos-tab/videos-tab.scss
test/src/data/details-biology-2e.js
test/src/data/details-polish.js
test/src/data/details.js

This is an experimental feature. If there are `videos` on the book details page, it will display a video tab. So don't do that in production.
Issue #727

Add videos tab to book details page

---

src/app/helpers/errata.js

Safari does not accept 'yyyy-mm-dd' as a Date initializer. Need to use slashes.
Issue #768

Fix date format

---

src/app/models/table-of-contents-html.js
src/index.html

Due to CORS issues, this cannot be tested on cms-dev. It will have to go to staging or something that has its REX origin the same as the osweb origin.

Use current rex version in toc links

---

src/app/pages/creator-fest/creator-fest.js

Build `url` from the slug rather than from the text label.

Handle changing section names on Creator Fest page

---

src/app/helpers/$.js
src/app/pages/details/instructor-resource-tab/instructor-resource-tab.html
src/app/pages/details/instructor-resource-tab/instructor-resource-tab.js
src/app/pages/details/instructor-resource-tab/instructor-resource-tab.scss

Issue #670
The feature was actually added in an earlier PR. This puts a flag on it so it won't go to Production (but can be tested in all non-production environments).

Put feature flag on partners list on instructor resources tab

---

src/app/helpers/analytics.js

(It was used for analytics, but the data is no longer attached to the book)

(Hotfix) Stop using allies list from book details

---

package.json
src/app/pages/partners/controls/controls.js

Was going to be a hotfix, but is just going into the next release.
Needs to be coordinated with a change in Salesforce.

Fix partner Type value list

---

src/app/pages/errata-detail/errata-detail.js

`reviewed_date` and `corrected_date` come in as date-only, which `new Date` interprets as being GMT. This adjusts by the timezone offset so that the local date matches the intended date.

Fix dates for Errata

---

src/app/controllers/jsx-wrapper.js
src/app/pages/a-page-template/a-page-template.js
src/app/pages/a-page-template/a-thing.jsx

I wrote a (trivial but real) React component. It gets added to `/a-page-template`, has its display value change, and then is removed. (Only available in testing environments.)

Write adapter for React components

---

src/app/pages/errata-form/form/ErrorLocationSelector/ErrorLocationSelector.scss

Issue #1013
There is no solution in browsers other than Chrome

Chrome only: wrap long titles in errata ToC

---

src/app/components/shell/footer/footer.js
src/app/components/shell/sticky-note/sticky-note.js
src/app/helpers/controller/cms-mixin.js
src/app/pages/details/details.scss
src/index.html
test/helpers/fetch-mocker.js

We've done good work over time to eliminate 30x redirects for our content on osweb (the ones that are just redirecting to add a trailing slash), but there are still 18 of them remaining.  They slow our site down and cost us in terms of requests made through Cloudfront.  Would be great if we could eliminate the remaining ones.  
Here's a stab at a few of them.
* I don't know where to fix the one for https://openstax.org/apps/cms/api/sticky?format=json
* I also can't see where to fix the ones for the images e.g. https://openstax.org/apps/cms/api/images/921
Ideally, a load of the home page should show no openstax.org 30x's in the chrome inspector.

eliminate 30x redirects due to missing trailing slash

---

package.json
src/app/helpers/controller/cms-mixin.js
src/app/models/book-titles.js
src/app/models/cmsFetch.js
test/helpers/fetch-mocker.js

Attaching to #853, but this is really just a bug fix.
Book page errata messages can be updated in the CMS.

Fix v2 requests

---

src/app/models/usermodel.js

The only time when the "Request instructor access" link shouldn't show is when instructors' `faculty_status == pending_faculty` because that means that they have already applied. 
This PR makes it so by removing `'no_faculty_info'` from the array that we check in order to determine when an instructor is "pending" access because the result from this check is used in the [login-menu.js](https://github.com/openstax/os-webview/blob/68e25083f6fad94520e286d4bc823bf744d84359/src/app/components/shell/header/main-menu/login-menu/login-menu.js#L76-L82).

DO show "Request instructor access" link in Login Menu when no faculty info

---

src/app/components/book-checkbox/book-checkbox.scss
src/app/pages/details/phone-view/instructor-resources-pane/instructor-resources-pane.scss

This is a simple fix. It doesn't match the design, but it's better than before.

Handle long titles in Adoption/Interest forms

---

src/robots.txt

There is already a robots.txt in place in CloudFront, this file will block Google from indexing the cms-*.openstax.org URLs.

adding a robots.txt to cms-*.openstax.org

---

src/app/pages/blog/more-stories/more-stories.scss
src/styles/main.scss

Also hide the "more stories" section on blog posts, which take along time to lay out, and probably aren't what a person wants when printing an article.

Hide header and footer when printing

---

src/app/pages/separatemap/search-box/results.js

Ignore whether an institution type is selected; if the other inputs are clear, don't show the message.

Clear "too many matching results"

---

src/app/models/rex-release.js

archiveOverride currently includes `/apps/archive` even though i would prefer for it not to. the current logic had it putting that prefix in twice, this change makes it work, and will continue to work if i remove the prefix from the override.

fix archive override handling

---

src/app/components/shell/router.js

The trick is when a new page loads, not simply a pathname change.

Scroll to top when new page loads

---

src/index.html

Temporary solution that works for the home page only.
The url is also production-specific and the image is loaded from prod only.

Added meta tags to the home page

---

src/app/models/cmsFetch.js
src/app/pages/blog/blog.js
src/index.html
webpack.config.js

webview-settings seems to require crossorigin="anonymous"
fonts also require it but the CMS doesn't set a CORS header so instead of loading the fonts from the CMS and getting a CORS error we just proxy them using the webpack dev server
This seems to fix all console errors and warnings in dev.openstax.org
The dev server has some errors related to accounts (third party cookies) and google analytics.
Enabling third-party cookies for localhost allows you to login on local dev.

Fix CORS for webview-settings preloading and fonts

---

webpack.config.js

Should fix loading urls directly in the webpack dev server

Use historyApiFallback to serve the index instead of a rewrite

---

src/app/helpers/tag-manager.js
src/app/pages/subjects/old/book-viewer/book-viewer.js
src/app/pages/subjects/old/book-viewer/book.js

I'm working on adding shared analytics-events code via GTM and [this other helper](https://github.com/openstax/analytics-helpers). meaning all we have to do in osweb is add the metadata as data attributes.
there is a cms change (https://github.com/openstax/openstax-cms/pull/1446) to add the cnx_id to the default book data response, the analytics won't work until both changes are in place but nothing breaks without the supporting change.

Add some analytics metadata

---

src/app/helpers/tag-manager.js

OK so there are a few things going on here. one is that there was an existing default `Platform` dimension in GA that i didn't want to get confused with, so i renamed our platform thing to "app"
i was also [educated](https://stackoverflow.com/questions/76177242/can-ga4-custom-dimensions-be-updated-after-the-initial-config-call) on how to correctly use dataLayer directly.
finally i would much prefer to move the `app_loaded` call to after we've established the user state and can include a user role on the event, but theres something hinky going on with that code that i need to investigate or talk to roy about.

update gtag integration

---

src/app/components/shell/lower-sticky-note/lsn-content.js
src/app/components/shell/microsurvey-popup/sticky-content.js
src/app/helpers/tag-manager.js
src/app/helpers/use-document-head.js
src/app/pages/blog/article-summary/article-summary.js
src/app/pages/details/common/featured-resources/featured-resources.js
src/app/pages/details/common/resource-box/resource-boxes.js
src/app/pages/details/desktop-view/instructor-resource-tab/instructor-resource-tab.js
src/app/pages/details/desktop-view/instructor-resource-tab/partners/partners.js
src/app/pages/details/phone-view/instructor-resources-pane/instructor-resources-pane.js
src/app/pages/partners/partner-details/partner-details.js
src/app/pages/partners/partner-details/synopsis/synopsis.js
src/app/pages/partners/results/result-grid.js
src/app/pages/subjects/old/book-viewer/book.js

- aligned donation nudge name
- added logic that waits to configure GA tracker until content is loaded, and set user type tags on the config
- add logic that sets content tags when bookish pages are loaded (will be adding this to other page types like blog as well)
- remove `content-id` parameter from analytics, it turns out it was not really helpful and not worth the confusion of having it in there
- identify featured resources list as being instructor specific
- remove categories parameters from select-content events. the way they were being tracked was not really working, replaced with "tags" which are formatted in a way to make it easy to use a "contains" filter on them, but will not be able to be used as group_by in any meaningful way in GA, maybe another tool will be able to figure …

fix analytics events

---

src/app/helpers/use-document-head.js

i misinterpreted `setPageTitleAndDescriptionFromBookData` to mean that it was only used on book pages, this method is actually used for all specific page data, i modified to only set the book title on book pages, and added a different formatter for blog posts

update analytics page types

---

src/app/pages/blog/article-summary/article-summary.js
src/app/pages/details/common/resource-box/resource-boxes.js
src/app/pages/details/desktop-view/instructor-resource-tab/partners/partners.js
src/app/pages/partners/results/result-grid.js
src/app/pages/subjects/old/book-viewer/book.js

i realized that my changes to make the content reference metadata more taggy (mostly to support selecting books from the subjects lists) also made the book resources much less reportable, so i moved their one category into the type field, and made the type field generally more human readable since it'll be used as a default dimension.

update content reference categories

---

src/app/pages/blog/explore-page/explore-page.js
src/app/pages/blog/more-stories/more-stories.js
src/app/pages/blog/pinned-article/pinned-article.js
src/app/pages/details/common/featured-resources/featured-resources.js
src/app/pages/details/desktop-view/instructor-resource-tab/instructor-resource-tab.js
src/app/pages/details/desktop-view/instructor-resource-tab/partners/partners.js
src/app/pages/details/desktop-view/student-resource-tab/student-resource-tab.js
src/app/pages/details/phone-view/instructor-resources-pane/instructor-resources-pane.js
src/app/pages/partners/partners.js
src/app/pages/subjects/old/book-viewer/book-viewer.js

i thought it would be helpful to have a consistent id for lists in case the titles changed, but after getting into the reporting i'm seeing that its really not going to be used ever

remove separate content list id and name

---

src/app/components/accordion-group/accordion-group.js
src/app/components/shell/header/menus/main-menu/dropdown/dropdown.js
src/app/components/tab-group/tab-group.js
src/app/pages/details/common/get-this-title-files/options.js

i had put these in here to allow the analytics code to run before the handlers modified the page, but after changing the analytics code to use capture mode event handlers they're no longer necessary

revert timeouts, not necessary anymore

---

src/app/models/use-school-suggestion-list.js
src/app/pages/details/common/let-us-know/let-us-know.js

For: https://github.com/openstax/openstax.org/issues/2264
This PR just removes the links to the adoption and interest forms from the book details page if the book isn't in Salesforce. The forms will not list the book if it is not in Salesforce.
In general, Coming Soon books should not be in Salesforce, but there are edge cases (see Issue card discussion).

Hide adoption and interest links for non-Salesforce books

---

src/app/components/dialog/dialog.scss

I don't know if we had a way to test Osano outside of production?
There are two commits:
The first excludes Osano dialogs from default dialog styling. It keeps styling that was specific to osano-cm-dialog, but we can take that out, too, if needed.
The second drops all dialog styling outside of #app (which excludes all the osano-specific styling as well, so I deleted those styles).

Don't apply sitewide dialog styles to Osano dialogs

---

src/app/helpers/use-document-head.ts
src/app/pages/blog/blog.js
src/app/pages/subjects/new/specific/specific.tsx
src/app/pages/webinars/webinars.tsx
test/src/components/book-selector.test.js
test/src/pages/confirmation.test.js
test/src/pages/details/book-details-context.js
test/src/pages/details/let-us-know.test.js
test/src/pages/details/resource-boxes.test.js
test/src/pages/errata/errata-summary.test.js
test/src/pages/institutional-partnership/institutional-partnership.test.js
test/src/pages/team.test.js

[DISCO-139]
Consistently strip trailing slash from pathnames for canonical paths
Used `useLocation` rather than window.location, which made it necessary to add MemoryRouter to some tests.
[DISCO-139]: https://openstax.atlassian.net/browse/DISCO-139?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Consistent canonical urls

---

src/app/helpers/device.js

[DISCO-263]
I simplified the test for supported browsers, reducing the risk of erroneously popping up the warning that the site might not render properly, but increasing the risk that some obscure browser will render badly and there will be no warning.
I don't know of any other likely-helpful features to test for in this regard.
It looks like [eslint-plugin-compat](https://stackoverflow.com/a/54942229) can check for these issues, but it wants node v18.
[DISCO-263]: https://openstax.atlassian.net/browse/DISCO-263?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Support any browser that supports grid layout

---

src/app/pages/contact/form.js
src/app/pages/flex-page/blocks/HeroBlock.tsx
src/app/pages/flex-page/blocks/SectionBlock.tsx

[DISCO-318]
[DISCO-318]: https://openstax.atlassian.net/browse/DISCO-318?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Add user_id as a hidden field populated from search params

---

src/app/pages/flex-page/blocks/CTABlock.scss
src/app/pages/flex-page/blocks/DividerBlock.scss
src/app/pages/flex-page/blocks/HeroBlock.scss
src/app/pages/flex-page/blocks/HeroBlock.tsx
src/app/pages/flex-page/blocks/RichTextBlock.scss
src/app/pages/flex-page/blocks/SectionBlock.tsx
src/app/pages/flex-page/components/Link.tsx

https://openstax.atlassian.net/browse/DISCO-466
https://openstax.atlassian.net/browse/DISCO-446
https://openstax.atlassian.net/browse/DISCO-442
https://openstax.atlassian.net/browse/DISCO-440
https://openstax.atlassian.net/browse/DISCO-439
banging out a few of the minor enhancements to the flex page options

Flex enhancements 1

---

src/app/components/shell/shell.tsx
src/app/pages/contact/contact.scss
src/app/pages/contact/embedded.js
src/app/pages/contact/embedded.scss
src/app/pages/contact/form.js
src/app/pages/contact/form.scss
src/app/pages/errata-form/form/FileUploader.scss
src/app/pages/errata-form/form/form.scss

[CORE-532]
This makes the embedded Contact form (mostly) like the [designs](https://www.figma.com/design/9xbDQWGZuE4vdYb8kqsyvj/instructor-side?node-id=3890-4909&node-type=frame&t=FXsvX78xf0ULEwd7-0).
- Display just the form, not the header or mailing address sections
- After form submit, show a minimalist thank you page
- Dismissing the thank you sends a postmessage to the parent window
- Default question topic to OpenStax Assignable for the embedded form
[CORE-532]: https://openstax.atlassian.net/browse/CORE-532?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fix postMessage in embedded Contact form

---

src/app/components/tablist/tablist.scss
src/app/pages/k12/subject/resources.scss
src/app/pages/k12/subject/resources.tsx
src/app/pages/k12/subject/subject.js
test/src/pages/k12/resources.test.tsx

Fix width
Fix specifier so it displays as grid
For testing, Dev is pretty sparse, but Biology has some associated resources.

Fix k12 resources section

---

src/app/layouts/default/takeover-dialog/content-desktop.scss
src/app/layouts/default/takeover-dialog/content-mobile.scss

[CORE-632]
There is no longer a dialog element between the outer and inner layers
[CORE-632]: https://openstax.atlassian.net/browse/CORE-632?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fix CSS for takeover banner

---

src/app/layouts/default/header/menus/main-menu/main-menu.js
src/app/pages/partners/active-filters/active-filters.scss
src/app/pages/partners/results/results.scss
src/app/pages/partners/results/results.tsx
test/src/pages/partners/partners.test.tsx

[CORE-609]
I have added a phone-format layout. On screens larger than phones, it has the sidebar which has a contrasting heading and a single column of partners. On small screens, the Startups section becomes just another grid at the bottom of the page (phone screens generally hold 2 partner info cards on each row).
[CORE-609]: https://openstax.atlassian.net/browse/CORE-609?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Add startups sidebar to partners

---

src/app/pages/errata-form/form/form.scss

[CORE-726]
scrollbar when text overflows
Textarea is resizable for height, but restricted width.
[CORE-726]: https://openstax.atlassian.net/browse/CORE-726?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Style textarea

---

package.json
src/app/pages/details/common/get-this-title-files/give-before-pdf/thank-you-form.tsx
test/src/pages/details/get-this-title/give-before-pdf.test.tsx

This was the hotfix from Thu 6 Mar. The issue was using `id` and `title` instead of the `name` attribute to identify the target iframe. That change required an update to a test.

Use name field of target iframe

---

src/app/layouts/landing/header/header.scss
src/app/layouts/landing/header/header.tsx
src/app/layouts/landing/landing.tsx
test/src/layouts/layouts.test.tsx

[CORE-899]
First commit shows changes; second commit applied prettier.
[CORE-899]: https://openstax.atlassian.net/browse/CORE-899?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Core 899 add option to remove give button from landing page

---

src/app/components/shell/router-helpers/fallback-to.js
src/app/layouts/default/footer/cookie-yes-toggle.tsx
src/app/layouts/default/footer/copyright.tsx
src/app/layouts/default/footer/footer.js
src/app/layouts/default/footer/footer.scss
src/app/layouts/landing/footer/flex.scss
src/app/layouts/landing/footer/flex.tsx
src/app/layouts/landing/landing.tsx
test/src/layouts/landing/footer.test.tsx
test/src/layouts/layouts.test.tsx

https://openstax.atlassian.net/browse/CORE-898
Add a new footer for landing layout flex pages.
I am a bit new to this code, but it seemed like this combination of `import` and `JITLoad` was a common way to avoid importing styles/code that isn't actively used. I realize that the footer loader has its own loading placeholder which is then placed inside the `JITLoad` which also has a loading placeholder. Maybe there's a better way that I overlooked.
I am also wondering if (1) the condition for flex pages is correct and (2) if I should export a list of flex page types somewhere that can be used here and in `fallback-to` so that this condition is not duplicated.

Core 898 landing flex footer

---

src/index.html

[CORE-962]
[CORE-962]: https://openstax.atlassian.net/browse/CORE-962?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CORE-962: Change default OG image(s)

---

src/app/helpers/errata.ts
src/app/pages/errata-detail/detail/detail.tsx
src/app/pages/errata-detail/errata-detail.tsx
src/app/pages/errata-detail/progress-bar/progress-bar.tsx
test/src/pages/errata/errata-detail.test.tsx

[CORE-1204]
[CORE-1204]: https://openstax.atlassian.net/browse/CORE-1204?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Core 1204 port errata detail page to ts
