openstax/os-webview

src/app/pages/adoption-form/adoption-form.hbs
src/app/pages/home/home.js
src/app/pages/interest-form/interest-form.hbs
src/app/pages/interest-form/interest-form.js
src/app/router.js
src/styles/components/forms.scss
src/styles/main.scss

Moved form css into shared resource
Put hint text for fieldsets into legend

Create interest form

---

src/app/main.js

Prevent the page from incorrectly refreshing if the target is not an anchor tag (if, for example, an anchor tag is the parent of an img tag).  We now traverse up the DOM more intelligently to find any relevant anchor tags.

Improve routing click handler logic

---

src/app/pages/adoption/adoption.hbs
src/app/pages/comp-copy/comp-copy.hbs
src/app/pages/comp-copy/comp-copy.js
src/app/pages/comp-copy/comp-copy.scss
src/app/router.js
src/styles/components/forms.scss

Minimal layout and functionality for the form

Complimentary copy

---

src/app/pages/details/details.hbs
src/app/pages/details/details.js
src/app/pages/details/details.scss
src/app/pages/subjects/category-section/book/book.hbs
src/app/pages/subjects/subjects.hbs
src/app/pages/subjects/subjects.js
src/app/pages/subjects/subjects.scss
src/styles/components/buttons.scss
src/styles/variables/colors.scss

Updated subjects to fetch and display data from our server. CORS is an
issue (also, server may not have any data at a given time).
Plugged a little more dummy data into details page instead of flat HTML.
Also folded in fix-ups

Fetch data for Subjects page

---

src/app/models/pagecollection.js
src/app/pages/subjects/subjects.js

Move the model that fetches page information into a separate module.
Pages can be fetched as needed, referenced by `meta.type`.

Implement model for fetching page info

---

src/app/pages/adoption-confirmation/adoption-confirmation.hbs
src/app/pages/adoption-confirmation/adoption-confirmation.js
src/app/pages/adoption-confirmation/adoption-confirmation.scss
src/app/pages/details/details.hbs
src/app/router.js

Layout table of savings and donation slider
Add behavior and basic styling

Create adoption confirmation form

---

src/app/pages/adoption/adoption.hbs
src/app/pages/adoption/adoption.js
src/app/pages/adoption/book-info/book-info.hbs

add salesforce URL as form action
rename inputs
comment out inputs that salesforce does not handle

Make adoption form submittable

---

src/app/pages/interest/interest.hbs

Provided form action, hidden values, and proper input names

Make interest form submittable

---

src/app/pages/accessibility-statement/accessibility-statement.hbs
src/app/pages/accessibility-statement/accessibility-statement.js
src/app/pages/accessibility-statement/accessibility-statement.scss
src/app/router.js

@Fredasaurus and I will be trying few other colors for the `stripes` div. It might end up being used on pages that has content only i.e: Toc and License.

Add Accessibility page

---

src/app/pages/adoption-confirmation/adoption-confirmation.hbs
src/app/pages/adoption/adoption.hbs

Disable donate form for now
Remove unnecessary hidden field in adoption form

Disable donate form on adoption confirmation page

---

src/app/pages/accessibility-statement/accessibility-statement.scss
src/styles/main.scss

Styles need to be global as @Fredasaurus might use them for other pages. For now, I'm adding them to TOC and License page in the upcoming PRs.

Move strips styles to main.scss

---

src/app/pages/adoption/adoption.hbs
src/app/pages/adoption/book-info/book-info.hbs
src/app/pages/comp-copy/comp-copy.hbs
src/app/pages/details/details.hbs
src/app/pages/details/details.js

Replace occurrences of faculty with instructor(s)

---

src/app/pages/home/banners/chemistry/chemistry.hbs
src/app/pages/home/banners/us-history/us-history.scss
src/styles/variables/colors.scss

Fix Openstax colors

---

src/app/pages/adoption-confirmation/adoption-confirmation.hbs
src/app/pages/adoption/adoption.hbs
src/app/pages/interest/interest.js

Adoption and Interest forms had not-quite-complete solutions for
redirecting on success.

Fix salesforce redirect

---

src/app/pages/subjects/category-section/book/book.js

Click has to specify img target or the other click doesn’t work.

Unbreak details link

---

src/app/pages/adoption/adoption.js
src/app/pages/adoption/book-info/book-info.js
src/app/pages/details/details.js

Main issue was leftover code from an iframe that I took out.
Some weirdness with regions remains, but isn't raising errors now.

Fix Adoption form issue that is breaking navigation

---

src/app/pages/details/author/author.hbs
src/app/pages/details/author/author.js
src/app/pages/details/details.hbs
src/app/pages/details/details.js
src/app/pages/details/details.scss

Add endorsement quote and author lists to details page

---

src/app/components/shell/shell.js
src/app/pages/details/details.hbs

Trello card: https://trello.com/c/nXb6nMpr

Put pageName into header title, Restore Details down-page links

---

src/app/components/quotes/quotes.scss
src/app/components/shell/footer/footer.hbs

Also, somehow the quotes section was not centered. Fixed that too

Add social media links to footer

---

src/app/pages/comp-copy/comp-copy.hbs
src/app/pages/comp-copy/comp-copy.js
src/app/pages/faculty-verification/faculty-verification.hbs
src/app/pages/faculty-verification/faculty-verification.js
src/app/pages/faculty-verification/faculty-verification.scss
src/app/router.js

Complimentary Copy and Faculty Verification forms are laid out and
successfully submit to Salesforce. (A couple fields are not legitimate
Salesforce columns: department and has_adopted)

Create basic comp copy and faculty verification forms that submit

---

src/app/components/shell/header/header.hbs
src/app/components/shell/header/header.js
src/app/components/shell/header/header.scss
src/app/pages/home/banners/us-history/us-history.scss
src/app/pages/home/home.scss
src/index.html
src/styles/main.scss

Items left: (will complete in smaller PR)

fix mobile header css & js

---

src/app/pages/adoption/adoption.hbs
src/app/pages/adoption/adoption.js
src/app/pages/adoption/adoption.scss
src/app/pages/adoption/book-info/book-info.hbs
src/app/pages/comp-copy/comp-copy.hbs
src/app/pages/comp-copy/comp-copy.scss
src/styles/components/forms.scss

Styled the adoption form in particular, but mostly using the
forms.scss file so that the styling applied across all forms.
PRing so the changes stay a reasonable size.

Do basic styling on forms

---

src/app/models/salesforce-model.js
src/app/pages/adoption-confirmation/adoption-confirmation.hbs
src/app/pages/adoption/adoption.hbs
src/app/pages/adoption/adoption.js
src/app/pages/comp-copy/comp-copy.js
src/app/pages/interest/interest.js

Adoption, Interest, and Comp Copy forms now save the values of text
fields, and pre-fill them from the saved values on load.
Adoption confirmation includes link back to adoption so they can fill
it out for another book.

Keep a global model of Salesforce form data

---

src/app/components/shell/header/header.hbs
src/app/components/shell/header/header.js
src/app/components/shell/header/header.scss
src/index.html
src/styles/main.scss

Fix Navigation Mobile UI

---

src/app/components/select-option/select-option.js
src/app/components/single-select/single-select.js
src/app/components/tag-multi-select/tag-multi-select.js
src/app/pages/adoption/adoption.js
src/app/pages/adoption/adoption.scss
src/app/pages/interest/interest.hbs
src/app/pages/interest/interest.js
src/styles/components/forms.scss

Plus some cleanup of adoption form leftovers
Proxy-widgets get styled for invalid now

Replace checkbox/radiobutton groups on interest form

---

src/app/components/shell/header/header.scss
src/styles/main.scss

Fix Desktop Dropdown UI

---

src/app/components/get-this-title/get-this-title.hbs
src/app/components/get-this-title/get-this-title.js
src/app/components/get-this-title/get-this-title.scss
src/app/pages/details/details.hbs
src/app/pages/details/details.js
src/app/pages/details/resource/resource.hbs
src/app/pages/details/resource/resource.js
src/app/pages/subjects/category-section/book/book.hbs
src/app/pages/subjects/category-section/book/book.js
src/app/pages/subjects/subjects.js

Get This Title links: View online, PDF, iBook hooked up
Details page: Instructor and Student Resources
Details page URL uses 'slug' instead of id, for more clarity

Insert download links and resources

---

src/app/pages/faculty-verification/faculty-verification.hbs
src/app/pages/faculty-verification/faculty-verification.scss

Add copy, rearrange some fields, add instructional text.

Update faculty verification form

---

src/app/components/tag-multi-select/tag-multi-select.js
src/app/helpers/book-titles.js
src/app/models/usermodel.js
src/app/pages/finish-profile/faculty-section/faculty-section.hbs
src/app/pages/finish-profile/faculty-section/faculty-section.js
src/app/pages/finish-profile/finish-profile.hbs
src/app/pages/finish-profile/finish-profile.js
src/app/pages/finish-profile/finish-profile.scss
src/app/pages/finished-no-verify/finished-no-verify.hbs
src/app/pages/finished-no-verify/finished-no-verify.js
src/app/pages/finished-verify/finished-verify.hbs
src/app/pages/finished-verify/finished-verify.js
src/app/pages/interest/interest.js
src/app/router.js

Created form plus two thank you pages.

Implement additional account information form for new accounts

---

src/app/components/filter-button/filter-button.js
src/app/pages/subjects/subjects.js
src/styles/components/filter-buttons.scss

Moved filter-button's js from subjects.js to components/filter-button.js
so allies page can use the same JS. Also fixed filter-button safari bug where dropdown
height would cut off dropdown text.

Move filter-button js

---

src/app/components/single-select/single-select.hbs
src/app/components/tag-multi-select/tag-multi-select.hbs
src/app/pages/adoption/adoption.hbs
src/app/pages/adoption/adoption.scss
src/styles/components/forms.scss
src/styles/components/headers.scss
src/styles/components/option-list.scss
src/styles/components/single-select.scss
src/styles/components/tag-multi-select.scss
src/styles/main.scss

Remaining styles and functionality:

Form styles

---

src/app/components/buckets/buckets.js
src/app/components/buckets/buckets.scss
src/app/components/quotes/quotes.scss
src/app/pages/home/banners/us-history/us-history.hbs
src/app/pages/home/home.scss

Home page hackathon updates

---

src/app/components/shell/header/header.hbs
src/app/components/shell/header/header.js

Fix login redirect link

---

src/app/pages/adoption-confirmation/adoption-confirmation.hbs
src/app/pages/adoption/adoption.hbs
src/app/pages/comp-copy-confirmation/comp-copy-confirmation.hbs
src/app/pages/comp-copy-confirmation/comp-copy-confirmation.js
src/app/pages/comp-copy/comp-copy.hbs
src/app/pages/comp-copy/comp-copy.js
src/app/pages/details/details.scss
src/app/pages/faculty-confirmation/faculty-confirmation.hbs
src/app/pages/faculty-confirmation/faculty-confirmation.js
src/app/pages/faculty-verification/faculty-verification.hbs
src/app/pages/faculty-verification/faculty-verification.js
src/app/pages/interest-confirmation/interest-confirmation.hbs
src/app/router.js
src/styles/main.scss

Created pages for faculty and comp-copy confirmations
Adjusted faculty and comp-copy to redirect properly to those
confirmations
Added link to interest confirmation
Pulled .go-to style into main, so they all could use it

Complete confirmation pages

---

src/app/components/get-this-title/get-this-title.scss
src/app/pages/details/details.hbs
src/app/pages/details/details.js
src/app/pages/details/details.scss
src/app/pages/subjects/subjects.hbs
src/app/pages/subjects/subjects.scss
src/styles/mixins/responsive.scss

Details page CSS

---

src/app/pages/allies/allies.hbs
src/app/pages/allies/allies.js
src/app/pages/allies/ally/ally.hbs
src/app/pages/allies/ally/ally.js
src/styles/components/filter-buttons.scss

Links to the Allies' book pages are displayed and filtered according to the selected subject.

Show and filter book links on Allies page

---

src/app/components/single-select/single-select.js
src/app/components/tag-multi-select/tag-multi-select.js
src/app/pages/adoption/adoption.js
src/app/pages/faculty-verification/faculty-verification.hbs
src/app/pages/finish-profile/finish-profile.js
src/app/pages/interest/interest.js

For adoption form, interest form, and finish-profile form, postpone setting invalid class on proxy select widgets until form submit is attempted.

Delay invalid class on selects

---

src/app/components/get-this-title/get-this-title.hbs
src/app/components/get-this-title/get-this-title.js
src/app/components/get-this-title/get-this-title.scss
src/app/components/get-this-title/pdf-submenu/pdf-submenu.hbs
src/app/components/get-this-title/pdf-submenu/pdf-submenu.js
src/app/components/get-this-title/print-submenu/print-submenu.hbs
src/app/components/get-this-title/print-submenu/print-submenu.js
src/app/pages/subjects/subjects.js

Added Concept Coach link, submenus for print and PDF, and bookstore
link.

Implement remaining get-this-title options

---

src/app/pages/comp-copy/comp-copy.hbs
src/app/pages/comp-copy/comp-copy.js
src/app/pages/comp-copy/comp-copy.scss
src/styles/components/buttons.scss
src/styles/components/forms.scss

Add comp-copy page styles

---

src/app/components/get-this-title/get-this-title.scss
src/app/pages/details/details.hbs
src/app/pages/details/details.js
src/app/pages/details/details.scss
src/app/pages/details/resource/resource.hbs
src/app/pages/subjects/category-section/book/book.js
src/app/pages/subjects/subjects.scss

Finish details page CSS

---

src/app/pages/404/404.hbs
src/app/pages/404/404.js

Implement 404 page

---

src/app/pages/adoption/adoption.scss
src/app/pages/renewal/renewal.hbs
src/app/pages/renewal/renewal.js
src/app/router.js

Copied adoption form, changed text at top slightly, changed
`lead_source` hidden field value.

Create renewal form

---

src/app/pages/adoption-confirmation/adoption-confirmation.hbs
src/app/pages/adoption-confirmation/adoption-confirmation.js
src/app/pages/adoption-confirmation/adoption-confirmation.scss
src/styles/components/add-another.scss
src/styles/components/intro.scss
src/styles/main.scss

Add Adoption Confirmation styles

---

src/app/pages/allies/allies.hbs
src/app/pages/allies/allies.js
src/app/pages/allies/allies.scss
src/app/pages/allies/ally/ally.hbs
src/app/pages/subjects/subjects.hbs
src/app/pages/subjects/subjects.scss
src/styles/components/filter-buttons.scss
src/styles/components/strips.scss

Add responsive css for allies page

---

src/app/components/calculator/calculator.hbs
src/app/components/calculator/calculator.js
src/app/pages/adoption-confirmation/adoption-confirmation.hbs
src/app/pages/adoption-confirmation/adoption-confirmation.js

Extracted calculator from adoption confirmation page, created
component. Did some refactoring.

Make calculator into a component

---

src/app/components/quotes/quotes.hbs
src/app/components/shell/header/header.hbs
src/app/components/shell/header/header.js

Header dropdown & home page updates

---

src/app/components/get-this-title/get-this-title.js
src/app/components/get-this-title/get-this-title.scss
src/app/components/get-this-title/pdf-submenu/pdf-submenu.hbs
src/app/components/get-this-title/print-submenu/print-submenu.hbs
src/app/pages/details/details.hbs
src/app/pages/details/details.scss
src/app/pages/subjects/subjects.scss

add css & clean up UI for pdf/print options menu on subjects and details page

Get this title menu UI updates

---

src/app/components/calculator/calculator.scss
src/app/pages/adoption-confirmation/adoption-confirmation.hbs
src/app/pages/comp-copy-confirmation/comp-copy-confirmation.hbs
src/app/pages/comp-copy-confirmation/comp-copy-confirmation.js
src/app/pages/comp-copy-confirmation/comp-copy-confirmation.scss
src/app/pages/faculty-confirmation/faculty-confirmation.hbs
src/app/pages/interest-confirmation/interest-confirmation.hbs
src/app/pages/interest-confirmation/interest-confirmation.js
src/app/pages/interest-confirmation/interest-confirmation.scss
src/styles/components/add-another.scss
src/styles/components/headers.scss

Also, I did update some of the copy on Adoption Confirmation and Faculty Confirmation pages.

Add styles for both Comp Copy Confirmation and Interest Confirmation

---

src/app/components/shell/header/header.js

update listener to listen for clicks globally to close dropdown

Fix dropdown click function

---

src/app/pages/adoption-confirmation/adoption-confirmation.hbs
src/app/pages/adoption-confirmation/adoption-confirmation.js
src/app/pages/adoption-confirmation/adoption-confirmation.scss
src/app/pages/comp-copy-confirmation/comp-copy-confirmation.hbs
src/app/pages/comp-copy-confirmation/comp-copy-confirmation.js
src/app/pages/comp-copy-confirmation/comp-copy-confirmation.scss
src/app/pages/comp-copy/comp-copy.hbs
src/app/pages/faculty-confirmation/faculty-confirmation.hbs
src/app/pages/faculty-confirmation/faculty-confirmation.js
src/app/pages/faculty-confirmation/faculty-confirmation.scss
src/app/pages/interest-confirmation/interest-confirmation.hbs
src/app/pages/interest-confirmation/interest-confirmation.js
src/app/pages/interest-confirmation/interest-confirmation.scss
src/styles/main.scss

Will add this back in Phase 2.

Comment out Calculator

---

src/app/pages/details/contents/contents.hbs
src/app/pages/details/contents/contents.js
src/app/pages/details/details.hbs
src/app/pages/details/details.js
src/app/pages/details/details.scss

Created contents view
Populated from detail data table_of_contents.contents
Triggered by Table of Contents link

Display table of contents in pop-up on Details page

---

src/app/pages/finish-profile/finish-profile.hbs

Changed from Role_c to 00NU00000054MLz

Change name of select field

---

src/app/pages/contact/contact.hbs
src/app/pages/contact/contact.js
src/app/pages/contact/contact.scss
src/app/router.js

The form collects all the information it needs to send mail, but the
Amazon SES is not intended for browser use.

Create contact page

---

src/app/pages/accessibility-statement/accessibility-statement.hbs

Fixes https://trello.com/c/MvilQrzI

Removed colons from headings

---

src/app/pages/allies/ally/ally.hbs
src/app/pages/details/ally/ally.hbs
src/app/pages/details/ally/ally.js
src/app/pages/details/details.hbs
src/app/pages/details/details.js
src/app/pages/details/details.scss

Clean up ally resources CSS on details page

---

src/app/components/get-this-title/print-submenu/print-submenu.hbs
src/app/components/shell/header/header.js
src/app/components/shell/shell.js
src/app/models/pagemodel.js
src/app/models/usermodel.js
src/app/pages/about-us/about-us.scss
src/app/pages/accessibility-statement/accessibility-statement.hbs
src/app/pages/allies/allies.js
src/app/pages/details/details.js
src/app/pages/details/details.scss
src/app/pages/finish-profile/finish-profile.js
src/app/pages/subjects/subjects.js
src/settings.js

This fixes several minor issues and has code to replace the Login menu with "Hi username", if the user info fetching from the API works. There is more to work out surrounding user info, but I want to get the other fixes in.

Change login to username

---

src/app/components/shell/header/header.js
src/app/models/usermodel.js
src/app/pages/contact/contact.hbs
src/app/pages/contact/contact.js
src/app/pages/finish-profile/finish-profile.hbs
src/app/pages/finish-profile/finish-profile.js
src/app/pages/finish-profile/finish-profile.scss

Also improve handling when userInfo is not populated.

Make Contact-us form submit

---

src/app/pages/about-us/about-us.scss
src/app/pages/contact-thank-you/contact-thank-you.hbs
src/app/pages/contact-thank-you/contact-thank-you.js
src/app/pages/contact/contact.hbs
src/app/pages/contact/contact.js
src/app/router.js

A minimal page for Django to redirect to upon receiving contact form
submission.
Also adjust layout of about-us images

Add thank-you page for contact form

---

gulp/tasks/systemjs-builder.js
src/app/config.js
src/app/helpers/analytics.js
src/app/main.js
src/app/router.js
src/settings.js

Note: A 404 will currently be returned for http://www.googletagmanager.com/gtm.js?id=GTM-W6N7PB because the container has not yet been published.
See: https://support.google.com/tagmanager/answer/6107163?hl=en

Add Google Analytics and Google Tag Manager

---

src/app/pages/contact/contact.js

Allows Michael to send the email to his own address

Add (temporary) Testing option to contact us menu

---

src/app/components/shell/header/header.hbs
src/app/components/shell/header/header.js
src/app/components/single-select/single-select.js
src/app/pages/contact/contact.js
src/app/pages/higher-ed/higher-ed.hbs
src/app/pages/higher-ed/higher-ed.js
src/app/pages/higher-ed/higher-ed.scss

Adjusted single-select proxy to allow value-setting
Made contact-us page take an argument for the initial subject selection

Make links in the orange box on Higher Ed

---

src/app/components/shell/header/header.hbs
src/app/pages/about-us/about-us.scss
src/app/pages/adopters/adopters.hbs
src/app/pages/adopters/adopters.js
src/app/pages/adopters/adopters.scss
src/app/pages/allies/allies.js
src/app/pages/allies/allies.scss
src/app/pages/allies/ally/ally.js
src/app/pages/contact/contact.js
src/app/pages/details/details.hbs
src/app/pages/details/details.js
src/app/pages/details/details.scss
src/app/pages/finish-profile/finish-profile.scss
src/app/pages/foundation/foundation.scss
src/app/pages/subjects/subjects.scss
src/app/router.js
src/styles/components/forms.scss
src/styles/components/headers.scss
src/styles/components/intro.scss
src/styles/main.scss
src/styles/variables/colors.scss

Created page, added link to Our Impact menu
Removed Testing item from Contact form
Applied Fred’s web styles to main style sheets, removed redundant
styling

Create Adopters page

---

src/app/pages/about-us/bios.js

Roy also removed titles from under images.

Updated bios

---

src/app/components/shell/header/header.hbs
src/app/components/shell/header/header.js
src/app/components/shell/header/header.scss

Add logged in user dropdown to header

---

src/app/components/products-boxes/products-boxes.hbs
src/app/components/products-boxes/products-boxes.js
src/app/components/shell/header/header.hbs
src/app/pages/k-12/k-12.js

Adjusted product-boxes to accept templateHelpers, adjusted template to
conditionally append a particular subject to the book subjects link.

Make K12 page book link point at AP books

---

src/app/pages/details/details.scss
src/app/pages/higher-ed/higher-ed.hbs
src/app/pages/higher-ed/higher-ed.scss
src/app/pages/k-12/k-12.hbs
src/app/pages/k-12/tutor/tutor.hbs

Fixes for https://trello.com/c/WzSEJJFe
https://trello.com/c/A4VaSIS5 (maybe)
https://trello.com/c/Gw9Vmh6j

Fix higher ed and k 12 issues

---

src/app/components/shell/header/header.scss

css arrows were a little small, so I increased the height.

fix CSS arrow height

---

src/app/components/shell/header/header.hbs
src/app/components/shell/header/header.js
src/app/components/shell/header/header.scss

dropdown arrows werent displaying correctly across all browsers. Changed to use svg images

add svg dropdown arrows

---

src/app/pages/about-us/bios.js
src/app/pages/faculty-verification/faculty-verification.hbs

Also fixed error in about-us bios

Add select list for book to faculty verification form

---

src/app/components/tag-multi-select/tag-multi-select.js
src/app/pages/details/details.js
src/app/pages/details/resource/resource.hbs
src/app/pages/details/resource/resource.js

Also fix bug in new Other option on forms

Use new resource information for constructing resources on Details

---

src/app/components/quote/quote.hbs
src/app/components/quote/quote.js
src/app/components/quotes/quotes.hbs
src/app/components/quotes/quotes.js
src/app/pages/higher-ed/higher-ed.hbs
src/app/pages/higher-ed/higher-ed.js
src/app/pages/higher-ed/higher-ed.scss
src/app/pages/home/home.js
src/app/pages/k-12/k-12.js

Quotes component now takes an array of data to pass to the new Quote
component. Home, K-12, and Higher Ed each use somewhat different data.

Create quote component, refactor pages to use it

---

src/app/components/shell/header/header.hbs
src/app/components/shell/header/header.js
src/app/components/shell/header/header.scss

Also fix back arrow on mobile menu

add logout link to header

---

src/app/components/shell/shell.js
src/app/pages/about-us/about-us.scss
src/app/pages/about-us/headshot/headshot.js
src/app/pages/details/details.js
src/app/pages/details/details.scss
src/styles/components/headers.scss

Details: scrolling to Errata section, fix menu overlap
About Us: allow click on bio to dismiss it

Fixes for details and about us

---

src/app/components/shell/shell.js
src/app/components/shell/shell.scss
src/app/pages/adoption/adoption.hbs
src/app/pages/comp-copy/comp-copy.hbs
src/app/pages/details/details.js
src/app/pages/interest/interest.hbs
src/styles/main.scss

Also fix scroll top bug and a little code cleanup

Add min to numeric form fields

---

src/app/pages/details/details.scss

Allies page UX updates

---

src/app/pages/finish-profile/finish-profile.js

Because this can only be debugged on dev.

Echo caught error from finish-profile onto console

---

src/app/pages/contact/contact.hbs
src/app/pages/contact/contact.scss
src/app/pages/finish-profile/faculty-section/faculty-section.hbs
src/app/pages/finish-profile/finish-profile.hbs
src/app/pages/finish-profile/finish-profile.js
src/app/pages/finish-profile/finish-profile.scss

add form styles for finish profile & contact page

---

src/app/components/buckets/buckets.scss
src/app/pages/details/details.hbs
src/app/pages/home/banners/us-history/us-history.scss
src/app/pages/home/home.hbs
src/app/pages/home/home.js
src/app/pages/home/home.scss

Spacing and copy changes; scroll down chevron

Update Home page

---

src/app/helpers/book-titles.js
src/app/pages/adoption/adoption.hbs
src/app/pages/adoption/adoption.js
src/app/pages/finish-profile/finish-profile.hbs
src/app/pages/finish-profile/finish-profile.js
src/app/pages/interest/interest.hbs

Updated field names in finish-profile form to match faculty verification
Updated values of selected books

Fix field names and book values

---

src/app/components/get-this-title/get-this-title.hbs
src/app/pages/faculty-verification/faculty-verification.hbs
src/app/pages/faculty-verification/faculty-verification.js
src/app/pages/finish-profile/finish-profile.hbs
src/app/pages/higher-ed/higher-ed.hbs
src/app/pages/higher-ed/higher-ed.scss
src/app/pages/home/home.hbs
src/app/pages/home/home.scss
src/app/pages/impact/impact.hbs
src/app/pages/impact/impact.js
src/app/pages/impact/impact.scss
src/app/pages/k-12/banner/banner.hbs
src/app/pages/k-12/banner/banner.js
src/app/pages/k-12/k-12.hbs
src/app/pages/k-12/k-12.js
src/index.html
src/styles/main.scss

Corrected form field names on finish-profile
Added more user info fields to faculty-verification
Added scroll-down chevrons to banners on Higher Ed, K-12, and Impact
(replacing “learn more” and such)
Styled Impact page responsively
Linked Font Awesome CDN in index.html, so it works in Firefox

Scroll-down chevrons on banners, form fixes, Impact responsiveness

---

src/app/components/shell/header/header.hbs
src/app/components/shell/header/header.js
src/app/pages/about-us/about-us.hbs
src/app/pages/about-us/about-us.js
src/app/pages/about-us/about-us.scss
src/app/pages/about-us/bios.js
src/app/pages/about-us/headshot/headshot.hbs
src/app/pages/about-us/headshot/headshot.js
src/styles/main.scss

About Us UX updates

---

src/app/helpers/$.js
src/app/pages/allies/allies.hbs
src/app/pages/allies/allies.js
src/app/pages/allies/allies.scss
src/app/pages/allies/ally/ally.hbs
src/app/pages/allies/icon/icon.hbs
src/app/pages/allies/icon/icon.js
src/app/pages/details/details.hbs
src/app/pages/details/details.js
src/app/pages/details/details.scss
src/app/pages/k-12/banner/banner.hbs
src/app/pages/k-12/banner/banner.scss
src/styles/components/headers.scss

Top section is a group of icons that link to blurbs in the bottom section
Each blurb has a “back to top” link
Filtering applies to both icons and blurbs
Right now, only one icon is loaded, and it is color. Fallback is to render name as text in icon section. When b&w icons are loaded in the CMS, they should display.

Implement redesigned Allies page

---

src/app/pages/about-us/headshot/headshot.js
src/app/pages/details/details.js

On Details table of contents and About Us bios, drag to scroll on touch
device.
Tap to dismiss.

Add scrolling handler for touch events

---

src/app/pages/allies/allies.scss

More closely match the visual design doc

Adjust layout of Allies logos

---

src/app/pages/allies/allies.js
src/app/pages/allies/allies.scss
src/app/pages/allies/ally/ally.js
src/app/pages/allies/icon/icon.js
src/styles/main.scss

Fixed ally filtering by subject, which got broken at some point.
Refactored to reduce duplicated code.

Restore icon filtering

---

src/app/components/get-this-title/get-this-title.hbs
src/app/components/get-this-title/get-this-title.scss
src/app/components/quotes/quotes.scss
src/app/components/shell/header/header.hbs
src/app/components/shell/header/header.js
src/app/pages/about-us/about-us.scss
src/app/pages/details/details.hbs
src/app/pages/foundation/foundation.scss
src/app/pages/subjects/subjects.hbs
src/styles/mixins.scss
src/styles/mixins/halo.scss
src/styles/mixins/radial-gradient.scss

De-cram letter spacing of Funder names
Remove superfluous scrollbar on bios
Hide “Request Instructor Access” menu item when already confirmed
Recenter graphic in the Tutor quotes block
Changed how About Us headshot halos are done, so they work
cross-platform
Fixed Get This Title menu-flipping

Fix several minor bugs

---

src/app/helpers/$.js
src/app/pages/allies/allies.scss
src/app/pages/allies/icon/icon.js
src/app/pages/details/details.js
src/app/pages/higher-ed/higher-ed.js
src/app/pages/home/home.js
src/app/pages/impact/impact.js
src/app/pages/k-12/k-12.js
src/app/pages/subjects/subjects.scss

Reworked scroll-to-hash code
Changed flex to block where flex wasn’t needed
Added width: 100% to some items IE was messing up

Fix layout of Allies and Subjects pages

---

src/app/components/quotes/quotes.scss
src/app/pages/home/banners/us-history/us-history.scss
src/app/pages/home/education/education.hbs
src/app/pages/home/education/education.scss
src/app/pages/home/home.scss
src/app/pages/subjects/subjects.scss

Home page CSS updates

---

src/app/helpers/backbone/loading-view.js
src/app/pages/home/banners/us-history/us-history.hbs
src/app/pages/home/banners/us-history/us-history.js
src/app/pages/home/banners/us-history/us-history.scss
src/app/pages/home/home.hbs
src/app/pages/home/home.js
src/app/pages/home/home.scss

Wait until all video and image resources have finished loading before displaying the home banner, and add flyin animations to banner elements.

Dynamically load Home Banner

---

src/app/components/shell/shell.js
src/app/pages/accessibility-statement/accessibility-statement.scss
src/app/pages/foundation/foundation.scss
src/styles/main.scss

Also had a problem with page extending beyond screen due to width +
padding.

Fix IE rendering problems with nav menus and Foundation page

---

src/app/pages/home/banners/us-history/us-history.scss
src/app/pages/home/home.scss
src/styles/components/animations.scss
src/styles/main.scss

add css animations for us history banner on home page

---

src/app/pages/home/banners/us-history/us-history.scss
src/app/pages/home/home.scss

corrected the height of the home page banner on mobile and adjusted animation timing

fix banner height and animation timing on home page

---

src/app/components/single-select/single-select.js
src/app/components/tag-multi-select/tag-multi-select.js
src/app/helpers/backbone/proxy-widget-view.js
src/app/pages/finish-profile/finish-profile.js

Fixed IE bug in proxy widgets
Selecting Student unchecks faculty access checkbox, any other option
checks it

Control faculty checkbox from role selector on Finish Profile form

---

src/app/pages/details/contents/contents.hbs
src/app/pages/details/details.js
src/app/pages/details/details.scss

Replaced default numbering with OSC-style numbering

Number TOC chapters

---

src/app/components/tag-multi-select/tag-multi-select.js
src/app/helpers/backbone/proxy-widget-view.js
src/app/pages/home/home.js

Fixed bug in multi-select startup
Removed time delay for displaying home page

Close proxy selects on outside click

---

src/app/components/remover/remover.hbs
src/app/components/remover/remover.scss
src/app/pages/about-us/headshot/headshot.js
src/app/pages/home/banners/us-history/us-history.js
src/app/pages/home/banners/us-history/us-history.scss
src/app/pages/home/home.js
src/app/pages/home/home.scss

fix remover size and home page banner updates

---

src/app/components/shell/header/header.js
src/app/components/shell/shell.js
src/app/helpers/backbone/proxy-widget-view.js
src/app/pages/finish-profile/finish-profile.js
src/app/pages/subjects/subjects.scss

Fix login dropdown; fix faculty checkbox on finish-profile page

---

src/app/components/shell/shell.js
src/app/components/single-select/single-select.js
src/app/components/tag-multi-select/tag-multi-select.js
src/app/helpers/$.js
src/app/helpers/touch-scroller.js
src/app/pages/about-us/headshot/headshot.js

Created a touch-scroller object
Used it in bios and proxy select widgets
Created a browser test so redrawing can be done only on IE11 where it
is needed
Put in a noticeable delay.

Scroll form dropdowns

---

src/app/components/shell/footer/footer.scss
src/app/components/shell/header/header.scss
src/app/components/shell/shell.js
src/app/components/single-select/single-select.js
src/app/components/tag-multi-select/tag-multi-select.js
src/app/helpers/backbone/proxy-widget-view.js
src/app/pages/impact/impact.hbs
src/app/pages/impact/impact.scss

Constrain affiliates to 1200px width
Add margin space to affiliates at 1200px
Size icons to fit five across at 1200px
Limit banner height
Adjust overlay size and position at large screen sizes
Adjust padding in and around affiliates

Style impact page more like visual design

---

src/app/components/single-select/single-select.js
src/app/helpers/backbone/loading-view.js

Fix page load failure due to Symbol.iterator issue

---

src/app/components/filter-button/filter-button.js
src/app/components/loading-section/loading-section.scss
src/app/components/shell/header/header.js
src/app/components/shell/shell.js
src/app/components/tag-multi-select/tag-multi-select.js
src/app/helpers/backbone/proxy-widget-view.js
src/app/helpers/backbone/view.js
src/app/pages/adopters/adopters.scss
src/app/pages/details/details.js

Made click event reset window location so offsite link doesn’t open in
new tab.
Created attachListenerTo method for BaseView that handles
addEventListener and removeEventListener; replaced throughout code base.
Also: fixed bug in multi-select

Make login link open in same tab

---

src/app/components/single-select/single-select.js
src/app/components/tag-multi-select/tag-multi-select.js
src/styles/components/option-list.scss

Freeze window while scrolling select options
Show scrollbars when Mac has no mouse
Handle touchpad (wheel) scrolling when Mac won’t

Handle scrolling of dropdown-selects

---

src/app/pages/home/banners/banner-view.js
src/app/pages/home/home.js

Add parallax effect back to home page banners since videos were removed. Also added slight movement to book covers on scroll & increased length of time each banner is shown to 8 seconds

add parallax effect to all home page banners

---

src/app/components/shell/header/header.js
src/app/components/shell/header/header.scss

Switched dropdown to activating on hover instead of on click as per @Fredasaurus

add dropdown on hover instead of on click for desktop

---

src/app/components/products-boxes/products-boxes.js
src/app/components/quotes/quotes.scss
src/app/components/remover/remover.js
src/app/helpers/backbone/view.js
src/app/pages/details/details.js
src/app/pages/foundation/foundation.scss
src/app/pages/k-12/hero/hero.hbs
src/app/pages/k-12/tutor/tutor.hbs
src/styles/main.scss

Updated product boxes copy
Fixed bug in mac-scroll code
Made Details page handle missing data (particularly TOC)
Updated K-12 copy
Changed chevron styling
Fixed remover bug

Change chevron styling, change K-12 blurbs, fix scroll-wheel bug

---

src/app/pages/details/details.hbs
src/app/pages/details/details.js
src/app/pages/details/details.scss
src/styles/main.scss

TOC updates

---

src/app/components/products-boxes/products-boxes.js
src/app/pages/higher-ed/higher-ed.scss
src/index.html

They updated the shim. Now using older version, rather than latest.
Fixed Higher Ed banner issues

Fix IE problems created by classList shim

---

src/app/components/shell/header/header.js
src/app/helpers/$.js
src/app/pages/about-us/about-us.js
src/app/pages/about-us/about-us.scss
src/app/pages/about-us/bios.js
src/app/pages/about-us/headshot/headshot.js
src/app/pages/finish-profile/finish-profile.js

Fix about us & finish profile

---

src/app/pages/details/details.hbs
src/app/pages/details/details.js
src/app/pages/details/details.scss
src/app/pages/subjects/category-section/book/book.js

Apply "coming soon" styling to unpublished books

---

src/app/components/products-boxes/products-boxes.js
src/app/components/shell/shell.js

Also removed non-working fix for IE nav styling problem

Fix Tutor blurb title

---

src/app/helpers/$.js
src/styles/main.scss

I can only test on mobile devices when code is in dev, so this may turn
into a series of PRs.

Add touch-scroll handling to scroll fix

---

src/app/helpers/$.js
src/app/pages/details/details.hbs

Attach mac-scroll class to the scrolling element

---

src/app/pages/home/banners/banner-view.js
src/app/pages/home/banners/biology/biology.hbs
src/app/pages/home/banners/biology/biology.scss
src/app/pages/home/banners/us-history/us-history.hbs
src/app/pages/home/banners/us-history/us-history.scss

Flyin/flyout banner animations were never meant to be removed. Reverting changes back.

add home banner flyin/flyout animations back

---

src/app/pages/home/home.js
src/app/pages/home/home.scss

Add banner loads to otherPromises so loading-view waits for them

---

src/app/pages/details/details.scss

This is a test-PR. I'm hoping this makes scrolling work.

Make TOC box position absolute on all media formats

---

src/app/helpers/$.js

Do not prevent default on touch start, because that keeps put-away clicks from working

Allow clicks on TOC

---

src/app/pages/faculty-verification/faculty-verification.hbs
src/app/pages/finish-profile/faculty-section/faculty-section.hbs
src/app/pages/finish-profile/finish-profile.hbs

Add preferred email field to faculty-verification
Fix field names for email fields in finish-profile

Fix email issues

---

src/app/pages/details/details.hbs

change "get interested" to "sign up for info"

update cta copy on details page

---

src/app/components/get-this-title/get-this-title.hbs
src/app/components/get-this-title/get-this-title.js

Make it say “Download a PDF sample”

Change Download a PDF for coming soon books

---

src/app/helpers/book-titles.js
src/app/pages/comp-copy/comp-copy.hbs
src/app/pages/impact/impact.hbs
src/app/pages/impact/impact.scss

Also fix ampersand in value sent to Salesforce for Anatomy & Physiology

Add CTA with PDF link to Impact page

---

src/app/pages/details/details.js
src/app/pages/details/details.scss
src/app/pages/details/resource/resource.hbs
src/app/pages/details/resource/resource.js

Handle `link_external` as well as `link_document_url`
Tidy up link and lock positioning

Fix external links on Details page

---

src/app/components/get-this-title/get-this-title.scss
src/app/components/get-this-title/print-submenu/print-submenu.hbs
src/app/pages/subjects/subjects.scss

fixes https://trello.com/c/ZMtou7RR/1155-change-available-from-seller-openstax-college-on-amazon-to-available-from-seller-openstax-on-amazon# and https://trello.com/c/j7YpXS9X/1140-x-to-close-pdf-window-appears-in-middle-of-pdf-window

update openstax name on get-this-title & fix remover position

---

src/app/components/quotes/quotes.js
src/app/components/quotes/quotes.scss
src/app/pages/home/home.scss

Also:
Make bucket sizes adjust smoothly
Use variable-sized font for quote bucket

Top-align quote-box text on home page

---

src/app/components/products-boxes/products-boxes.scss
src/app/pages/higher-ed/higher-ed.hbs
src/app/pages/higher-ed/higher-ed.scss
src/styles/components/bucket.scss

Also:
Make the links line up
Adjust bucket title letter spacing on Higher Ed page

Fix Product Boxes link styles

---

src/app/components/buckets/buckets.js
src/app/components/shell/header/header.scss
src/app/pages/home/banners/biology/biology.scss
src/app/pages/home/education/education.hbs
src/app/pages/home/education/education.scss
src/app/pages/home/home.js

Home page phase 2 updates

---

src/app/pages/details/details.hbs
src/app/pages/details/details.js

On Details page, both at the top and the bottom, senior authors and
non-senior authors should be listed separately.

Handle top-of-page and senior author status independently

---

src/app/helpers/book-titles.js
src/app/helpers/salesforce.js
src/app/pages/adoption/adoption.hbs
src/app/pages/adoption/adoption.js
src/app/pages/faculty-verification/faculty-verification.hbs
src/app/pages/faculty-verification/faculty-verification.js
src/app/pages/finish-profile/already-using/already-using.hbs
src/app/pages/finish-profile/already-using/already-using.js
src/app/pages/finish-profile/faculty-section/faculty-section.hbs
src/app/pages/finish-profile/faculty-section/faculty-section.js

Make central book list object, separating published from coming-soon
books
Use list in adoption, interest, faculty-verification, and
finish-profile (faculty section)
Make central list object of acceptable answers to “how are you using
this book”
Add that question to faculty-verification and finish-profile

Ask "Are you already using the book"

---

src/app/helpers/$.js
src/app/pages/impact/impact.scss
src/app/pages/partners/partners.js

Adoption status changes were superseded by another PR, so I have removed that commit here.

Fix margin on Get The Application button

---

src/app/helpers/salesforce.js
src/app/pages/faculty-verification/faculty-verification.hbs
src/app/pages/faculty-verification/faculty-verification.js
src/app/pages/finish-profile/faculty-section/faculty-section.hbs
src/app/pages/finish-profile/faculty-section/faculty-section.js
src/app/pages/finish-profile/finish-profile.js

Add qtext member to salesforce answers, to answer “Are you already
using” vs “How are you using”
Reword question on Faculty Verification and Finish Profile
Use qtext answers on Faculty Verification and Finish Profile
Fix Finish Profile update hidden field when checkbox changes
programmatically

Update "Are you an adopter" text

---

src/app/pages/higher-ed/higher-ed.hbs
src/app/pages/higher-ed/higher-ed.js

Fetch page data from CMS
Build Quotes spec
Note: not fetching images to use

Restore callout boxes below Higher Ed banner

---

src/app/pages/mass-renewal/mass-renewal.hbs
src/app/pages/mass-renewal/mass-renewal.js
src/app/router.js
src/styles/components/forms.scss

Create the form and router entry, but not the item in the navigation bar

Create Mass Renewal Form

---

src/app/helpers/$.js
src/app/helpers/backbone/proxy-widget-view.js
src/app/pages/faculty-verification/faculty-verification.hbs
src/app/pages/faculty-verification/faculty-verification.js
src/app/pages/finish-profile/faculty-section/faculty-section.hbs
src/app/pages/finish-profile/faculty-section/faculty-section.js
src/styles/components/forms.scss

Define email validation test in $
Add custom validation check method to proxy-widget-view
Use custom validation check to call test and set states
Add validation-message to fields that displays when invalid
Modify proxy-widget-view so that it does not have to contain the submit
button

Restrict institutional email domains

---

src/app/pages/adoption/adoption.hbs
src/app/pages/mass-renewal/mass-renewal.hbs
src/app/pages/renewal/renewal.hbs

Add eMath and panOpen to dropdowns.

Add partners to Salesforce dropdowns

---

src/app/helpers/backbone/proxy-widget-view.js
src/app/pages/finish-profile/faculty-section/faculty-section.js
src/app/pages/finish-profile/finish-profile.js

Make faculty section elements non-required when the faculty section is
removed from the form.

Allow non-faculty to submit finish-profile

---

src/app/components/body-units/body-units.js
src/app/components/quote/quote.hbs
src/app/components/quotes/quotes.scss
src/app/models/imagemodel.js
src/app/models/searchmodel.js
src/app/pages/article/article.hbs
src/app/pages/article/article.js
src/app/pages/blog/article/article.hbs
src/app/pages/blog/article/article.js
src/app/pages/blog/pinned-article/pinned-article.hbs
src/app/pages/blog/pinned-article/pinned-article.js
src/app/pages/higher-ed/higher-ed.js
src/app/pages/higher-ed/higher-ed.scss
src/styles/components/bucket.scss

Revised quotes component to accept image URL

Use blog body segments to build articles

---

src/app/pages/article/article.js
src/app/pages/article/article.scss
src/app/pages/blog/article/article.js
src/app/pages/blog/article/article.scss
src/app/pages/blog/articles/articles.scss
src/app/pages/blog/pinned-article/pinned-article.js

fix article alignment & date format

---

src/app/pages/faculty-verification/faculty-verification.js
src/app/pages/faculty-verification/faculty-verification.scss

Hide all on form and add explanation

Disallow faculty-verification when request is pending

---

src/app/components/shell/header/header.scss

fix alignment of dropdown arrow next to logged in name in meta nav

fix alignment of dropdown arrow

---

src/app/helpers/$.js
src/app/helpers/partners.js
src/app/pages/adoption/adoption.hbs
src/app/pages/adoption/adoption.js
src/app/pages/mass-renewal/mass-renewal.hbs
src/app/pages/mass-renewal/mass-renewal.js
src/app/pages/renewal/renewal.hbs
src/app/pages/renewal/renewal.js

Create helper file for list of partners
Use helper list in all forms to create partners select options
Remove unused methods from $

Standardize partners list

---

src/app/pages/details/resource/resource.hbs

Display resource_description if it is defined

Show descriptions for resources

---

src/app/pages/cms/cms.js
src/app/router.js

Page name is simply the id number of the CMS entry
404 is special and must not be an ID

Display pages defined in the CMS

---

src/app/components/get-this-title/print-submenu/print-submenu.hbs

https://trello.com/c/dC8Sk7ko/1366-adjust-blurbs-on-get-print-copy-buttons

Adjust blurbs on Get Print Copy buttons

---

src/app/pages/faculty-verification/faculty-verification.hbs
src/app/pages/finished-verify/finished-verify.hbs

Fix confirmation timeframe

---

src/app/components/shell/header/header.hbs
src/app/pages/support/support.hbs
src/app/pages/support/support.js
src/app/pages/support/support.scss
src/app/router.js

Add menu item
Link to support pages at Salesforce

Create Support page

---

src/app/pages/about-us/about-us.scss
src/app/pages/home/home.js
src/app/pages/support/support.js
src/app/pages/support/support.scss

Also comment out Astronomy banner, since the book will not be available
for some months.

Fix About Us so names are not cut off

---

src/app/components/get-this-title/get-this-title.html
src/app/components/get-this-title/get-this-title.js
src/app/pages/finish-profile/finish-profile.html

Also added Bulk Orders button to AP Physics (link goes to non-existent
form)

Add email to finish-profile form

---

src/app/pages/about/about.html
src/app/pages/about/about.js

Change bio description and intro paragraph to plain text

Change About Us items to plain text

---

src/app/components/get-this-title/get-this-title.js
src/app/models/book-titles.js
src/app/pages/bulk-order/bulk-order.html
src/app/pages/bulk-order/bulk-order.js
src/app/pages/bulk-order/bulk-order.scss
src/app/pages/bulk-order/order-items.html
src/app/router.js

I think it has to be on dev to test the mail api.

Implement Bulk Order form (testing release)

---

src/app/pages/bulk-order/bulk-order.html
src/app/pages/bulk-order/bulk-order.js

If it all works, no further PR will be needed, but the mail can only be tested on the server.
CMS currently sends email to me instead of Tory.

Implement bulk order form, 2nd testing release

---

src/app/components/quotes/quotes.scss
src/app/controllers/cms.js
src/app/pages/about/about.js
src/app/pages/adoption/adoption.html
src/app/pages/ap/ap.html
src/app/pages/ap/ap.js
src/app/pages/blog/article/article.js
src/app/pages/blog/articles/articles.js
src/app/pages/blog/blog.js
src/app/pages/blog/newsPromise.js
src/app/pages/blog/pinned-article/pinned-article.js
src/app/pages/bulk-order/bulk-order.html
src/app/pages/comp-copy/comp-copy.html
src/app/pages/contact/contact.html
src/app/pages/contact/contact.js
src/app/pages/details/details.js
src/app/pages/faculty-verification/faculty-verification.html
src/app/pages/finish-profile/faculty-section/faculty-section.html
src/app/pages/finish-profile/finish-profile.html
src/app/pages/higher-ed/higher-ed.js
src/app/pages/home/home.js
src/app/pages/interest/interest.html
src/app/pages/partners/partners.js
src/app/pages/renew/renew.html
src/app/pages/subjects/book-viewer/book-viewer.js
src/app/pages/subjects/subjects.js

Copy changes on Interest form
Update email fields to be of type “email”
Copy changes on AP page

Assorted change requests

---

src/app/pages/give/give.hbs

Hotfix: Fix Give page recipient

---

src/app/pages/give/give.hbs

Change UPAY_SITE_ID on Give page to 9999, which is a development/test ID.

Change UPAY_SITE_ID on Give page

---

src/app/pages/confirmation/confirmation.js
src/app/pages/give/give.html
src/app/pages/give/give.js
src/app/pages/give/give.scss

Make it a variant of the Give page (instead of the confirmation page)
since the design is almost the same.

Make Give Thank You page according to visual design

---

src/app/components/shell/header/header.js
src/app/pages/details/details.js
src/app/pages/faculty-verification/faculty-verification.js

It used to be wrapped in an array

Hotfix: fix other calls to user API

---

src/app/pages/give/give.html
src/app/pages/give/give.js
src/app/pages/give/give.scss

Clicking Donate button takes them to donor information form

Add 2nd Give page

---

src/app/pages/adoption/adoption.html
src/app/pages/adoption/adoption.js
src/app/pages/bulk-order/bulk-order.js
src/app/pages/comp-copy/comp-copy.js
src/app/pages/contact/contact.html
src/app/pages/contact/contact.js
src/app/pages/faculty-verification/faculty-verification.js
src/app/pages/finish-profile/finish-profile.js
src/app/pages/give/give.html
src/app/pages/give/give.js
src/app/pages/give/give.scss
src/app/pages/interest/interest.js
src/app/pages/renew/renew.html
src/app/pages/renew/renew.js
src/app/router.js
src/styles/components/forms.scss

Make all forms validate like Bulk Order
Also:
Use detach instead of onClose
The select handler tries to tie itself to onClose, which is
getting broken when the view also defines onClose. This might
be something to find a more elegant solution to later.

Form fixes

---

src/app/components/shell/header/header.html
src/app/components/shell/header/header.js
src/app/controllers/cms.js
src/app/models/usermodel.js
src/app/pages/details/details-loaded.js
src/app/pages/faculty-verification/faculty-verification.js
src/app/pages/finish-profile/finish-profile.js

Also cleans up some anti-patterns with Promises.

Show User login status in header

---

src/app/pages/details/contents/content-item.js
src/app/pages/details/contents/contents.js

Chapter numbers should continue to increase across Unit divides
Preface check was registering false-positive for an Introduction to
chapter

Fix TOC numbering

---

.travis.yml
src/app/components/get-this-title/get-this-title.js
src/app/components/get-this-title/pdf-submenu/pdf-submenu.js
src/app/pages/give/give.hbs

Also disable Donate form on Give page

Hotfix: redirect to Subjects instead of Give page on download

---

src/app/pages/blog/blog.js
src/app/pages/foundation/foundation.html
src/app/pages/foundation/foundation.js

Also set Blog page description

Use CMS data for Foundation page

---

src/app/pages/give/give.html
src/app/pages/give/give.js

Also make sure validation works correctly

Verify Give page fields are correct

---

src/app/components/quotes/quote/quote.js
src/app/models/usermodel.js

Create model for loading /api/document
Use model in quote.js

Handle overlay on quote box

---

src/app/components/select/select.js
src/app/pages/adoption/adoption.html
src/app/pages/adoption/adoption.js
src/app/pages/adoption/adoption.scss
src/app/pages/bulk-order/bulk-order.js
src/app/pages/comp-copy/comp-copy.js
src/app/pages/contact/contact.js
src/app/pages/faculty-verification/faculty-verification.js
src/app/pages/finish-profile/finish-profile.js
src/app/pages/give/give.js
src/app/pages/interest/interest.js
src/app/pages/renew/renew.js
src/app/pages/subjects/subjects.html

Fall back to old-style events on systems that do not support `new Event`
Change invalid-form test to work in IE
Hide invalids on Subjects page

Fix selecthandler

---

src/app/pages/details/details.scss
src/app/pages/impact/impact.scss
src/app/pages/support/support.html
src/app/pages/support/support.scss

Also adjust sizing and placement

Fix Impact student z-index

---

src/app/pages/give/give.html

Fix typo in model variable name.

Fix Give page empty hidden field

---

src/app/components/category-selector/category-selector.js
src/app/components/shell/header/header.html
src/app/pages/finish-profile/finish-profile.html
src/app/pages/finish-profile/finish-profile.js
src/app/pages/partners/partners.html
src/app/pages/partners/partners.js
src/styles/components/filter-buttons.scss

Fix filter on narrow screen

---

src/app/models/usermodel.js

change load to do the fetch rather than to return the initial fetch

Fix usermodel

---

src/app/models/usermodel.js

Include same-origin credentials in fetch

Fix usermodel part 2

---

src/app/models/usermodel.js

Change credentials to ‘include’

Fix usermodel part 3

---

src/app/pages/faculty-verification/faculty-verification.js

Use sfUserModel (/api/user_salesforce) instead of userModel (/api/user)

Fix pending check

---

src/app/pages/accessibility-statement/accessibility-statement.html
src/app/pages/accessibility-statement/accessibility-statement.scss
src/app/pages/impact/impact.html
src/app/pages/impact/impact.js
src/app/pages/impact/impact.scss

Also update accessibility statement

Use cms data on impact page

---

src/app/components/shell/header/header.html
src/app/components/shell/header/header.js
src/app/components/shell/header/header.scss
src/app/components/shell/sticky-note/sticky-note.html
src/app/components/shell/sticky-note/sticky-note.js
src/app/components/shell/sticky-note/sticky-note.scss
src/app/pages/give/give.js
src/app/router.js

Add sticky note

---

src/app/pages/about/about.html
src/app/pages/about/about.js
src/app/pages/about/about.scss

Use color photos with transparency
Use same background as team

Change display of advisors

---

src/app/components/shell/sticky-note/sticky-note.scss
src/app/pages/bulk-order/bulk-order.js

Also remove letter spacing in sticky note

Fix csrf token on bulk order

---

src/app/components/products-boxes/product-box/product-box.html
src/app/components/products-boxes/products-boxes.js
src/app/components/products-boxes/products-boxes.scss
src/app/components/select/select.js
src/app/components/select/select.scss
src/app/pages/adopters/adopters.html
src/app/pages/adopters/adopters.js
src/app/pages/adopters/adopters.scss
src/app/pages/details/details.scss
src/app/pages/details/partner/partner.html
src/app/pages/higher-ed/higher-ed.html
src/app/pages/higher-ed/higher-ed.scss
src/app/pages/impact/impact.html
src/app/pages/impact/impact.scss
src/app/pages/support/support.html
src/app/pages/support/support.scss
src/styles/main.scss
src/styles/mixins/triangle.scss

Create “with-arrow” class, style in main.css
Use “with-arrow” class instead of all the individual triangles
Make “go-to” share “with-arrow” arrow
Also: Fix sorting and display on Adopters

Standardize CTA triangles

---

src/app/pages/subjects/book-viewer/book-viewer.js
src/app/pages/subjects/subjects.js

Coming Soon books at the end, others alphabetical by title

Sort books on Subjects page

---

src/app/components/get-this-title/get-this-title.js
src/app/helpers/$.js
src/app/pages/details/details-loaded.js
src/app/pages/details/details.js
src/app/pages/give/give.html
src/app/pages/give/give.js
src/app/pages/subjects/book-viewer/book-viewer.js
src/app/pages/subjects/book-viewer/category-section/book/book.js
src/app/pages/subjects/subjects.js

Also: use `coming_soon` data item to identify Coming Soon books

Use CMS data on Give page

---

src/app/components/shell/footer/footer.js
src/app/controllers/salesforce-form.js
src/app/models/usermodel.js
src/app/pages/adoption/adoption.html
src/app/pages/adoption/adoption.js
src/app/pages/comp-copy/comp-copy.html
src/app/pages/comp-copy/comp-copy.js
src/app/pages/contact/contact.html
src/app/pages/contact/contact.js
src/app/pages/faculty-verification/faculty-verification.html
src/app/pages/faculty-verification/faculty-verification.js
src/app/pages/finish-profile/finish-profile.html
src/app/pages/finish-profile/finish-profile.js
src/app/pages/interest/interest.html
src/app/pages/interest/interest.js
src/app/pages/renew/renew.html
src/app/pages/renew/renew.js
src/styles/main.scss

Also use document search for press kit link

Change form submission flow for better analytics

---

src/app/components/shell/sticky-note/sticky-note.html
src/app/components/shell/sticky-note/sticky-note.js
src/app/pages/give/give.js

Use content
Do not display sticky note if current date is after expires

Use CMS data on Sticky Note

---

src/app/components/shell/header/header.js

Just change currentTarget to target

Fix login menu

---

src/app/components/shell/header/header.html
src/app/components/shell/header/header.js
src/app/components/shell/header/header.scss
src/app/components/shell/header/main-menu/main-menu.html
src/app/components/shell/header/main-menu/main-menu.js
src/app/components/shell/header/main-menu/main-menu.scss
src/app/components/shell/header/upper-menu/upper-menu.html
src/app/components/shell/header/upper-menu/upper-menu.js
src/app/components/shell/header/upper-menu/upper-menu.scss
src/app/components/shell/sticky-note/sticky-note.scss

Divide menus into separate components
Simplify layout of chevrons
Simplify and regularize CSS

Refactor menu code

---

src/app/pages/partners/partners.js

Retain subject subdirectory in window location

Fix Partners "Return To Top" navigation

---

src/app/components/shell/header/header.html
src/app/components/shell/header/header.js
src/app/pages/blog/blog.html
src/app/pages/blog/blog.js
src/app/pages/blog/blog.scss
src/app/pages/details/details.js
src/app/pages/give/give.scss

Fix details path issue
Format Give page
Enable Blog, add newsletter sign-up link

Hotfixes 6 18

---

src/app/pages/subjects/book-viewer/category-section/book/book.html
src/app/pages/subjects/book-viewer/category-section/book/book.js
src/app/pages/subjects/subjects.js
src/app/pages/subjects/subjects.scss

On mobile device, open menu and scroll book to top
on other, go to details

Hotfix: Handle click on book in Subjects page

---

src/app/components/body-units/aligned-image.html
src/app/components/body-units/body-units.js
src/app/components/quotes/quote/quote.html
src/app/controllers/cms.js
src/app/pages/blog/article/article.js
src/app/pages/blog/article/article.scss
src/app/pages/blog/article/formatted-as/feature.html
src/app/pages/blog/article/formatted-as/formatted-as.js
src/app/pages/blog/blog.html
src/app/pages/blog/blog.js
src/app/pages/blog/blog.scss

Make newsletter signup below, not in line with, article blurbs
Include and format article tags
Handle body units for image and pull quote

Add Disqus comment section (only works for initial article load)

---

src/app/components/shell/header/header.js
src/app/pages/give/give.js
src/app/pages/home/home.js

Count page visits based on `init` of the homepage.
Hide sticky if `/give?thanks` is visited (donation has been completed)

Fix sticky note visit counter

---

src/app/pages/faq/faq.html
src/app/pages/faq/faq.js
src/app/pages/faq/faq.scss
src/app/router.js
src/styles/components/hero.scss
src/styles/main.scss

Create FAQ page
Populate page from CMS
Fix some layout issues

Add FAQ page

---

src/app/pages/blog/article/formatted-as/formatted-as.js
src/app/pages/blog/blog.js
src/app/pages/blog/blog.scss

Make Disqus comments show up
Fix header image
Fix navigation problems

Enable Disqus on Blog

---

src/app/pages/give/fbshare.html
src/app/pages/give/fbshare.js
src/app/pages/give/give.html
src/app/pages/give/give.js
src/app/pages/give/give.scss

Change thank you wording and add Facebook share button

Give Page: add Facebook share button

---

src/app/pages/blog/article/formatted-as/formatted-as.js
src/app/pages/faq/faq.html
src/app/pages/faq/faq.scss
src/app/pages/partners/partners.html
src/app/pages/partners/partners.js
src/app/pages/partners/partners.scss
src/styles/components/filter-buttons.scss

Styling issues per https://trello.com/c/mdxih2Vj

Update Partners page

---

src/app/components/shell/header/header.js
src/app/pages/give/give.js
src/app/pages/home/home.js

Compensate for being unable to write localStorage in Private window

Patch sticky note code for Safari private window

---

src/app/components/select/select.js
src/app/pages/give/give.html

Keypress in select scrolls to next item with that initial
Pressing Return selects topmost item

Make fields on Give page not required, and handle key events in Selects

---

src/app/pages/partners/partners.html
src/app/pages/partners/partners.js
src/app/pages/partners/partners.scss

Also:
Changed allies logo to gray to match visual design
Constrained text in hero

Use page_description text in Partners page

---

src/app/pages/faq/faq.html
src/app/pages/faq/faq.scss

Prevent sidebar box from wrapping
Add hanging indent to questions
Insert subhead paragraph as HTML

FAQ page fixups

---

src/app/pages/give/give.html
src/app/pages/give/give.scss

Show other ways to give on thanks page
Scale up Facebook button

Give page design fixes

---

src/app/pages/details/details.scss

Turn off flex wrap at desktop size

Fix book cover placement

---

src/app/pages/details/details-loaded.html
src/app/pages/details/details-loaded.js
src/app/pages/details/details.scss

add toggleFixedClass() code to get-this-title menu to prevent scrolling past footer

fix get-this-title menu scrolling

---

src/app/controllers/salesforce-form.js

Fix bug in sorting
Make list unique

Sort and unique adoption form titles

---

src/app/components/shell/header/header.scss

Can’t log in locally, so I have to test in dev.

Enable logout in IOS9

---

src/app/models/usermodel.js
src/app/pages/faculty-verification/faculty-verification.js

Allow query parameters to usermodel
Query salesforce user model with institutional email from the form (on
change)

Prevent multiple requests for faculty resources

---

src/app/components/shell/header/header.js
src/app/components/shell/header/header.scss
src/app/components/shell/header/main-menu/main-menu.scss
src/app/components/shell/header/upper-menu/upper-menu.scss
src/app/pages/home/banners/banner.js
src/app/pages/home/home.js
src/app/pages/home/home.scss

change banner parallax animations to animate using translate instead of top/left

fix banner animations

---

src/app/components/calculator/calculator.html
src/app/components/calculator/calculator.js
src/app/components/calculator/calculator.scss
src/app/components/spinner/spinner.html
src/app/components/spinner/spinner.js
src/app/components/spinner/spinner.scss
src/app/pages/confirmation/confirmation.scss

Add spacing to text below calculator
Supply up/down controls for the number fields
Center header text
Lighten text below calculator

Adjust calculator design

---

src/app/pages/details/contents/contents.js
src/app/pages/details/details-loaded.js

If they have contents, number them

Number Introduction chapters; freeze scrolling while TOC is up

---

src/app/components/shell/header/upper-menu/upper-menu.scss
src/app/helpers/$.js

* Browser detection works for Edge
* “Hi, User” menu displays in proper location in IE/Edge

Fix Windows regressions

---

src/app/pages/details/details.scss
src/app/pages/details/partner/partner.html
src/app/pages/details/resource/resource.html

Style Details page resource links

---

src/app/controllers/cms.js
src/app/pages/details/details.js

Force bookTitle (slug) to lowercase
route to 404 on error fetching book data

Handle capitalized book slugs

---

gulpfile.js
package.json
src/app/helpers/$.js
src/jspm.config.js

Edge 14 works, so:
updated version of superb
removed ava testing
added Edge < 14 to compatibility warning message

Fix navigation in Edge

---

gulpfile.js
package.json
src/app/components/shell/header/header.js
src/app/components/shell/header/main-menu/main-menu.html
src/app/components/shell/header/main-menu/main-menu.js
src/app/components/shell/header/main-menu/main-menu.scss
src/app/components/shell/header/upper-menu/upper-menu.html
src/app/components/shell/sticky-note/sticky-note.js
src/app/helpers/$.js
src/jspm.config.js

Also hide sticky note if there is no content

Move login to sticky menu

---

src/app/pages/give/give.html
src/app/pages/give/give.scss

2 columns of buttons on phone
2 rows of buttons on larger screens
IE layout matches other layouts
Fixed header text size

Fix Donation page layout

---

src/app/pages/errata/errata.js
src/app/pages/subjects/book-viewer/category-section/book/book.html
src/app/pages/subjects/book-viewer/category-section/book/book.js
src/app/pages/subjects/book-viewer/category-section/category-section.html
src/app/pages/subjects/subjects.scss

Also fixed errata title and changed heading tags on book viewer

Alt text for book covers

---

src/app/pages/errata/errata.js
src/app/pages/errata/errata.scss
src/app/pages/errata/form/form.html
src/app/pages/errata/form/form.js

Errata enable uploading of files

---

src/index.html

So they are set by initial page load

Put page meta descriptions in static page

---

src/app/pages/errata/errata.js
src/app/pages/errata/form/form.js

Takes parameters for source and location (to be passed from Concept Coach and Tutor)

Errata form parameters

---

src/app/pages/errata/form/form.html

Just a boilerplate hidden for now

Add submitter email to errata form

---

src/app/pages/contact/contact.html

Replace Contact page info

---

src/app/components/shell/header/header.js

This attempts a synchronous fetch of /accounts/logout.
Cannot be tested locally; test on dev

Force logout on window close

---

src/app/components/shell/footer/footer.scss
src/app/pages/accessibility-statement/accessibility-statement.scss
src/app/pages/contact/contact.scss
src/app/pages/errata/detail/detail.scss
src/app/pages/errata/errata.scss
src/app/pages/partners/partners.scss
src/app/pages/support/support.scss
src/styles/components/forms.scss
src/styles/main.scss

Set link color to cyan at top level
Remove redundant styling

Set default link styling

---

src/app/helpers/$.js

insertHtml should insert an empty string when it gets an undefined value

Fix tagline under instructor resources

---

src/app/components/shell/header/header.js

Reverts openstax/os-webview#748

Revert "Force logout on window close"

---

src/app/components/get-this-title/get-this-title.html
src/app/pages/errata/detail/detail.html

Force space between “PDF” and “sample”
Do not show webview link for coming soon books

Fix get this title links for coming soon books

---

src/app/pages/details/details-loaded.html
src/app/pages/details/details-loaded.js

1. Separate Login into Log in
2. Hide instructions if faculty or pending

Fix tagline under Instructor Resources: the sequel

---

src/app/pages/confirmation/confirmation.html
src/app/pages/confirmation/confirmation.js
src/app/pages/contact/contact.js

contact -> webContact
bulk-order -> contact

Differentiate confirmations for bulk order from contact

---

src/app/pages/errata/form/form.html
src/app/pages/errata/form/form.js
src/app/pages/errata/form/form.scss

Errata form: disable submit button on submit

---

src/app/pages/errata/form/form.html
src/app/pages/errata/form/form.js
src/app/pages/errata/form/form.scss

Also fix submit button styling, handle failed submission

Errata form: make text area not required

---

src/app/components/body-units/body-units.js
src/app/components/buckets/bucket/bucket.html
src/app/components/buckets/bucket/bucket.js
src/app/components/quotes/quote/quote.html
src/app/components/quotes/quote/quote.js
src/app/controllers/cms.js
src/app/pages/bulk-order/bulk-order.js
src/app/pages/details/partner/partner.html
src/app/pages/details/partner/partner.js
src/app/pages/home/education/education.html
src/app/pages/home/education/education.js
src/app/pages/home/home.js
src/app/pages/renew/renew.html
src/app/pages/subjects/book-viewer/book-viewer.js
src/app/pages/subjects/book-viewer/category-section/category-section.html
src/app/pages/subjects/book-viewer/category-section/category-section.js

Also use $.insertHtml to replace setting innerHTML where possible

Fix things marked FIX

---

src/app/components/category-selector/category-selector.html
src/app/components/category-selector/category-selector.js
src/app/pages/partners/partner-viewer/partner-viewer.js
src/app/pages/partners/partners.js
src/app/pages/subjects/book-viewer/book-viewer.js
src/app/pages/subjects/book-viewer/category-section/category-section.js
src/app/pages/subjects/subjects.js
src/styles/components/filter-buttons.scss

Also made category-selector a subclass of radio-panel

Selected item is gray, unselected is white

---

src/app/controllers/cms.js

Include credentials in slug fetches

Fix empty faculty resource link issue

---

src/app/pages/give/give.js

Update student give options

---

src/app/helpers/link.js
src/app/pages/blog/blog.html
src/app/pages/blog/blog.js

Recognize it as an “external” link

Open RSS link in new window

---

package.json
script/update
src/app/pages/details/details-loaded.html
src/jspm.config.js
src/jspm.dev.js

Instructor Resources link scrolls to Community Resources section

---

src/app/pages/confirmation/confirmation.js
src/app/router.js

Also remove student confirmation page, no longer used.

Add button on errata confirmation page to submit more errata

---

src/app/components/body-units/aligned-image.html
src/app/components/calculator/calculator.html
src/app/components/get-this-title/get-this-title.html
src/app/components/quotes/quote/quote.html
src/app/components/share/share.html
src/app/pages/about/about.html
src/app/pages/confirmation/confirmation.html
src/app/pages/details/details-loaded.html
src/app/pages/details/partner/partner.html
src/app/pages/foundation/foundation.html
src/app/pages/partners/partner-viewer/icons.html
src/app/pages/partners/partners.html

And blank alt text where the image is redundant

Add alt text from CMS to images

---

package.json
src/app/components/shell/header/header.js
src/app/components/shell/header/main-menu/main-menu.html
src/app/components/shell/header/main-menu/main-menu.js
src/app/components/shell/header/main-menu/main-menu.scss

Submenu items must get focus for the screenreader to announce them.
Handle aria-expanded properly.
Dropdown identification is strongly dependent on structure.

Make menubars work with screenreader

---

src/app/components/shell/header/main-menu/main-menu.js
src/app/pages/home/banners/banner.html

Also fix problem with Subjects menu popping open anytime a subjects
link is focused.

Remove hidden banner buttons from tab order

---

src/app/components/select/select.js
src/app/pages/renew/renew.html
src/app/pages/renew/renew.js
src/app/pages/renew/renew.scss

Also fix issue of required fields not showing validation messages

Fix tabbing on Renew form

---

src/app/components/shell/header/header.js
src/app/components/shell/header/main-menu/main-menu.html
src/app/components/shell/header/main-menu/main-menu.js
src/app/pages/openstax-tutor/openstax-tutor.js

Also the mail-on-a-line-by-itself thing I thought I already fixed

Fix training wheel scroll problem

---

src/app/components/shell/header/header.js
src/app/pages/openstax-tutor/openstax-tutor.js

Also fix training wheel issue Robert had

Fix Tutor marketing "where money goes" copy

---

src/app/components/shell/header/main-menu/main-menu.html
src/app/components/shell/header/upper-menu/upper-menu.html
src/app/pages/foundation/foundation.html
src/app/pages/foundation/foundation.scss

No longer display logo or description
Move Foundation Support menu item to upper menu and rename to Our
Supporters
Make Our Impact a simple menu item, not a dropdown

Rework Foundation page

---

README.md
script/update
script/upgrade

clarifies the difference between updating the local build and upgrading 3rd-party dependencies.
- `./script/update` updates the local files to match what is in git
- `./script/upgrade` upgrades the versions of 3rd-party dependencies and updates the `package.json` et all files that are stored in git

a script to update local version vs upgrade dependencies

---

src/jspm.config.js

I **think** this removes the remaining causes of rate limiting errors but I am unsure how to see which config (dev or not) is being used in this file. Maybe @RoyEJohnson would know?

replace github: with npm: package loading

---

src/app/components/form-input/form-input.scss
src/app/pages/bulk-order/bulk-order.scss
src/app/pages/home/home.scss
src/jspm.config.js

Missed a couple of color specs

Fix teacher dropdown

---

src/app/components/get-this-title/get-this-title.js
src/app/pages/details/details-loaded.js
src/app/pages/subjects/book-viewer/category-section/book/book.html
src/app/pages/subjects/book-viewer/category-section/book/book.js

Also relocate TOC-insertion code so it doesn’t depend on User info
being loaded.

Fix Polish "details" link and slug

---

src/app/models/usermodel.js
src/app/pages/details/details-loaded.js
src/app/pages/details/details.scss

Hotfix: show resources and partner blurbs on book details page

---

src/app/models/salesforce.js
src/app/pages/adoption/adoption.html
src/app/pages/adoption/teacher-form/teacher-form.html
src/app/pages/adoption/teacher-form/teacher-form.js
src/app/pages/comp-copy/comp-copy.html
src/app/pages/comp-copy/comp-copy.js
src/app/pages/contact/contact.html
src/app/pages/contact/contact.js
src/app/pages/give/give.html
src/app/pages/give/give.js
src/app/pages/interest/teacher-form/teacher-form.html
src/app/pages/interest/teacher-form/teacher-form.js

Fix Salesforce form routing for non-production environments

---

gulp/tasks/scripts.js
gulp/tasks/styles.js
gulp/tasks/templates.js
gulp/tasks/webpack.js
gulpfile.js
package.json
yarn.lock

This is a PR against `anticipated-merge`, a merge of `exclude-settings.js-from-bundle` and `master`. That shows which changes are actually new for purposes of code review.

Revise build system

---

gulp/tasks/webpack.js
package.json
yarn.lock

Also remove slow optimizations for dev builds

Add hardsource webpack plugin

---

src/app/pages/openstax-tutor/openstax-tutor.html
src/app/pages/openstax-tutor/openstax-tutor.js
src/app/pages/openstax-tutor/openstax-tutor.scss

Popup text appears on scroll
Adjust layout for better display on mobile

Tutor Marketing page fixes

---

src/app/pages/openstax-tutor/openstax-tutor.js
src/app/pages/openstax-tutor/pulsing-dot/pulsing-dot.html
src/app/pages/openstax-tutor/pulsing-dot/pulsing-dot.js
src/app/pages/openstax-tutor/pulsing-dot/pulsing-dot.scss

Use pop_up_text from CMS for pulse button text

Fix pulse button text

---

src/app/pages/openstax-tutor/openstax-tutor.html
src/app/pages/openstax-tutor/openstax-tutor.scss
src/settings-example.js

Popup text more controlled
space for floating navigation tools
stop science particles from blocking link click

Tutor marketing page layout fixes

---

src/app/components/form-checkboxgroup/form-checkboxgroup.html
src/app/components/form-radiogroup/form-radiogroup.html
src/app/pages/adoption/adoption.scss
src/app/pages/adoption/teacher-form/teacher-form.html
src/styles/components/forms.scss

Also: fix highlight for invalid checkboxes/radio buttons

Move error messages to bottom of groups

---

src/app/pages/subjects/subjects.scss

Also adjust books-per-line at various widths

Stick Subjects filter to nav bar on mobile

---

src/app/pages/adoption/teacher-form/teacher-form.html

Adoption form patch

---

src/app/pages/comp-copy/comp-copy.html
src/app/pages/comp-copy/comp-copy.scss

Changes to other forms messed it up. Made it more consistent

Fix up Comp Copy form

---

src/app/pages/blog/article/article.scss
src/app/pages/blog/article/formatted-as/feature.html
src/app/pages/blog/blog.scss

Fix blog typography

---

package.json
src/app/components/shell/header/main-menu/dropdown/dropdown.html
src/app/components/shell/header/main-menu/dropdown/dropdown.js
src/app/components/shell/header/main-menu/main-menu.html
src/app/components/shell/header/main-menu/main-menu.js
test/src/components/header.test.js
yarn.lock

It doesn't look like logout handles redirect. It also looks like it doesn't reliably handle logging out. We may need changes in Accounts or the CMS (which passes thru the logout request).

Redirect back to current page after login

---

src/app/components/dialog/dialog.html
src/app/components/dialog/dialog.js
src/app/components/dialog/dialog.scss
src/app/components/get-this-title-new/get-this-title.html
src/app/components/get-this-title-new/get-this-title.js
src/app/components/get-this-title-new/toc-dialog/toc-dialog.html
src/app/components/tab-group/tab-group.html
src/app/components/tab-group/tab-group.scss
src/app/components/tab-group/tab/tab.js
test/src/components/tab-group.test.js

Also: Improve tab group accessibility

Fix keyboard traps on Details page

---

src/app/components/shell/header/main-menu/dropdown/dropdown.js
src/app/pages/details/contents/contents.js
src/app/pages/openstax-tutor/openstax-tutor.js

Number TOC entry if it is Introduction something (not just Introduction by itself)
Fix dropdown menu for touch devices
Fix menu issue on Tutor Marketing page

Three small bug fixes

---

src/app/pages/bookstore-suppliers/bookstore-suppliers.html
src/app/pages/bookstore-suppliers/bookstore-suppliers.scss

Center button on bottom
Don't display before data is loaded

Bookstore Suppliers fixes

---

src/app/pages/about-new/about-new.html
src/app/pages/about-new/about-new.js
src/app/pages/about-new/about-new.scss
src/app/pages/about/about.js
src/app/router.js

This creates the new About page at /about-new
The old About page is still active at /about

New about us page

---

src/app/pages/press/press.js

Apparently I should have checked the documentation the last time I fixed this.

Fix dates for Press page

---

src/app/pages/adoption/adoption.js
src/app/pages/errata/errata.js

Also fix title on Adoption form

Do not 404 on Errata form when book parameter is wrong

---

script/bootstrap
script/upgrade

Related issue https://github.com/Connexions/cnx-recipes/pull/462

Update 'which' to 'command -v'

---

src/app/components/get-this-title/get-this-title.html
src/app/components/get-this-title/get-this-title.js
src/app/helpers/$.js
src/app/pages/details/details.js
src/app/pages/details/let-us-know/let-us-know.js
src/app/pages/details/phone-view/details-pane/details-pane.js
src/app/pages/details/phone-view/errata-pane/errata-pane.js
src/app/pages/details/phone-view/phone-view.js
src/app/pages/subjects/book-viewer/category-section/book/book.js

isPolish helper checks either slug or title for fizyka or Polska (which is part of the Salesforce title)

Handle new slugs for Katalyst physics books

---

src/app/pages/details/details-tab/details-tab.js
src/app/pages/research/research.scss

Also handles Polish book links to adoption and interest forms

Fix research banner layout on safari

---

src/app/pages/team/people-tab/people-tab.html
src/app/pages/team/people-tab/people-tab.js
src/app/pages/team/people-tab/people-tab.scss

Also widen cards that have inline bios. (Strategic Advisors)

Fix bio position on Team page

---

src/app/pages/adoption/adoption.js

There is no card for this - it is a late fix for the RC.

Change book prompt on Adoption form

---

src/app/components/shell/header/header.js
src/app/components/shell/header/header.scss
src/app/components/shell/header/main-menu/dropdown/dropdown.scss
src/app/components/shell/sticky-note/sticky-note.js
src/app/components/shell/sticky-note/sticky-note.scss
src/app/pages/home/home.scss
src/styles/main.scss

Cleans up lots of behavior around the use of images in the give-sticky.

Fix header sizing around sticky note

---

src/app/pages/home/banner-carousel/banner-carousel.scss
src/app/pages/team/people-tab/people-tab.scss

Also center-justify team images on their cards

Fix Edge banner display

---

src/app/components/shell/shell.html
src/app/pages/a-page-template/a-page-template.js
src/app/pages/about/about.js
src/app/pages/adopters/adopters.js
src/app/pages/adoption-confirmation/adoption-confirmation.html
src/app/pages/adoption/adoption.js
src/app/pages/blog/blog.js
src/app/pages/bookstore-suppliers/bookstore-suppliers.js
src/app/pages/bulk-order/bulk-order.js
src/app/pages/details/details.js
src/app/pages/errata/errata.js
src/app/pages/faq/faq.js
src/app/pages/foundation/foundation.js
src/app/pages/home/home.js
src/app/pages/interest/interest.js
src/app/pages/openstax-tutor/openstax-tutor.js
src/app/pages/partners/partners.js
src/app/pages/research/research.js
src/app/pages/subjects/subjects.js
src/app/pages/team/team.js
src/app/pages/technology/technology.js

Have at most one main tag per page

---

package.json
src/app/components/shell/header/header.scss
src/app/version.js
src/index.html

Fix Subjects page scrolling issue for Edge

---

src/app/pages/home/banner-carousel/banner-carousel.js

Adding to strings concatenates.

Fix banner scrolling issue

---

src/app/pages/impact-dev/impact-dev.html
src/app/pages/impact-dev/map/map.html
src/app/pages/impact-dev/map/map.js
src/app/pages/impact-dev/map/map.scss
src/app/pages/impact-dev/map/mapdropdown.js
src/app/pages/impact-dev/map/schoolinfo.js
src/app/pages/impact-dev/map/testimonial.js
src/app/pages/impact-dev/schoolmap/schoolmap.js
src/app/pages/impact-dev/schoolmap/schoolmap.scss
src/app/pages/impact-dev/statistics/stat.html
src/app/pages/impact-dev/statistics/stat.js
src/app/pages/impact-dev/statistics/stat.scss
src/app/pages/impact-dev/studentinfo/studentinfo.html
src/app/pages/impact-dev/studentinfo/studentinfo.js
src/app/pages/impact-dev/studentinfo/studentinfo.scss
src/app/pages/separatemap/separatemap.scss

Fix HTML indentation
Use pattern library where possible for colors, font setting, and media queries
Media queries must use `em` units - use pattern library predefines when possible
No closing tags on `<input>`
Remove unnecessary $.insertHtml calls

Clean up code (for merge to our-impact-map-page branch)

---

src/app/helpers/$.js
src/app/pages/blog/article/article.js
src/app/pages/blog/article/article.scss
src/app/pages/blog/article/formatted-as/formatted-as.js
src/app/pages/blog/blog.js

And begin excerpt with the first `<p>`

Dynamically load blog articles

---

src/app/components/shell/header/header.js

Was searching for the wrong value in groups list (value changed when we started using Accounts directly to generate user info)

Fix excessive polling for Tutor

---

package.json
src/app/pages/blog/article/article.scss
src/app/version.js
src/index.html

Also update version and remove no-longer-needed-classList CDN

Allow link text to wrap in blog articles

---

src/app/controllers/cms.js
src/app/pages/blog/article/article.scss

This actually also fixes the blog page in general, which is broken in dev/qa.

Fix blog preview in Edge

---

src/app/pages/details/details-tab/details-tab-polish.html
src/app/pages/details/details-tab/details-tab.html
src/app/pages/details/phone-view/publication-details/publication-details.html

the HTML space was being inserted as a literal

replace literal with a space

---

src/app/pages/rover-by-openstax/rover-by-openstax.html
src/app/pages/rover-by-openstax/rover-by-openstax.js
src/app/pages/rover-by-openstax/signup-form/signup-form.js
src/app/pages/subjects/subjects.js

Stop scrolling to form on page load
Hide submit button after submitting
Fix images in section 3

Little Rover fixes

---

script/build

Deployment needs the stuff in /app

Let /dist/app live

---

script/build
src/app/pages/general/general.html

Also cleanup non-CSS files from /dist/app

Handle HTML block on General pages

---

src/app/pages/rover-by-openstax/signup-form/signup-form.html
src/app/pages/rover-by-openstax/signup-form/signup-form.js

Faculty and Adjunct Faculty get the number of students field.

Rover form: Only show number of students field for instructors

---

src/app/pages/annual-report/annual-report.js
src/index.html
yarn.lock

Only put in default values when they are not supplied.

Revise annual report

---

src/app/pages/annual-report/annual-report.js
src/app/pages/annual-report/annual-report.scss
src/app/pages/annual-report/section/disruption.html
src/app/pages/annual-report/section/founding.scss
src/app/pages/annual-report/section/lookingAhead.html
src/app/pages/annual-report/section/map.html
src/app/pages/annual-report/section/map.scss
src/app/pages/annual-report/section/philanthropic-partners.html
src/app/pages/annual-report/section/philanthropic-partners.scss
src/app/pages/annual-report/section/reach.html
src/app/pages/annual-report/section/reach.scss
src/app/pages/annual-report/section/revolution.html
src/app/pages/annual-report/section/section.js
src/app/pages/annual-report/section/sustainability.html
src/app/pages/annual-report/section/testimonials.html
src/app/pages/annual-report/section/tutor.html
src/app/pages/annual-report/section/tutor.scss

Lots of layout problems per https://docs.google.com/document/d/1Z95NxjYTMXu_BYQcmIBIalZ2bPNkch1ipoiiEOtSzWs/edit

Fix Annual Report layout

---

package.json
src/app/helpers/controller/init-mixin.js
src/app/pages/interest/interest.js
src/index.html

Canonical link init wasn't being called.

Fix Interest form submission

---

src/app/pages/footer-page/footer-page.js
src/app/pages/give/give.js

Updated how this.insertHtml works but neglected to update footer-page to use it that way.

Fix footer pages

---

src/app/pages/give/give.js

Functions in model were not properly bound

Fix Give page

---

package.json
src/app/pages/annual-report/annual-report.html
src/app/pages/annual-report/annual-report.scss
src/app/pages/annual-report/section/map.scss
src/app/pages/annual-report/section/philanthropic-partners.html
src/app/pages/annual-report/section/revolution.html
src/app/pages/annual-report/section/revolution.scss
src/app/pages/annual-report/section/tutor.scss
src/index.html

Per comments in https://docs.google.com/document/d/1Z95NxjYTMXu_BYQcmIBIalZ2bPNkch1ipoiiEOtSzWs/edit

Touchup new impact page

---

src/app/pages/annual-report/annual-report.scss
src/app/router.js

Chevrons in links didn't line up in Safari
Block of text wasn't on its background (Safari)
Links to openstax.org didn't work because they got trimmed to nothing.

Fix some issues Malar found on the Annual Report page

---

CONTRIBUTING.md
src/app/components/a-component-template/a-component-template.js
src/app/pages/a-page-template/a-page-template.js

Create CONTRIBUTING.md file

---

src/app/pages/rover-by-openstax/sections/getting-started.scss
src/app/pages/rover-by-openstax/sections/video.scss

Remove conflicting image-sizing constraints, and adjust size down slightly.

Fix Rover mobile animations

---

src/index.html

So it will be available to send page view information.

Load Analytics first

---

src/app/components/role-selector/role-selector.js
src/app/pages/adoption/adoption.js
src/app/pages/adoption/hidden-fields/hidden-fields.html
src/app/pages/adoption/hidden-fields/hidden-fields.js
src/app/pages/interest/hidden-fields/hidden-fields.html
src/app/pages/interest/hidden-fields/hidden-fields.js
src/app/pages/interest/interest.js

Send correct roles to Salesforce from Adoption and Interest forms

---

src/app/pages/hero-journey/hero-journey.js
src/app/pages/hero-journey/numbered-navigator/numbered-navigator.js
src/app/pages/hero-journey/numbered-navigator/numbered-navigator.scss
src/app/pages/hero-journey/sections/books/books.html
src/app/pages/hero-journey/sections/share/share.html
src/app/pages/hero-journey/sections/share/share.js
src/app/pages/hero-journey/sections/share/share.scss
src/app/pages/hero-journey/sections/thanks/thanks.html
src/app/pages/hero-journey/sections/thanks/thanks.js
src/app/pages/hero-journey/sections/thanks/thanks.scss

Fix testimonial form on Hero Journey page

---

src/app/pages/hero-journey/hero-journey.js
src/app/pages/hero-journey/sections/books/books.html
src/app/pages/hero-journey/sections/books/books.scss
src/index.html
src/settings-example.js

Also don't defer analytics and optimizely scripts, so they're definitely loaded before our scripts.

Update login notice, fix adoption detection code

---

src/app/models/salesforce.js
src/app/pages/adoption-confirmation/supplemental-form.html
src/app/pages/adoption/adoption.js
src/app/pages/details/request-form/request-form.html
src/app/pages/give/give.html
src/app/pages/hero-journey/sections/share/share.js
src/app/pages/impact-dev/impact-dev.js
src/app/pages/impact-dev/map/map.scss
src/app/pages/impact-dev/map/mapdropdown.html
src/app/pages/impact-dev/map/schoolinfo.html
src/app/pages/impact-dev/map/schoolinfo.js
src/app/pages/impact-dev/map/testimonial-form.html
src/app/pages/impact-dev/map/testimonial-form.js
src/app/pages/impact-dev/map/testimonial-form.scss
src/app/pages/impact-dev/map/testimonial.html
src/app/pages/impact-dev/map/testimonial.js
src/app/pages/interest/interest.js

Since the link is in at the school level, and it requires login, you may wind up having to search again after login. Might consider moving it. School is pulled from account info, so the link doesn't need to be at that level.

Add testimonial form to map

---

gulp/tasks/webpack.js
package.json
src/app/pages/institutional-partnership/application.js
src/app/pages/institutional-partnership/institutional-partnership.html
src/app/pages/institutional-partnership/institutional-partnership.js
src/app/pages/institutional-partnership/institutional-partnership.scss
src/app/pages/institutional-partnership/program-details.html
src/app/pages/institutional-partnership/program-details.js
src/index.html

Populate Institutional Partnership page from CMS

---

src/app/pages/subjects/book-viewer/book-viewer.js

The AP section was not being populated properly. It is now.

Fix AP listings on Subjects page

---

gulp/tasks/webpackDll.js
package.json
script/build
src/app/main.js
src/index.html
yarn.lock

Update version numbers
Apply today's hotfix to master

Remove whatwg-fetch and add cache-busting

---

src/app/pages/hero-journey/hero-journey.js
src/app/pages/hero-journey/numbered-navigator/numbered-navigator.js
src/app/pages/hero-journey/numbered-navigator/numbered-navigator.scss
src/app/pages/hero-journey/sections/books/books.html
src/app/pages/hero-journey/sections/quiz/quiz.scss
src/app/pages/hero-journey/sections/share/share.html
src/app/pages/hero-journey/sections/try/try.html

Multiple cards on Victoria's Trello board

Fixups for Hero Journey page

---

src/app/components/shell/header/header.js
src/app/helpers/link.js

Handle oxauth path as external link

---

src/app/pages/hero-journey/hero-journey.js
src/app/pages/hero-journey/hero-journey.scss
src/app/pages/hero-journey/numbered-navigator/numbered-navigator.js
src/app/pages/hero-journey/numbered-navigator/numbered-navigator.scss
src/app/pages/hero-journey/sections/books/books.html
src/app/pages/hero-journey/sections/quiz/quiz.html
src/app/pages/hero-journey/sections/quiz/quiz.js
src/app/pages/hero-journey/sections/quiz/quiz.scss
src/app/pages/hero-journey/sections/share/share.html
src/app/pages/hero-journey/sections/share/share.js
src/app/pages/hero-journey/sections/try/try.html

See https://trello.com/b/Vr2DfPT7/ux-review-spring-campaign for cards

Spring campaign ux review issues

---

package.json
src/app/pages/institutional-partnership/application.html
src/app/pages/institutional-partnership/institutional-partnership.scss
src/index.html

Put formstack form in an iframe

---

package.json
src/app/pages/hero-journey/hero-journey.scss
src/index.html

Also update release version number

Move submit button to right side

---

src/app/components/student-form/student-form.js
src/app/pages/adoption/adoption.js
src/app/pages/interest/interest.js
src/app/pages/rover-by-openstax/rover-by-openstax.js

Add Pardot tracking to Rover marketing page

---

src/app/components/shell/footer/footer.js
src/app/components/shell/header/upper-menu/upper-menu.js
src/app/controllers/cms.js
src/app/helpers/analytics.js
src/app/models/book-titles.js
src/app/models/books.js
src/app/models/partners.js
src/app/models/schools.js
src/app/models/subjectCategories.js
src/app/models/usermodel.js
src/app/pages/bulk-order/bulk-order.html
src/app/pages/bulk-order/bulk-order.js
src/app/pages/contact/contact.js
src/app/pages/errata/detail/detail.js
src/app/pages/errata/errata.js
src/app/pages/errata/form/form.js
src/app/pages/general/general.js
src/app/pages/global-reach/map/map.js
src/app/pages/hero-journey/hero-journey.js
src/app/pages/press/press.js
src/index.html
test/src/data/books.js
test/src/data/details.js

Preparing for move to cloudfront

Replace /api with /apps/cms/api

---

src/app/pages/rover-by-openstax/sections/meet-rover.html
src/app/pages/rover-by-openstax/sections/meet-rover.scss

Make Rover page cards form an even grid

---

src/app/models/usermodel.js

remove /apps/cms from accounts login path

Fix login link

---

src/app/pages/partners/partners.js
src/app/router.js

Fix router and Partners page

---

src/app/pages/institutional-partner-program/sections/big-quote/big-quote.scss

Fix big quote section of Institutional Partnership Program page

---

src/app/pages/hero-journey/hero-journey.js

Accessing nonexistent data item

Fix Hero Journey final section

---

src/app/components/radio-panel/radio-panel.js

Restore code that was removed due to misjudgment.

Fix mobile subject picker

---

src/app/pages/details/details.js

This provides information, including published and modified dates, for search engines.

Add JSON-LD section to book details

---

src/app/components/shell/footer/footer.scss
src/app/pages/institutional-partner-program/institutional-partner-program.scss
src/app/pages/openstax-tutor/openstax-tutor.js
src/app/pages/openstax-tutor/openstax-tutor.scss

UX footer and IPP fixes, round 2

---

gulp/config.js
gulp/tasks/html.js

and also output files with rev hash into correct directory

remove cms/assets prefix 

---

gulp/config.js
gulp/tasks/html.js
gulp/tasks/styles.js
gulp/tasks/webpack.js
gulpfile.js

this stores scripts in `dist/cms/assets/scripts` and styles in `dist/cms/assets/styles`

add trailing slash; store files in directory specified by urlPrefix

---

gulp/tasks/copy.js
gulp/tasks/html.js
gulp/tasks/styles.js
package.json
src/index.html
src/styles/fonts.scss
yarn.lock

Enables them to also be cached by cloudfront

Serve fonts from configured directory

---

src/app/components/shell/footer/footer.js
src/app/components/shell/header/upper-menu/upper-menu.js
src/app/helpers/analytics.js
src/app/helpers/controller/cms-mixin.js
src/app/models/book-titles.js
src/app/models/books.js
src/app/models/partners.js
src/app/models/schools.js
src/app/models/subjectCategories.js
src/app/models/usermodel.js
src/app/pages/bulk-order/bulk-order.html
src/app/pages/bulk-order/bulk-order.js
src/app/pages/details/resource-box/resource-box.js
src/app/pages/errata/detail/detail.js
src/app/pages/errata/errata.js
src/app/pages/errata/form/form.js
src/app/pages/general/general.js
src/app/pages/global-reach/map/map.js
src/app/pages/hero-journey/hero-journey.js
src/settings-example.js

Requires a new entry in settings.js

Change /api calls to use /apps/cms/api

---

src/app/components/sticky-footer/sticky-footer.scss
src/app/pages/institutional-partnership/institutional-partnership.scss
src/app/pages/institutional-partnership/sections/sign-up/sign-up.scss

A couple issues found in testing the branch that ultimately we are not releasing.

Fix ipp issues

---

.travis.yml
Gemfile
README.md
gulp/tasks/styles.js
package.json
script/bootstrap
yarn.lock

Ruby Sass has reached end-of-life and will not longer build on Travis.

Remove Ruby and use sass-lint

---

src/app/pages/details/details.html
src/app/pages/details/details.js
src/app/pages/details/details.scss
src/app/pages/details/instructor-resource-tab/instructor-resource-tab.html
src/app/pages/details/instructor-resource-tab/instructor-resource-tab.scss

Already had the tab created, just needed to enable it, rename it, and move it.

Move Partners to their own tab on Details page

---

src/app/pages/hero-journey/numbered-navigator/numbered-navigator.js
src/app/pages/hero-journey/numbered-navigator/numbered-navigator.scss

Eliminate dragging artifacts by using 3d engine
Keep track of current node

Fix hero journey milestone animation oddities

---

src/app/components/get-this-title/toc-dialog/toc-dialog.js
src/app/pages/details/contents/content-item.html
src/app/pages/details/contents/contents.js
src/app/pages/details/details-tab/details-tab.js
src/app/pages/details/details.js
src/app/pages/details/details.scss
src/app/pages/details/phone-view/phone-view.js
src/app/pages/details/resource-box/resource-box.js

Table of contents is in new tab
Tab labels are not quite as big, since there are more of them
TOC entries are links to the correct CNX pages

Include full TOC on book detail pages

---

src/app/pages/institutional-partnership/institutional-partnership.js
src/app/pages/institutional-partnership/sections/participants/participants.html
src/app/pages/institutional-partnership/sections/participants/participants.js
test/helpers/fetch-mocker.js

and only established members on popup

Show only current cohort on IPP

---

src/app/pages/institutional-partnership/sections/promoting/promoting.scss
src/app/pages/institutional-partnership/sections/results/results.scss

UX review issues for IP page

---

src/app/helpers/link.js
src/app/models/usermodel.js
src/index.html

I think the problem is that I removed a needed `resolve` call along with some debugging code.

Route oxauth properly (2nd try)

---

src/app/helpers/link.js

I made a subtle error in refactoring a regex

Fix internal link handling in router

---

src/app/components/shell/footer/footer.html
src/app/components/shell/footer/footer.scss
src/app/components/shell/header/main-menu/dropdown/dropdown.scss

The footer headings were not accessible.
The login menu was not aligned properly.

Fix login menu and footer headings

---

src/app/pages/impact/impact.scss

So the person is onscreen on mobile devices

Adjust banner image position on Impact page

---

src/app/pages/details/details.scss

Adds line break for book contents as requested.

Adds line break for book contents.

---

src/app/components/shell/header/header.js
src/app/components/shell/header/header.scss
src/app/pages/home/banner-carousel/banner-carousel.js

Also optimize banner image loading: wait for the first image to finish loading, pause to let the browser realize loading is complete (hi, Google!) and then set the remaining banner images.

No more gray menu

---

src/app/pages/rover-by-openstax/rover-by-openstax.js
src/app/pages/rover-by-openstax/rover-by-openstax.scss
src/app/pages/rover-by-openstax/sections/banner.html
src/app/pages/rover-by-openstax/sections/banner.js
src/app/pages/rover-by-openstax/sections/banner.scss
src/app/pages/rover-by-openstax/sections/faq.js
src/app/pages/rover-by-openstax/sections/getting-started.js
src/app/pages/rover-by-openstax/sections/lms.js
src/app/pages/rover-by-openstax/sections/meet-rover.html
src/app/pages/rover-by-openstax/sections/meet-rover.js
src/app/pages/rover-by-openstax/sections/navigator/navigator.html
src/app/pages/rover-by-openstax/sections/navigator/navigator.js
src/app/pages/rover-by-openstax/sections/navigator/navigator.scss
src/app/pages/rover-by-openstax/sections/section.js
src/app/pages/rover-by-openstax/sections/stepwise.js
src/app/pages/rover-by-openstax/sections/video.js

New navigator is a set of down-page links

Change navigation on rover page

---

src/app/components/get-this-title/toc-dialog/toc-dialog.js
src/app/pages/details/details-tab/details-tab.js
src/app/pages/details/details.js
src/app/pages/details/details.scss

It's a little complicated, but I've finally rebased and gotten to the minimal-changes PR to revert the old TOC tab PR.

Remove toc tab changes

---

src/app/pages/blog/article/formatted-as/feature.html
src/app/pages/blog/article/formatted-as/formatted-as.js
src/app/pages/press/press-excerpt/press-excerpt.html

Handle image alt tags for press and blog

---

src/app/models/mapbox.js
src/app/pages/global-reach/global-reach.js
src/app/pages/global-reach/map/map.html
src/app/pages/global-reach/map/map.js
src/app/pages/global-reach/map/map.scss
src/app/pages/global-reach/map/mapdropdown.html
src/app/pages/global-reach/map/mapdropdown.js
src/app/pages/global-reach/map/schoolinfo-head.html
src/app/pages/global-reach/map/schoolinfo-head.js
src/app/pages/global-reach/map/testimonial.js
src/app/pages/separatemap/separatemap.html
src/app/pages/separatemap/separatemap.js
src/settings-example.js
yarn.lock

This introduces two new settings to settings.json.
mapboxStyle should be an environment setting that is different for all environments.

Mapbox Redo. Fixes cards that are related to global-impact map.

---

src/styles/components/radio-buttons.scss

I don't know what threw this off. This formulation is a little simpler.

Fix radio button layout

---

src/app/pages/details/details.html
src/app/pages/details/details.js
src/app/pages/details/details.scss

Add padding to top and bottom of ToC area so scrolling doesn't seem like it's pushing it under the banner and footer.
Fix the squishing of the page contents

ToC UX fixes for padding and content sizing

---

src/app/components/shell/header/header.js

This will need to be really verified in cms-dev.

Send anonymous user id to Pulse Insights

---

src/app/pages/hero-journey/hero-journey.js
src/app/pages/hero-journey/sections/books/books.html
src/app/pages/hero-journey/sections/books/books.scss

Put up a placeholder notice, but keep all the old code available to be turned back on.

Fix login problem and turn off Hero Journey page

---

src/app/components/tab-group/tab-group.js
src/app/pages/details/details.scss

Also fix resources cards layout so they don't overhang their allotted space.

Resize ToC when tab changes

---

src/app/pages/details/details-tab/details-tab-polish.html
src/app/pages/details/details-tab/details-tab.js

A couple of changes to conditionally-included bits.
Check `bookState === 'live'` instead of the `comingSoon` flag in the Polish books
Check that it has a table of contents before trying to build it.

Fix ToC issue for Coming Soon books

---

src/app/pages/details/details.js
src/app/pages/general/general.js

Just a single character change

Fix capitalization of Partner resources tab

---

src/app/pages/hero-journey/hero-journey.js

Don't load all the page features if the page is turned off. Also, control that with a state variable.

Do a better job turning off Hero Journey page

---

src/app/pages/details/details.js

book_contributing_authors -> authors

Change name of author field

---

src/app/pages/rover-by-openstax/popup/popup.html
src/app/pages/rover-by-openstax/popup/popup.js
src/app/pages/rover-by-openstax/popup/popup.scss

Take put-away icon out of flow so text is not pushed down
Let image overlap text block a little bit

Adjust layout

---

src/app/components/shell/header/header.js
src/app/components/shell/header/header.scss
src/app/components/shell/header/main-menu/main-menu.html
src/app/components/shell/header/main-menu/main-menu.scss

Also replace hamburger menu with standard icons

Resize OS logo on mobile view

---

src/app/pages/details/resource-box/resource-box.js
test/src/pages/details/resource-box.test.js
test/src/pages/details/student-resources-pane.test.js

In resource boxes and tests of those.

Change "Click here to unlock" to "Login to unlock"

---

package.json
src/app/pages/rover-by-openstax/popup/popup.scss

Fix Rover button width on mobile

---

src/app/pages/details/details.scss
src/app/pages/details/phone-view/phone-view.scss

Resize book banners to conform with REX

---

src/app/helpers/analytics.js
src/app/pages/rover-by-openstax/popup/popup.scss

Added the call. Will need to verify that it's happening in dev.

Add user id tracking to Google Analytics

---

src/app/components/dialog/dialog.js
src/app/components/dialog/dialog.scss
src/app/components/get-this-title/get-this-title.js
src/app/components/modal-content/modal-content.js
src/app/components/shell/cookie-notice/cookie-notice.html
src/app/components/shell/cookie-notice/cookie-notice.js
src/app/components/shell/cookie-notice/cookie-notice.scss
src/app/components/shell/shell.js
src/app/helpers/analytics.js
test/src/components/modal-content.test.js

This also fixes a bug in the user tracking code.

Implement cookie notice as footer-dialog

---

src/app/pages/general/general.js

This may be a hotfix as well as a PR.

Fix scripts on general pages

---

src/app/components/dialog/dialog.scss
src/app/components/shell/cookie-notice/cookie-notice.html
src/app/components/shell/cookie-notice/cookie-notice.js
src/app/components/shell/cookie-notice/cookie-notice.scss
src/app/components/shell/shell.js
src/styles/main.scss

Change text, use link instead of second button for privacy policy, handle no-scroll properly, only display if logged in.

Cookie notice fixes

---

src/app/components/shell/header/header.scss
src/app/components/shell/header/main-menu/main-menu.html
src/app/components/shell/header/main-menu/main-menu.scss
src/app/components/shell/header/upper-menu/upper-menu.scss

Restore hamburger-to-x animation
Fix size and positioning of logo
Whack-a-mole all the things that messes up

Fix mobile menu styling

---

src/app/components/get-this-title/get-this-title.html
src/app/components/get-this-title/get-this-title.js

If the general page `study-edge` is published, the link will show. If it is not published, it will not show.

Control display of Study Edge link

---

src/app/pages/separatemap/testimonial-form/testimonial-form.js

left off `this.` on references to `hideDialog`

Hide modal after testimonial is submitted

---

src/app/pages/general/general.js
src/app/pages/general/general.scss

Just a few rules to keep things reasonably constrained.

Style general pages

---

src/app/pages/rover-by-openstax/rover-by-openstax.js

Missed fixing a call after changing ModalContent params

Fix Rover popup problem

---

src/app/pages/blog/blog.js
src/app/pages/blog/search-bar/search-bar.scss
src/app/pages/blog/search-results/search-results.scss

Turn on features that were already written

Enable blog search

---

src/app/pages/details/details.scss
src/app/pages/details/phone-view/phone-view.scss

Revert banner gradients
Ensure that banner text-images are left-aligned
Add border-radius to get this title div

Fix book banners

---

src/app/pages/blog/blog.js
src/app/pages/blog/more-stories/more-stories.html
src/app/pages/blog/more-stories/more-stories.js
src/app/pages/blog/search-results/search-results.js

But keep at top of search results

Move search bar into More Stories section

---

src/app/pages/blog/blog.js

Forgot to hook it up. :flushed:

Enable search on search results page

---

src/app/components/get-this-title/get-this-title.html
src/app/components/get-this-title/get-this-title.js
test/src/components/get-this-title.test.js

Put less-preferred book formats in expandable menu

---

src/app/components/get-this-title/get-this-title.html
src/app/components/get-this-title/get-this-title.scss
src/app/pages/details/details.scss

Final banner gradients

---

src/app/components/dialog/dialog.html
src/app/components/dialog/dialog.js
src/app/components/dialog/dialog.scss
src/app/components/get-this-title/get-this-title.js
src/app/components/get-this-title/get-this-title.scss
src/app/components/get-this-title/study-edge/study-edge.scss
src/app/components/shell/cookie-notice/cookie-notice.js
src/app/components/shell/cookie-notice/cookie-notice.scss
src/app/components/shell/header/main-menu/main-menu.scss

(Firefox issue) OpenStax logo and quote layout fix
App store dialog button layout fix and background image adjustment
Cookie notice dialog layout fix
Layout fixes on Get this book menu

Fix header logo and quote layout, other UX fixes

---

src/app/components/get-this-title/get-this-title.html
src/app/components/get-this-title/get-this-title.js
test/src/components/get-this-title.test.js

Handle singular/plural
Add control to revert to hidden

UX fixes for "see additional formats"

---

src/app/components/get-this-title/study-edge/study-edge.scss
src/app/pages/rover-3/banner/banner.scss
src/app/pages/rover-3/popup/popup.scss
src/app/pages/rover-3/rover-3.js

Includes final Study Edge fixup.

Fix rover gradient and logo

---

src/app/components/get-this-title/get-this-title.js
test/src/components/get-this-title.test.js

Use enable_study_edge flag from book details

Control display of study edge per book

---

.travis.yml
src/app/pages/blog/blog.js
src/app/pages/blog/more-stories/more-stories.js
src/app/pages/blog/search-bar/search-bar.html
src/app/pages/blog/search-bar/search-bar.js
src/app/pages/blog/search-bar/search-bar.scss
src/app/pages/blog/search-results/search-results.js
test/src/pages/blog/search-bar.test.js

Add button to clear search
Keep search term in box when showing search results
When no results are found, display "No matching results were found."

Blog search bar and search results fixes

---

package.json
src/app/helpers/data.js
src/app/pages/blog/article-summary/article-summary.html
src/app/pages/blog/article-summary/article-summary.js
src/app/pages/blog/article-summary/article-summary.scss
src/app/pages/blog/article/article.html
src/app/pages/blog/article/article.js
src/app/pages/blog/article/article.scss
src/app/pages/blog/blog.js
src/app/pages/blog/byline/byline.html
src/app/pages/blog/byline/byline.js
src/app/pages/blog/byline/byline.scss
src/app/pages/blog/more-stories/more-stories.js
src/app/pages/blog/search-bar/search-bar.html
src/app/pages/blog/search-bar/search-bar.js
src/app/pages/details/phone-view/instructor-resources-pane/instructor-resources-pane.js
src/robots.txt
test/src/pages/blog/search-bar.test.js

Remove "Read more great stories"
Fix byline date format in summary and article
Decode search string when loading from URL bar

Fix blog search

---

src/app/components/get-this-title/get-this-title.html
src/app/components/shell/cookie-notice/cookie-notice.html
test/src/components/get-this-title.test.js

Per instructions from Victoria

Remove "see fewer options" from Get this Book

---

src/app/pages/details/resource-box/resource-box.js
test/src/pages/details/resource-box.test.js

Updated status check and associated tests

Allow instructors to view locked student resources

---

src/app/helpers/$.js
src/app/pages/general/general.js

I had done this for general pages, but not for elsewhere. Turns out we might want it everywhere.

Make scripts work in inserted HTML

---

src/app/pages/rover-3/banner/banner.scss
src/app/pages/rover-3/navigator/navigator.scss

Constrain video width
Fix "On this page" layout

Rover mobile page UX fixes

---

src/app/components/get-this-title/get-this-title.html

This will also be added to the 28 Aug release

Move "Download the app" link to just below "View online" link

---

src/app/components/shell/cookie-notice/cookie-notice.js
src/app/components/shell/shell.js
src/app/models/usermodel.js

Instead of is_gdpr_location, it is is_not_gdpr_location

Change gdpr flag name

---

src/app/components/get-this-title/get-this-title.html
src/app/helpers/link.js
src/app/pages/details/details.js
src/app/pages/openstax-tutor/openstax-tutor.js
src/app/router.js

Recognize /books as an external link
View online opens in current window

Fix REX links
