openstax/os-webview

- src/app/components/shell/cookie-notice/cookie-notice.js
- src/app/helpers/analytics.js
- src/app/helpers/link.js
- src/app/router.js
Also update cookie path per request from JP
> Analytics track toc clicks

- src/app/components/shell/header/main-menu/dropdown/dropdown.js
- src/app/components/shell/header/main-menu/main-menu.html
- src/app/components/shell/header/main-menu/main-menu.js
Was being created anew on each update. Oops.
> Fix logout menu for mobile

- package.json
- test/src/data/errata-resources.js
> Remove Concept Coach as a source for errata

- src/app/pages/rover-by-openstax/rover-by-openstax.js
> Set "Sign up" link on Rover page

- src/app/components/shell/adoption-dialog/adoption-dialog.html
- src/app/components/shell/adoption-dialog/adoption-dialog.js
- src/app/components/shell/adoption-dialog/adoption-dialog.scss
- src/app/components/shell/header/main-menu/dropdown/dropdown.html
- src/app/components/shell/header/main-menu/main-menu.js
- src/app/pages/rover-by-openstax/getting-started/getting-started.scss
Addresses #627, #628, #629, #632, #633
> Fixes for rc 2.41.0

- src/app/helpers/analytics.js
- src/app/helpers/link.js
- test/src/helpers/link.test.js
Was missing parentheses :flushed:
> Fix external link test

- src/app/components/shell/cookie-notice/cookie-notice.js
> Set cookie even if not acknowledged

- src/app/pages/general/general.scss
> Add padding to general page and constrain content better

- src/app/pages/details/details.js
Remove dynamic styling when drawer is closed.
> Fix jitter caused by closed TOC drawer

- src/app/pages/separatemap/search-box/search-box.js
- src/app/pages/separatemap/testimonial-form/testimonial-form.html
- src/app/pages/separatemap/testimonial-form/testimonial-form.scss
Also fix flipped savings totals
> Force user to select a book for testimonial form

- src/app/components/a-component-template/a-component-template.js
- src/app/components/get-this-title/callout-counter.js
- src/app/components/get-this-title/get-this-title.html
- src/app/components/get-this-title/get-this-title.js
- src/app/components/get-this-title/get-this-title.scss
- src/app/components/get-this-title/recommended-callout/recommended-callout.html
- src/app/components/get-this-title/recommended-callout/recommended-callout.js
- src/app/components/get-this-title/recommended-callout/recommended-callout.scss
- src/app/components/shell/header/main-menu/main-menu.scss
- test/src/components/get-this-title/callout-counter.test.js
- test/src/components/get-this-title/get-this-title.test.js
- test/src/components/get-this-title/recommended-callout.test.js
> Implement callout on View Online for REX titles

- src/app/pages/separatemap/separatemap.js
- src/app/pages/separatemap/testimonial-form/testimonial-form.js
- test/src/pages/separatemap/testimonial-form.test.js
Each time it is brought up, generate a new form that cleans itself up.
> Allow user to submit more than one testimonial

- src/app/components/shell/header/header.js
- src/app/components/shell/header/main-menu/dropdown/dropdown.js
- src/app/components/shell/header/main-menu/login-menu/login-menu.html
- src/app/components/shell/header/main-menu/login-menu/login-menu.js
- src/app/components/shell/header/main-menu/main-menu.html
- src/app/components/shell/header/main-menu/main-menu.js
- src/app/helpers/link.js
- src/app/models/usermodel-bus.js
- src/app/models/usermodel.js
- src/app/pages/errata-form/errata-form.js
- test/setupFile.js
- test/src/components/adoption-dialog.test.js
- test/src/components/book-selector.test.js
- test/src/components/header.test.js
- test/src/components/role-selector.test.js
- test/src/components/shell/login-menu.test.js
- test/src/components/shell/main-menu.test.js
- test/src/components/technology-selector.test.js
Started out as just a fix to the loginLink, but decided that the login menu needed to be factored out of the main menu code.
Did not break mobile menu!
> Refactor login menu

- src/app/helpers/analytics.js
- src/index.html
Fixes: business-intel#654
Also fix #1561
> Add Google Optimize

- src/app/pages/details/comp-copy-dialog-props.js
- src/app/pages/faq/faq.js
Nothing should be importing shell. Fixed FAQ for that, too.
> Fix comp copy dialog error

- src/app/pages/details/table-of-contents/table-of-contents.js
> Fix variable name

- src/app/components/shell/adoption-dialog/adoption-dialog.html
> Change lead source to Renewal Popup

- src/app/pages/rover-by-openstax/banner/banner.html
- src/app/pages/rover-by-openstax/faq/faq.html
- src/app/pages/rover-by-openstax/meet-rover/meet-rover.html
- src/app/pages/rover-by-openstax/navigator/navigator.html
- src/app/pages/rover-by-openstax/rover-by-openstax.js
Fixes #355
I ran a Lighthouse audit for the page and addressed the issues it found.
> Improve accessibility on Rover page

- src/app/components/get-this-title/recommended-callout/recommended-callout.scss
> UX fixes for "View Online" callout

- src/app/components/paginator/paginator.js
- test/src/components/paginator.test.js
Instead of showing first and last page numbers, just show those around the current page.
Per instructions from Victoria
> Change paginator

- src/index.html
> Add Facebook pixel code

- src/app/components/shell/header/main-menu/main-menu.js
- src/app/components/shell/shell.js
- src/app/helpers/$.js
- src/app/pages/creator-fest/about/about.html
- src/app/pages/creator-fest/about/about.js
- src/app/pages/creator-fest/about/about.scss
- src/app/pages/creator-fest/banner/banner.html
- src/app/pages/creator-fest/banner/banner.js
- src/app/pages/creator-fest/banner/banner.scss
- src/app/pages/creator-fest/creator-fest.js
- src/app/pages/creator-fest/creator-fest.scss
- src/app/pages/creator-fest/shared.scss
- src/app/pages/creator-fest/why/why.html
- src/app/pages/creator-fest/why/why.js
- src/app/pages/creator-fest/why/why.scss
- src/app/router.js
> Creator fest page

- src/app/components/get-this-title/get-this-title.js
- src/app/pages/details/details-tab/details-tab.js
- src/app/pages/details/details.js
- src/app/pages/details/phone-view/phone-view.js
- test/src/components/get-this-title/get-this-title.test.js
Removed uses of table_of_contents data item
> Stop relying on table_of_contents from CMS

- package.json
- src/app/pages/details/instructor-resource-tab/instructor-resource-tab.js
- src/app/pages/details/phone-view/instructor-resources-pane/instructor-resources-pane.js
- src/app/pages/details/phone-view/student-resources-pane/student-resources-pane.js
- src/app/pages/details/resource-box/resource-box.js
- src/app/pages/details/resource-box/resource-box.scss
- src/app/pages/details/student-resource-tab/student-resource-tab.js
> Add "Coming Soon" to resources

- src/app/models/table-of-contents-html.js
- src/app/pages/details/details-tab/details-tab.js
- src/app/pages/details/phone-view/phone-view.js
> Change REX links in ToC to use current host

- src/app/pages/blog/article-summary/article-summary.js
- src/app/pages/blog/more-stories/more-stories.js
- src/app/pages/blog/search-results/search-results.js
Issue #578
Search results are paginated, so there's no large cost to loading all the thumbnails. Continue to delay loading thumbnails in the More Stories (which is not paginated).
> Load blog search result images immediately

- src/app/helpers/controller/cms-mixin.js
- src/app/pages/blog/article/article.js
> Use title and description in blog articles

- src/app/pages/creator-fest/creator-fest.scss
- src/app/pages/creator-fest/fetched-content/fetched-content.scss
- src/app/pages/creator-fest/home-content/about/about.scss
- src/app/pages/creator-fest/shared.scss
> Creator Fest page UX style updates

- src/app/pages/bookstore-suppliers/bookstore-suppliers.html
- src/app/pages/bookstore-suppliers/bookstore-suppliers.js
- src/app/pages/bookstore-suppliers/bookstore-suppliers.scss
- test/src/data/print-order.js
- test/src/pages/bookstore-suppliers.test.js
> Add button for Canada ISBN list

- src/app/helpers/errata.js
- src/app/pages/errata-detail/errata-detail.js
- src/app/pages/errata-detail/progress-bar/progress-bar.js
- src/app/pages/errata-summary/errata-summary.js
> Adjust errata decision wording

- src/app/components/paginator/paginator.js
> Blur focus on paginator number buttons when page changes

- src/app/components/shell/header/main-menu/login-menu/login-menu.js
- src/app/pages/creator-fest/fetched-content/fetched-content.scss
When lines wrapped, the connector lines didn't connect.
> Fix progress bars on CreatorFest Schedule

- src/app/pages/details/resource-box/resource-box.scss
> Move "coming soon" label to bottom of resource box

- src/app/pages/blog/blog.js
- src/app/pages/blog/search-bar/search-bar.js
- src/app/pages/blog/search-results/search-results.js
> Track blog search terms in Google Analytics

- src/app/pages/home/banner-carousel/banner-carousel.scss
> Align and justify arrows to be centered in their dots

- src/app/helpers/controller/init-mixin.js
- src/app/pages/adoption-confirmation/supplemental-form.js
- src/app/pages/adoption/how-using/how-using.js
- src/app/pages/bookstore-suppliers/bookstore-suppliers.js
- src/app/pages/faq/faq.js
- src/app/pages/hero-journey/numbered-navigator/numbered-navigator.js
- src/app/pages/hero-journey/sections/books/books.js
- src/app/pages/hero-journey/sections/thanks/thanks.js
- src/app/pages/press/bookings/booking/booking.js
- src/app/pages/research/research.js
- src/app/pages/team/people-tab/people-tab.js
Single page apps have to tell Optimize when the page has updated.
see https://support.google.com/optimize/answer/7008840
Issue #739
> Fix A/B testing in Google Optimize

- src/app/pages/errata-detail/detail/detail.html
> Display errata decision details as HTML

- src/app/models/usermodel.js
- src/index.html
Issue #740
`no_faculty_info` is the status you get before `pending`.
> Recognize pending accounts for locked resources

- src/app/components/shell/header/main-menu/login-menu/login-menu.html
- src/app/pages/details/resource-box/resource-box.js
- test/src/components/shell/login-menu.test.js
- test/src/pages/details/resource-box.test.js
- test/src/pages/details/student-resources-pane.test.js
Also some refactoring to DRY up some code
> Change "Login" to "Log in"

- src/app/models/querySchools.js
> Filter out schools with no cumulative savings

- src/app/components/shell/header/header.js
- src/app/pages/creator-fest/home-content/why/why.js
> Show sticky on initial page load

- src/app/components/get-this-title/callout-counter.js
- test/src/components/get-this-title/callout-counter.test.js
> Reset recommended callout after Jan 15 2020

- src/app/helpers/analytics.js
- src/app/pages/details/details.js
Issue #604
This gets rid of a very slow query. It also takes care of a problem in which  the wrong book was being associated with click actions.
> Load resources to Analytics table from book details page

- src/app/components/progress-ring/progress-ring.html
- src/app/components/progress-ring/progress-ring.js
- src/app/components/progress-ring/progress-ring.scss
- src/app/components/share/share.html
- src/app/components/share/share.js
- src/app/components/share/share.scss
- src/app/components/shell/shell.js
- src/app/helpers/throttle.js
- src/app/pages/adoption-confirmation/adoption-confirmation.js
- src/app/pages/blog/article/article.html
- src/app/pages/blog/article/article.js
- src/app/pages/blog/article/article.scss
> Improve individual blog page layout

- src/app/components/shell/cookie-notice/cookie-notice.js
> Use UUID for Analytics ID

- src/app/pages/rover-by-openstax/rover-by-openstax.js
> Use "Office Hours" info from CMS on Rover page

- src/app/pages/partner-marketplace/controls/controls.js
- src/app/pages/partner-marketplace/partner-marketplace.html
- src/app/pages/partner-marketplace/partner-marketplace.js
- src/app/pages/partner-marketplace/results/results.html
- src/app/pages/partner-marketplace/results/results.scss
Issue #669
Rating and cost tags are hidden since we have no data
Sort selector is hidden because there is no spec for how it should work
> Handle partner filter categories

- src/app/helpers/store.js
- src/app/pages/partner-marketplace/active-filters/active-filters.js
- src/app/pages/partner-marketplace/controls/controls.js
- src/app/pages/partner-marketplace/controls/options-list/options-list.js
- src/app/pages/partner-marketplace/partner-marketplace.js
- src/app/pages/partner-marketplace/results/results.js
- src/app/pages/partner-marketplace/store.js
> Implement filtering and sorting on new partner landing page

- src/app/helpers/store.js
- src/app/pages/partner-marketplace/analytics-events.js
- src/app/pages/partner-marketplace/partner-details/partner-details.html
- src/app/pages/partner-marketplace/partner-details/partner-details.js
- src/app/pages/partner-marketplace/partner-details/partner-details.scss
- src/app/pages/partner-marketplace/partner-marketplace.js
- src/app/pages/partner-marketplace/results/result/result.html
- src/app/pages/partner-marketplace/results/result/result.js
- src/app/pages/partner-marketplace/results/results.html
- src/app/pages/partner-marketplace/results/results.js
> Track partner marketplace filter usage in Google Analytics

- src/app/helpers/store.js
- src/app/pages/partner-marketplace/analytics-events.js
`notify`event needs to include an object payload
Types became a single-value selection
Issue #671
> Fix Marketplace events

- src/app/pages/details/details.js
- src/app/pages/details/details.scss
- src/app/pages/details/instructor-resource-tab/instructor-resource-tab.js
- src/app/pages/details/instructor-resource-tab/instructor-resource-tab.scss
- src/app/pages/details/instructor-resource-tab/partners/partners.html
- src/app/pages/details/instructor-resource-tab/partners/partners.js
- src/app/pages/details/instructor-resource-tab/partners/partners.scss
- src/app/pages/partner-marketplace/partner-marketplace.js
- src/app/pages/partner-marketplace/results/results.scss
> UX fixes for partner display section of book details page

- src/app/models/table-of-contents-html.js
- src/app/pages/creator-fest/creator-fest.scss
- src/app/pages/creator-fest/fetched-content/fetched-content.scss
- src/app/pages/creator-fest/home-content/about/about.scss
- src/app/pages/creator-fest/shared.scss
> Adjust spacing on top of creator fest page contents

- src/app/helpers/errata.js
- test/src/helpers/errata.test.js
> Fix errata corrected messaging

- src/app/helpers/controller/init-mixin.js
- src/app/models/querySchools.js
- src/app/pages/partner-marketplace/controls/controls.js
- src/app/pages/partner-marketplace/results/results.js
- src/app/pages/separatemap/search-box/search-box.js
- test/src/pages/separatemap/search-box.test.js
> Add message to map for too many matches

- src/app/pages/creator-fest/creator-fest.scss
- src/app/pages/creator-fest/fetched-content/fetched-content.js
- src/app/pages/creator-fest/fetched-content/fetched-content.scss
- src/app/pages/creator-fest/fetched-content/signup/form/form.html
- src/app/pages/creator-fest/fetched-content/signup/form/form.js
- src/app/pages/creator-fest/fetched-content/signup/form/form.scss
- src/app/pages/creator-fest/fetched-content/signup/signup.html
- src/app/pages/creator-fest/fetched-content/signup/signup.js
- src/app/pages/creator-fest/fetched-content/signup/signup.scss
- src/app/pages/creator-fest/navigator/navigator.scss
- src/app/pages/creator-fest/shared.scss
> Implement Session list and signup form

- src/app/pages/partners/controls/controls.js
- src/app/pages/partners/controls/controls.scss
- src/app/pages/partners/partner-details/carousel/carousel.html
- src/app/pages/partners/partner-details/carousel/carousel.js
- src/app/pages/partners/partner-details/carousel/carousel.scss
- src/app/pages/partners/partner-details/partner-details.scss
- src/app/pages/partners/results/results.js
- src/app/pages/partners/store.js
Issue #836 again
Also removes the Grid/List toggle, since List is pointless (we removed the description from it, so it has the same info as Grid, but takes more room).
> More UX fixes for Partners

- src/app/components/get-this-title/get-this-title.js
- src/app/components/get-this-title/order-print-copy/order-print-copy.html
> Remove price and seller line from print popup

- src/app/pages/rover-by-openstax/navigator/navigator.scss
- src/app/pages/rover-by-openstax/rover-by-openstax.js
Issue #831
Also made the navigator layout a little nicer.
> Make two sections optional on Rover page

- src/app/pages/separatemap/search-box/search-box.js
- src/app/pages/separatemap/separatemap.js
- src/app/pages/separatemap/separatemap.scss
> Track Map queries and clicks in Google Analytics

- src/app/pages/partners/controls/button-with-popover/button-with-popover.js
- src/app/pages/partners/partner-details/carousel/carousel.scss
- src/app/pages/partners/partner-details/partner-details.html
- src/app/pages/partners/partner-details/partner-details.scss
> UX fixes for partners lightbox

- src/app/pages/webinars/webinar-list/webinar-list.html
- src/app/pages/webinars/webinar-list/webinar-list.js
- src/app/pages/webinars/webinar-list/webinar-list.scss
- src/app/pages/webinars/webinars.html
- src/app/pages/webinars/webinars.js
- src/app/pages/webinars/webinars.scss
- src/app/router.js
#800
This PR does the layout to get a head start on UX review.
There will be another PR that ties it to CMS data and gets it ready for functional verification.
> Layout done; need CMS data

- src/app/pages/partners/partner-details/partner-details.scss
- src/app/pages/webinars/webinars.js
- src/app/pages/webinars/webinars.scss
> Use Webinar data from CMS

- src/app/pages/adoption-confirmation/supplemental-form.js
- src/app/pages/adoption/adoption.js
- src/app/pages/interest/interest.js
> Remove Partner categories question from adoption and interest forms

- src/app/components/shell/header/main-menu/main-menu.js
- src/app/pages/confirmation/confirmation.js
- src/app/pages/details/details.js
- src/app/pages/details/instructor-resource-tab/partners/partners.js
- src/app/pages/partners/partner-details/carousel/carousel.scss
- src/app/pages/partners/partner-details/partner-details.scss
- src/app/pages/partners/partners.js
- src/app/pages/webinars/webinar-list/webinar-list.html
- src/app/pages/webinars/webinar-list/webinar-list.js
- src/app/pages/webinars/webinar-list/webinar-list.scss
- src/app/pages/webinars/webinars.scss
> UX fixes for marketplace and webinars pages

- src/app/components/get-this-title/get-this-title.js
> Fix Order Print Copy for single entry in bookstore_content

- src/app/pages/rover-by-openstax/rover-by-openstax.js
> Use CMS text for Rover page "see more resources" button

- src/app/pages/details/details.js
- src/app/pages/details/instructor-resource-tab/instructor-resource-tab.js
- src/app/pages/details/instructor-resource-tab/partners/partners.html
- src/app/pages/details/instructor-resource-tab/partners/partners.js
- src/app/pages/partners/controls/controls.js
- src/app/pages/partners/mobile-filters/mobile-filters.js
- src/app/pages/partners/partners.js
- src/app/pages/webinars/webinar-list/webinar-list.scss
- src/app/pages/webinars/webinars.scss
Also includes several UX fixes
> Pull Partner Type options from CMS

- src/app/pages/details/instructor-resource-tab/partners/partners.scss
- src/app/pages/partners/results/results.scss
- src/styles/mixins/placeholder-selectors.scss
so the tooltip is over the neighbor's badge
#1664
> Move card to front on hover

- src/app/models/salesforce-partners.js
- src/app/pages/details/instructor-resource-tab/partners/partners.js
- src/app/pages/partners/partner-details/partner-details.html
- src/app/pages/partners/partners.js
- src/app/pages/partners/results/result/result.html
- src/styles/mixins/placeholder-selectors.scss
> Get partner verified status from CMS

- src/app/pages/partners/partner-details/partner-details.html
- src/app/pages/partners/partner-details/partner-details.scss
> Modify Tech Scout lightbox design

- src/styles/mixins/placeholder-selectors.scss
It was drawing behind the carousel
> Bring tooltip to the front

- src/app/pages/quiz-results/persona/persona.html
- src/app/pages/quiz-results/persona/persona.js
- src/app/pages/quiz-results/persona/persona.scss
- src/app/pages/quiz-results/quiz-results.html
- src/app/pages/quiz-results/quiz-results.js
- src/app/pages/quiz-results/quiz-results.scss
- src/app/router.js
> Implement quiz landing page

- gulp/tasks/jsx.js
- gulpfile.js
- package.json
- src/app/pages/a-page-template/a-page-template.js
- src/app/pages/a-page-template/a-page-template.scss
- src/app/pages/a-page-template/a-thing.jsx
- yarn.lock
Issue #1688
No one is more surprised than I am that I got this to work in a relatively short time.
> Add JSX compilation to build process

- src/app/pages/partners/partner-details/partner-details.html
- src/app/pages/partners/partner-details/partner-details.js
- src/app/pages/partners/partners.js
> Make Partner lightbox links editable

- src/app/components/shell/sticky-note/sticky-note.js
> Display emergency sticky note on every session

- src/app/pages/errata-detail/detail/detail.js
- src/app/pages/errata-detail/progress-bar/progress-bar.html
- src/app/pages/errata-detail/progress-bar/progress-bar.js
- test/src/pages/errata/errata-detail.test.js
> Change Errata Details details

- src/app/components/form-select/form-select.js
- src/app/pages/errata-form/form/ErrorLocationSelector/ErrorLocationSelector.jsx
- src/app/pages/errata-form/form/ErrorLocationSelector/ErrorLocationSelector.scss
- src/app/pages/errata-form/form/FileUploader.jsx
- src/app/pages/errata-form/form/form.jsx
- src/app/pages/errata-form/form/form.scss
- test/src/pages/errata/__snapshots__/errata-form.test.jsx.snap
Issue #899
Set width to 100%
Change label
Change checkbox to yes/no radios
Add expand/collapse indicators to options
Hide 2nd button when both are empty
> Errata source UX fixes

- src/app/helpers/$.js
- src/app/models/books.js
- src/app/pages/partners/partners.html
- src/app/pages/partners/partners.js
> Route all mobile confirmations to Tech Scout page

- src/app/components/book-selector/book-selector.js
- src/app/helpers/controller/init-mixin.js
Instances were sharing data items.
> Reset selected books when revisiting forms

- gulp/tasks/scripts.js
- package.json
- src/app/components/a-component-template/a-component-template.html
- src/app/components/a-component-template/a-component-template.js
- src/app/components/a-component-template/a-component-template.jsx
- src/app/components/a-component-template/a-component-template.scss
- src/app/controllers/jsx-wrapper.js
- src/app/models/cmsFetch.js
- src/app/pages/a-page-template/a-page-template.html
- src/app/pages/a-page-template/a-page-template.js
- src/app/pages/a-page-template/a-page-template.jsx
- src/app/pages/a-page-template/a-page-template.scss
- src/app/pages/a-page-template/a-thing.jsx
- src/app/pages/errata-form/form/ErrorLocationSelector/ErrorLocationSelector.jsx
- src/app/pages/errata-form/form/ErrorSourceSelector.jsx
- src/app/pages/errata-form/form/ErrorTypeSelector.jsx
- src/app/pages/errata-form/form/FileUploader.jsx
- src/app/pages/errata-form/form/InvalidMessage.jsx
- src/app/pages/errata-form/form/form.jsx
- src/app/pages/partners/results/result-card.jsx
- src/app/pages/partners/results/result-grid.jsx
- yarn.lock
> Update examples to react

- src/app/pages/a-page-template/a-page-template.jsx
- src/app/pages/errata-form/form/ErrorLocationSelector/ErrorLocationSelector.jsx
- src/app/pages/errata-form/form/ErrorSourceSelector.jsx
- src/app/pages/errata-form/form/ErrorTypeSelector.jsx
- src/app/pages/errata-form/form/FileUploader.jsx
- src/app/pages/errata-form/form/form.jsx
- src/app/pages/footer-page/footer-page.html
- src/app/pages/footer-page/footer-page.js
- src/app/pages/footer-page/footer-page.jsx
- src/app/pages/partners/results/results.js
- src/app/pages/quiz-results/quiz-results.js
> Port footer pages to React

- src/app/pages/details/details.scss
> Handle gold cover color scheme

- src/app/components/shell/header/main-menu/main-menu.scss
> Fix mobile menu: menu items obscured by logo-wrapper

- src/app/pages/errata-form/form/ErrorLocationSelector/ErrorLocationSelector.jsx
Brackets looked too crowded.
Issue #899
> Errata location selector redesign and fixes

- src/app/pages/errata-form/form/ErrorLocationSelector/ErrorLocationSelector.jsx
> Fix ToC toggles

- src/app/pages/webinars/webinars.js
> Order webinars by date

- src/app/models/books.js
- src/app/pages/subjects/subjects.js
> Handle deprecated and retired books

- src/app/models/rex-release.js
- src/app/models/table-of-contents-html.js
lodash memoize only keys by the first parameter!
Issue #1023
> Fix: ToC for Rex books doesn't change

- src/app/pages/details/details.js
- src/app/pages/details/instructor-resource-tab/instructor-resource-tab.js
- src/app/pages/details/phone-view/instructor-resources-pane/instructor-resources-pane.html
- src/app/pages/details/phone-view/instructor-resources-pane/instructor-resources-pane.js
- src/app/pages/details/phone-view/phone-view.js
- test/src/pages/details/instructor-resources-pane.test.js
- test/src/pages/details/phone-view.test.js
> Fix highlighted resources section on mobile

- src/app/pages/details/instructor-resource-tab/instructor-resource-tab.js
- src/app/pages/details/instructor-resource-tab/partners/partners.js
> Hide tech partners list if book has no partners

- src/app/pages/404/404.html
- src/app/pages/404/404.js
- src/app/router.js
Issue #1000
Rerouting to /error/404 now. This may not generate the actual 404 response, but it's less jarring than the /books/404/pages/404 hack. And maybe we can tell cloudfront or something to issue a 404 response to /error/404 addresses.
> Render 404 page again

- gulp/tasks/webpack.js
- package.json
- src/app/pages/errata-form/form/ErrorLocationSelector/ErrorLocationSelector.jsx
- test/helpers/jsx-test-utils.jsx
- yarn.lock
Preact is smaller and faster than React. This is a build system optimization. No user-side changes.
> Switch to Preact

- src/app/pages/details/details-tab/callout.jsx
- src/app/pages/details/details-tab/details-tab.html
- src/app/pages/details/details-tab/details-tab.js
- src/app/pages/details/details-tab/details-tab.scss
- src/app/pages/details/details.js
> Hover text for PDF version last updated

- src/app/pages/details/instructor-resource-tab/instructor-resource-tab.js
- src/app/pages/details/resource-box/resource-boxes.jsx
> Put oer commons hub back

- src/app/components/get-this-title/get-this-title.html
and say Go to OpenStax Tutor instead of View online
Issue #881
> Tutor books get Atom icon instead of Laptop

- src/app/pages/details/details-tab/publication-info.jsx
> Show hardcover and paperback ISBNs

- src/app/helpers/$.js
- src/app/pages/partners/partner-details/carousel/carousel.js
> Fix: lightbox navigation button closes lightbox

- src/app/pages/partners/partners.js
> Fix partner details closing issues

- src/app/pages/adoption/adoption.js
- src/app/pages/details/details.js
> Fix book details search string handling

- src/app/pages/confirmation/confirmation.js
> Fix errata confirmation

- src/app/helpers/controller/cms-mixin.js
- src/app/pages/institutional-partnership-application/application.html
- src/app/pages/interest/interest.js
Issue #1114
Also fix issue with the sticky note slug
> Replace Institutional Partnership Application form

- src/app/components/shell/sticky-note/sticky-note.js
- src/app/models/salesforce.js
- src/settings-example.js
- test/helpers/fetch-mocker.js
> Stop showing sticky note after 7 times, rather than 5

- package.json
- src/app/helpers/controller/cms-mixin.js
- src/app/models/book-titles.js
- src/app/models/cmsFetch.js
- src/app/pages/webinars/webinars.js
- test/helpers/fetch-mocker.js
> Webinar page fixes

- src/app/components/shell/adoption-dialog/adoption-dialog.js
- src/app/components/shell/footer/footer.js
- src/app/helpers/$.js
- src/app/helpers/controller/cms-mixin.js
- src/app/models/cmsFetch.js
- src/app/models/usermodel.js
- src/app/pages/adoption/adoption.js
- src/app/pages/creator-fest/creator-fest.js
- src/app/pages/creator-fest/fetched-content/signup/form/form.js
- src/app/pages/errata-form/errata-form.js
- src/app/pages/errata-form/form/form.jsx
- src/app/pages/general/general.js
- src/app/pages/hero-journey/hero-journey.js
- src/app/pages/interest/interest.js
- src/settings-example.js
- test/helpers/fetch-mocker.js
- test/src/pages/home/home.test.js
- test/src/pages/institutional-partnership/institutional-partnership.test.js
Issue #1759
Hopefully this finishes covering all the api/v2-sensitive issues
> Manage non-deployment-dependent settings locally

- src/app/pages/details/details.js
- src/app/pages/details/phone-view/instructor-resources-pane/instructor-resources-pane.js
- src/app/pages/details/phone-view/instructor-resources-pane/instructor-resources-pane.scss
- src/app/pages/details/phone-view/phone-view.js
- src/app/pages/details/resource-box/resource-box.scss
- src/app/pages/details/resource-box/resource-boxes.jsx
> Show OER Commons box on mobile instructor resources

- src/app/pages/home/education/education.html
- src/app/pages/home/education/education.js
- src/app/pages/home/home.js
- src/settings-example.js
> Make button editable in homepage Education section

- src/app/helpers/analytics.js
- src/app/helpers/tag-manager.js
> Add Google Tag Manager back

- src/app/models/books.js
> Include books with new edition forthcoming in Salesforce book list

- src/app/components/shell/cookie-notice/cookie-notice.js
- src/app/helpers/analytics.js
- src/index.html
> Handle cookie consent

- src/app/helpers/$.js
- src/app/models/salesforce.js
> Fix testing environment test to include staging

- src/app/pages/details/common/errata.jsx
> Hide errata links for deprecated books

- src/app/components/shell/header/main-menu/login-menu/login-menu.js
> Fix login menu when user logs out in another window

- src/app/pages/bookstore-suppliers/bookstore-suppliers.js
Issue #1199
**Important:**
Based on branch port-about-and-adoption-pages-to-react
> Hide price lists

- src/app/components/shell/header/main-menu/dropdown/dropdown.scss
- src/app/components/shell/header/main-menu/main-menu.scss
> Fix main menu layout

- src/app/pages/home/quotes/quotes.scss
> Fix quote bucket layout on mobile

- src/app/helpers/analytics.js
- src/app/pages/details/instructor-resource-tab/instructor-resource-tab.jsx
- src/app/router.js
> Update Google Events naming for Instructor Resources

- src/app/pages/partners/analytics-events.js
- src/app/pages/partners/partner-details/partner-details.js
> Report tech scout scrolling to Google Analytics

- src/app/pages/interest/hidden-fields/hidden-fields.html
A commit from previous release that didn't get added back to master.
> Change adoption status field name on Interest form

- src/app/models/usermodel.js
> Indicate logged-in instructors in GTM dataLayer

- src/app/components/get-this-title/get-this-title.html
- src/app/components/get-this-title/get-this-title.js
- src/app/components/get-this-title/order-print-copy/order-print-copy.jsx
- src/app/pages/details/details.js
- src/app/pages/details/instructor-resource-tab/instructor-resource-tab.jsx
- src/app/pages/details/phone-view/instructor-resources-pane/instructor-resources-pane.jsx
- src/app/pages/details/phone-view/phone-view.js
- src/app/pages/details/resource-box/resource-boxes.jsx
- src/app/router.js
- test/src/pages/details/instructor-resources-pane.test.js
> Track instructor resource downloads in salesforce

- src/app/components/dialog/dialog.html
- src/app/components/dialog/dialog.scss
- src/app/pages/details/details.scss
- src/app/pages/details/resource-box/resource-box.scss
- src/app/pages/details/resource-box/resource-boxes.jsx
> Video resources fixes

- src/app/components/dialog/dialog.scss
- src/app/pages/details/instructor-resource-tab/instructor-resource-tab.scss
- src/app/pages/details/phone-view/instructor-resources-pane/instructor-resources-pane.scss
- src/app/pages/details/resource-box/resource-box.scss
> Instructor Resources UX fixes round 2

- src/app/pages/home/banner-carousel/banner-carousel.scss
- src/app/pages/home/buckets/buckets.scss
- src/app/pages/home/education/education.scss
- src/app/pages/home/quotes/quotes.jsx
- src/app/pages/home/quotes/quotes.scss
- src/styles/components/buttons.scss
- src/styles/components/social.scss
> Restyle homepage buttons: UX review fixes

- src/app/pages/adoption/adoption.js
- src/app/pages/interest/interest.js
- src/app/pages/openstax-tutor/openstax-tutor.js
- src/app/router.js
> Track link clicks in Pardot

- src/app/pages/adoption/adoption.js
- src/app/pages/adoption/adoption.scss
> Add print partner contact question to adoption form

- package.json
- src/app/helpers/$.js
- src/app/helpers/errata.js
- src/app/pages/details/details.js
- src/app/pages/details/phone-view/instructor-resources-pane/instructor-resources-pane.jsx
- src/app/pages/subjects/book-viewer/book.js
- src/app/pages/webinars/webinars.js
Release candidate fixes need to be merged into master/main branch
> Fixes from Rc 2.63.1

- src/app/components/shell/header/main-menu/dropdown/dropdown.scss
- src/app/pages/details/instructor-resource-tab/instructor-resource-tab.scss
- src/app/pages/details/student-resource-tab/student-resource-tab.scss
> Fix resource and menu formatting

- src/app/components/shell/header/main-menu/login-menu/login-menu.js
- src/app/models/usermodel.js
**All** users, including previously rejected users, should have a way to get faculty access by clicking on a link which shows up in the login-menu. The link will say "Finish signing up" if faculty users have not even finished signing up (and therefore have not finished applying for faculty access) or "Request instructor access" for everyone else.
> Give all users the ability to request faculty access

- src/app/helpers/font-awesome.js
- src/app/pages/details/details.js
- src/app/pages/details/phone-view/phone-view.js
- src/app/pages/details/phone-view/phone-view.scss
- src/app/pages/details/tab-group-with-link/tab-group-with-link.js
- src/app/pages/details/tab-group-with-link/tab-group-with-link.scss
Issue #1357
This is just one part of the solution.
Other parts are waiting for more SF integration.
> Add give link to book details page

- src/app/components/shell/lower-sticky-note/lower-sticky-note.js
- src/app/components/shell/microsurvey-popup/sticky-content.js
- src/app/helpers/$.js
> Create GA events for microdonations

- src/app/components/accordion-group/accordion-group.jsx
- src/app/pages/details/phone-view/phone-view.js
> Pre-expand resource accordion items based on URL

- src/app/components/section-navigator/section-navigator.html
- src/app/components/section-navigator/section-navigator.js
- src/app/helpers/$.js
- src/app/pages/openstax-tutor/faq.js
- src/app/pages/openstax-tutor/features.js
- src/app/pages/openstax-tutor/frontier.js
- src/app/pages/openstax-tutor/how-it-works.js
- src/app/pages/openstax-tutor/learn-more.js
- src/app/pages/openstax-tutor/openstax-tutor.js
- src/app/pages/openstax-tutor/pulsing-dot/pulsing-dot.html
- src/app/pages/openstax-tutor/pulsing-dot/pulsing-dot.js
- src/app/pages/openstax-tutor/science.js
- src/app/pages/openstax-tutor/what-students-get.js
- src/app/pages/openstax-tutor/where-money-goes.js
- test/src/pages/openstax-tutor/openstax-tutor.test.js
- test/src/pages/openstax-tutor/pulsing-dot.test.js
> Port Tutor page to React

- src/app/components/shell/header/main-menu/login-menu/login-menu.js
To continue moving through the release process [issue 1320](https://github.com/openstax/business-intel/issues/1320) for Accounts
> Uncomment Request instructor access link

- src/app/helpers/$.js
It turns out I was generally testing title rather than slug, so I had to add a test for psychologia
> Identify psychologia as a Polish book

- src/app/components/accordion-group/accordion-group.jsx
- src/app/components/jsx-helpers/jsx-helpers.jsx
- src/app/pages/details/desktop-view/videos-tab/videos-tab.js
One thing I missed in the Details page port
> Enable scripts in video tab

- src/app/components/multi-page-form/multi-page-form.js
- src/app/helpers/analytics.js
- src/app/models/books.js
- src/app/pages/details/common/resource-box/resource-boxes.js
- src/app/pages/partners/controls/controls.js
- src/app/pages/partners/partners.js
- src/app/pages/partners/results/results.js
> Fix GA tracking of Form submission

- src/app/pages/details/common/resource-box/resource-box.scss
- src/app/pages/details/common/resource-box/resource-boxes.js
> Fix Access pending spacing

- src/app/pages/partners/results/results.js
> Handle multiple cost tags per partner

- package.json
- src/app/pages/details/common/errata.js
- src/app/pages/details/common/get-this-title.js
- src/app/pages/details/desktop-view/desktop-view.js
- src/app/pages/details/desktop-view/instructor-resource-tab/instructor-resource-tab.js
- src/app/pages/subjects/subjects.js
> Make Chegg Reader option visible on college success

- src/app/models/rex-release.js
> Do not try to get version of Tutor-only book (LLPH)

- src/app/components/shell/footer/footer.js
> Add Tutor refund policy to Policies in footer

- src/app/components/shell/header/upper-menu/upper-menu.js
- src/app/pages/details/common/customization-form/customization-form.js
- src/app/pages/details/common/resource-box/resource-boxes.js
- src/app/pages/details/context.js
- src/app/pages/details/details.js
> Use CMS data for Customization Form text

- src/app/components/shell/lower-sticky-note/lower-sticky-note.js
> Fix microdonation banner click tracking

- src/app/models/savings.js
- src/app/pages/subjects/subjects.js
- src/app/pages/subjects/subjects.scss
> Include savings data in About Our Textbooks blurbs

- src/app/components/shell/header/header.js
- src/app/components/shell/header/main-menu/main-menu.js
- src/app/pages/details/common/get-this-title-files/options.js
Issue #1887
This also includes a release candidate fix that didn't get merged to master last time.
> Fix mobile menu opener

- src/app/pages/partners/analytics-events.js
> Report book selections even when no other filters are used

- src/app/pages/details/common/savings-blurb.js
- src/app/pages/details/common/savings-blurb.scss
- src/app/pages/details/desktop-view/details-tab/details-tab.js
- src/app/pages/details/desktop-view/details-tab/details-tab.scss
- src/app/pages/details/phone-view/details-pane/details-pane.js
- src/app/pages/details/phone-view/details-pane/details-pane.scss
> Add savings blurb to book details on mobile

- src/app/components/carousel/carousel.js
- src/app/components/carousel/carousel.scss
- src/app/pages/openstax-tutor/webinars/webinars.js
- src/app/pages/openstax-tutor/webinars/webinars.scss
- src/app/pages/partners/partner-details/carousel/carousel.js
- src/app/pages/partners/partner-details/carousel/carousel.scss
- src/app/pages/partners/partner-details/partner-details.js
> Add carousel to Tutor marketing page Webinars section

- src/app/pages/llph/llph.js
> Add bri_book to login link when on LLPH page

- src/styles/components/filter-buttons.scss
Issue #1318
More sizing flexibility so it doesn't overhang on narrow-ish screens.
> Make subject navigation bar more responsive

- src/app/pages/partners/partner-details/reviews/reviews.js
- src/app/pages/partners/partner-details/reviews/user-review.js
> Do not show reviewless ratings in Reviews tab

- src/app/helpers/analytics.js
- test/src/pages/details/details.test.js
> Fix foreach error in analytics code

- src/app/pages/errata-form/form/ErrorTypeSelector.js
- src/app/pages/errata-form/form/FileUploader.js
- src/app/pages/errata-form/form/form.js
- src/app/pages/errata-form/form/form.scss
> Refactor errata form; disable submit button when clicked

- src/app/pages/details/common/get-this-title-files/amazon-associates-link.js
- src/app/pages/details/common/get-this-title-files/options.js
- src/app/pages/details/common/get-this-title-files/order-print-copy/order-print-copy.js
- test/helpers/fetch-mocker.js
- test/src/data/buyprint.js
- test/src/pages/details/get-this-title/get-this-title.test.js
> Use buyprint to determine whether to display print option

- src/app/models/reviews.js
> Update rating average and review count after submitting review

- src/app/helpers/errata.js
- src/app/pages/confirmation/confirmation.js
- src/app/pages/errata-detail/detail/detail.js
- src/app/pages/errata-detail/errata-detail.js
- src/app/pages/errata-summary/errata-summary.js
- src/app/pages/errata-summary/table/table.js
> Add Additional Location info to Errata summary

- src/app/pages/details/desktop-view/instructor-resource-tab/partners/partners.js
- src/app/pages/partners/analytics-events.js
- src/app/pages/partners/partner-details/partner-details.js
- src/app/pages/partners/partner-details/synopsis/synopsis.js
- src/app/pages/partners/partners.js
- src/app/pages/partners/results/result-grid.js
- src/styles/main.scss
> Fix Tech Scout event reporting

- src/app/pages/partners/partner-details/reviews/user-review.js
> Set status to Deleted on deleted reviews

- .github/workflows/build.yml
- script/archive
> Add Github workflows file

- src/app/pages/partners/partners.js
> Put spaces between words in post-adoption messaging

- src/app/pages/details/common/publication-info.js
> Add PDF last updated

- package.json
- src/app/components/content-group/content-group.jsx
- src/app/models/reviews.js
- src/app/pages/partners/partner-details/partner-context.js
- src/app/pages/partners/partner-details/partner-details.js
- src/app/pages/partners/partner-details/reviews/contexts.js
- src/app/pages/partners/partner-details/reviews/page-context.js
- src/app/pages/partners/partner-details/reviews/rating-form.js
- src/app/pages/partners/partner-details/reviews/reviews.js
- src/app/pages/partners/partner-details/reviews/user-context.js
- src/app/pages/partners/partner-details/reviews/user-review.js
- src/app/pages/partners/partner-details/synopsis/synopsis.js
- src/app/pages/partners/results/result-grid.js
- src/app/pages/research/people-section/people-section.js
- src/app/pages/research/publications-section/publications-section.js
> Merge release 2.73.0 back into master

- src/app/pages/details/common/customization-form/customization-form.js
> Add book ID to Customization form data

- src/app/pages/subjects/book-viewer/book.js
- src/app/pages/subjects/subjects.scss
> Add titles below covers on Subjects page

- src/app/helpers/data.js
- src/app/pages/details/common/publication-info.js
- src/app/pages/subjects/subjects.scss
Issue #1954
Also reverts a poorly-considered layout change on Subjects
> Hide Web Last Updated date when there isn't one

- src/app/pages/errata-form/errata-form.js
- src/app/pages/errata-form/errata-form.scss
- src/app/pages/errata-form/form/ErrorLocationSelector/ErrorLocationSelector.scss
> Prompt for book title when not passed to errata form

- src/app/components/carousel/carousel.js
- src/app/pages/partners/partner-details/carousel/carousel.js
> Fix Partner image carousel frame count

- src/app/pages/details/common/get-this-title-files/get-this-title.scss
- src/app/pages/details/common/get-this-title-files/options.js
> Add disclaimer message for Kindle format

- src/app/components/jsx-helpers/jsx-helpers.jsx
- src/app/pages/faq/faq.js
> Fix FAQ question toggle

- src/app/pages/general/general.js
> Port General Pages to React

- src/app/pages/details/common/resource-box/resource-boxes.js
- src/styles/main.scss
> Send Analytics event when opening Customization form

- src/app/components/shell/header/menus/main-menu/login-menu.js
- src/app/pages/openstax-tutor/openstax-tutor.js
> Use Tutor link from CMS

- src/app/models/usermodel.js
> Throttle login checks

- src/app/components/jsx-helpers/jsx-helpers.jsx
- src/app/components/shell/header/menus/main-menu/login-menu.js
- src/app/components/shell/header/menus/menu-expander/menu-expander.js
- src/app/components/shell/router.js
- src/app/components/shell/shell.js
- src/app/models/usermodel.js
- src/app/pages/creator-fest/creator-fest.js
- src/app/pages/footer-page/footer-page.js
Issue #1817
Discovered React router comes with a useLocation hook; replaced mine with it.
> Fix footer links

- src/app/components/dialog/dialog.js
- src/styles/main.scss
> Store scroll position when dialog is opening

- package.json
- src/app/models/reviews.js
- src/app/pages/details/common/get-this-title-files/get-this-title.scss
- src/app/pages/details/common/resource-box/request-form/request-form.js
- src/app/pages/errata-summary/errata-summary.js
- src/app/pages/home/banner/banner.scss
- src/app/pages/home/features/features.js
- src/app/pages/home/features/features.scss
- src/app/pages/home/tutor/tutor.scss
- src/app/pages/openstax-tutor/banner/banner.scss
- src/app/pages/openstax-tutor/cost/cost.scss
- src/app/pages/openstax-tutor/features/features.scss
- src/app/pages/openstax-tutor/feedback/feedback.js
- src/app/pages/openstax-tutor/materials/materials.scss
- src/app/pages/openstax-tutor/webinars/webinars.scss
- src/app/pages/partners/partner-details/partner-context.js
- src/app/pages/partners/store.js
- src/styles/main.scss
> Merge release/hotfix back to main

- src/app/models/usermodel.js
- src/app/pages/details/common/get-this-title.js
> Add user contact_id to download tracking

- src/app/pages/openstax-tutor/feedback/feedback.js
- src/app/pages/openstax-tutor/feedback/feedback.scss
> Allow video in Tutor page Feedback section

- src/styles/components/forms.scss
> Set textarea to normal wrapping

- src/app/components/dialog/dialog.js
- src/app/models/usermodel.js
- src/app/pages/blog/article-summary/article-summary.jsx
- src/app/pages/details/common/get-this-title-files/give-before-pdf/give-before-pdf.js
- src/app/pages/details/common/get-this-title-files/give-before-pdf/give-before-pdf.scss
- src/app/pages/details/common/get-this-title-files/give-before-pdf/thank-you-form.js
- src/app/pages/details/common/get-this-title-files/give-before-pdf/thank-you-form.scss
- src/app/pages/details/common/get-this-title-files/options.js
> Add donation ask to pdf click

- src/app/pages/errata-form/form/form.js
- src/app/pages/errata-form/form/form.scss
> Add errata release detail to submission form

- src/app/pages/partners/active-filters/active-filters.scss
- src/app/pages/partners/partner-details/partner-details.js
- src/app/pages/partners/partners.js
- src/app/pages/partners/results/results.js
- src/app/pages/partners/results/results.scss
May need to revisit when the BE puts in the headers and descriptions
> Separate partners and allies

- src/app/pages/subjects/subjects.js
> Display default page title in browser tab when no subject seo title

- src/app/pages/partners/results/results.js
> Make partner type comparison case-insensitive

- src/app/components/shell/shell.js
- src/app/pages/my-openstax/my-openstax.js
- src/app/pages/partners/partner-details/reviews/reviews.js
- src/app/pages/partners/partner-details/reviews/user-review.js
- src/app/pages/partners/partner-details/reviews/user-review.scss
- src/app/pages/partners/partners.scss
Also fix link color in Tech Scout banner
> Add Verified Instruction indicator to reviews

- src/app/components/dialog/dialog.js
- src/app/components/shell/cookie-notice/cookie-notice.js
- src/app/components/shell/cookie-notice/cookie-notice.scss
> Restyle cookie popup

- src/app/components/book-selector/book-selector.js
- src/app/components/jsx-helpers/jsx-helpers.jsx
- src/app/components/shell/cookie-notice/cookie-notice.js
- src/app/components/shell/header/menus/menu-expander/menu-expander.js
- src/app/components/shell/router-context.js
- src/app/components/shell/router.js
- src/app/components/shell/shell.js
- src/app/helpers/controller/cms-mixin.js
- src/app/helpers/errata.js
- src/app/main.js
- src/app/pages/blog/article/article.js
- src/app/pages/details/details.js
- src/app/pages/errata-form/errata-form.js
- src/app/pages/errata-summary/hero/hero.js
- src/app/pages/partners/controls/checkboxes-linked-to-store/checkboxes-linked-to-store.js
- src/app/pages/press/article/article.js
- src/styles/components/forms.scss
When loading book data fails, route to 404.
Issue #1886
> Recognize invalid books

- src/app/pages/details/common/errata.js
Snippet should include a mailto link
> Spanish book errata show no buttons

- src/app/pages/errata-summary/errata-summary.scss
- src/app/pages/errata-summary/hero/hero.js
- src/app/pages/errata-summary/hero/hero.scss
- src/styles/components/tooltip.scss
- src/styles/main.scss
> Use more accessible tooltip for errata correction schedule

- src/index.html
> Remove Pardot variables from index.html

- .gitignore
- src/app/pages/separatemap/search-box/result-box/result-box.js
- src/app/pages/separatemap/testimonial-form/testimonial-form.js
Round two.. without all your other changes going to RC
I'm not sure how you handle merging stuff into the RC (probably should learn that if I'm going to be messing around with your codebase!)
Anyways, if this isn't right, we can fix it tomorrow.. I just wanted to test deploy it and see if it happened to work like I thought it might.
> fix the testimonial form for SF

- src/app/helpers/link.js
…re using cloudfront instances
> FE cloudfront friendly login/logout urls

- src/app/components/multiselect/multiselect-context.js
> Fix book multiselect

- src/app/components/more-fewer/more-fewer.scss
It can be outside of a more-fewer component, and is, on the Press page
> Fix headline-paginator styling

- src/app/components/body-units/body-units.js
- src/app/pages/blog/article-summary/article-summary.js
- src/app/pages/blog/article-summary/article-summary.scss
- src/app/pages/blog/article/article.js
- src/app/pages/blog/article/article.scss
- src/app/pages/blog/blog-context.js
- src/app/pages/blog/blog.js
- src/app/pages/blog/more-stories/more-stories.js
- src/app/pages/blog/more-stories/more-stories.scss
- src/app/pages/blog/search-bar/search-bar.js
- src/app/pages/blog/search-bar/search-bar.scss
- src/app/pages/blog/search-results/search-results.js
- src/app/pages/blog/update-box/update-box.scss
- src/app/pages/details/common/resource-box/resource-box.js
- src/app/pages/my-openstax/store/use-adoptions.js
- test/src/pages/blog/blog.test.js
Left and right are now small images
Mid is float-right half-width
> Blog article layout

- src/app/pages/partners/partner-details/info-request-form/info-request-form.js
This changes the field name. The value is in the CMS. Card notes that change as a deployment issue.
> Rename role to position

- src/app/components/jsx-helpers/jsx-helpers.jsx
- src/app/components/multiselect/book-tags/book-options.scss
- src/app/components/multiselect/book-tags/book-tags.js
- src/app/components/multiselect/book-tags/book-tags.scss
- src/app/components/multiselect/book-tags/sf-book-context.js
- src/app/components/multiselect/multiselect.js
- src/app/components/shell/microsurvey-popup/adoption-content.js
- src/app/contexts/user.js
- src/app/models/renewals.js
- src/app/pages/partners/partner-details/info-request-form/info-request-form.js
- src/app/pages/renewal-form/renewal-form.js
- src/app/pages/renewal-form/renewal-form.scss
Not including some back end data items
> Layout renewal form

- src/app/pages/subjects/new/hero.scss
- src/app/pages/subjects/new/info-boxes.scss
- src/app/pages/subjects/new/subjects-listing.js
- src/app/pages/subjects/new/subjects-listing.scss
- src/app/pages/subjects/new/tutor-ad.scss
Some styling here, some data fixing in Dev. It now looks more like the design file, but translation is still not available.
> UX fixes for All Subjects

- src/app/helpers/$.js
- src/app/helpers/controller/cms-mixin.js
- src/app/pages/general/general.js
This applies to all general pages
> Fix Kinetic page tab title and description

- test/helpers/fetch-mocker.js
- test/src/data/renewal.js
- test/src/pages/my-openstax.test.js
- test/src/pages/renewal-form.test.js
- yarn.lock
Uses the updated Pattern Library, where the pip color change was implemented
> Pip color and tests

- package.json
- src/app/pages/details/common/resource-box/resource-box.js
- src/app/pages/subjects/new/specific/translation-selector.js
Also added a micro-fix for subjects
> Merge hotfix 2.95.2 into main

- src/app/pages/details/common/resource-box/resource-box.js
- src/app/pages/details/desktop-view/instructor-resource-tab/instructor-resource-tab.js
- src/app/pages/details/details.js
- src/app/pages/details/phone-view/instructor-resources-pane/instructor-resources-pane.js
Check for Resource tab/pane display when window width changes
> Use instructor resource API with hidden-links feature

- src/app/components/book-selector/book-selector.js
- src/app/pages/adoption/adoption.js
- src/app/pages/interest/interest.js
Also fix prompt on Interest form
> Add note to ignore version on Adoption form

- src/app/pages/blog/article/article.scss
- src/app/pages/subjects/new/specific/specific.js
- src/app/pages/subjects/new/subjects.js
> Handle subjects/ap and unknown-subject routing for New Subjects page

- src/app/components/shell/header/sticky-note/sticky-note.scss
> Fix put-away icon for emergency banner

- src/app/components/shell/header/menus/main-menu/main-menu.js
- src/app/components/shell/header/menus/upper-menu/upper-menu.js
> Specify menus as json

- src/app/pages/team/people-tab/people-tab.js
- src/app/pages/team/people-tab/people-tab.scss
Can't link across to the card:
https://github.com/openstax/openstax.org/issues/2176
> Display headshots on Team page

- src/app/pages/partners/results/results.js
- src/app/pages/subjects/new/specific/book-viewer.scss
Also fixes issue with Partner Website
> Fix get this book dropdown

- src/app/components/shell/takeover-dialog/takeover-dialog-content.js
Can't link this issue because it's on the cms board.
[openstax-cms/#1372](https://github.com/orgs/openstax/projects/14/views/9?pane=issue&itemId=18462056)
> Respect goal time regardless of type of fundraiser

- src/app/pages/general/general.js
Issue [openstax.org/2181](https://github.com/orgs/openstax/projects/14/views/9?pane=issue&itemId=18381595)
> Set canonical link for general pages

- src/app/pages/general/general.js
Issue [openstax.org/2181](https://github.com/orgs/openstax/projects/14/views/9?pane=issue&itemId=18381595)
> Do canonical link where it will be included with or without /general

- package.json
- src/app/pages/general/general.js
@chrisbendel Please check to make sure I resolved conflicts correctly on this.
> Merge changes from 2.99.1 back to main

- src/app/helpers/use-document-head.js
- src/app/pages/general/general.js
Issue [openstax.org/2175](https://github.com/openstax/openstax.org/issues/2175)
> Noindex general pages except kinetic

- src/app/pages/institutional-partnership/sections/big-quote/big-quote.js
- src/app/pages/interest/interest.js
- src/app/pages/k12/all-subjects/sign-up-form.js
- src/app/pages/k12/subject/contact.js
Real changes are in big-quote.js. The other files are just reformatted by prettier.
> Optimize testimonial background image on Institutional Partners page

- src/app/main.js
- src/app/models/sfapi.js
my local cms doesn't have any settings configured in webview_settings, so these lines were preventing the UI from loading at all.
> handle missing settings more gracefully

- src/app/components/accordion-group/accordion-group.js
- src/app/components/tab-group/tab-group.js
- src/app/pages/details/common/featured-resources/featured-resources.js
- src/app/pages/details/common/get-this-title-files/give-before-pdf/give-before-pdf.js
- src/app/pages/details/common/get-this-title-files/options.js
- src/app/pages/details/common/get-this-title.js
- src/app/pages/details/common/resource-box/resource-box.js
- src/app/pages/details/common/resource-box/resource-boxes.js
- src/app/pages/details/desktop-view/desktop-view.js
- src/app/pages/details/desktop-view/instructor-resource-tab/instructor-resource-tab.js
- src/app/pages/details/desktop-view/instructor-resource-tab/partners/partners.js
- src/app/pages/details/desktop-view/student-resource-tab/student-resource-tab.js
- src/app/pages/details/phone-view/instructor-resources-pane/instructor-resources-pane.js
- src/app/pages/details/phone-view/phone-view.js
adds requested G4 analytics events to book details page
> Additional analytics events

- src/app/components/shell/header/menus/main-menu/login-menu/login-menu-with-dropdown.js
For: https://github.com/openstax/openstax.org/issues/2223
> Add /i to /signup links

- src/app/components/shell/footer/footer.js
- src/app/components/shell/header/menus/logo/logo.js
- src/app/components/shell/header/menus/main-menu/dropdown/dropdown.js
- src/app/components/shell/header/menus/main-menu/main-menu.js
- src/app/components/shell/header/menus/upper-menu/upper-menu.js
adds g4 link click events to main navs and footers
> add site nav G4 events

- src/app/pages/renewal-form/renewal-form.js
For: https://github.com/openstax/os-webview/issues/2379
> Require student number on renewal form

- src/app/pages/assignable/sections/courses/courses.scss
For: https://github.com/openstax/openstax.org/issues/2235
> Center book image block on Assignable page

- src/app/pages/assignable/sections/overlapping-quote/overlapping-quote.js
- src/app/pages/assignable/sections/overlapping-quote/overlapping-quote.scss
For: https://github.com/openstax/openstax.org/issues/2246
> Restyle Assignable CTA

- src/app/components/paginator/search-results/paginator.js
- src/app/pages/blog/search-bar/search-context.js
- src/app/pages/blog/search-results/search-results.js
so that the G4 enhanced collection picks it up
https://support.google.com/analytics/answer/9216061?hl=en
> update blog search to use a query param

- src/app/pages/details/common/resource-box/resource-box.js
- test/src/pages/details/resource-boxes.test.js
For: https://github.com/openstax/openstax.org/issues/2238
The issue here is that the unlocked flag was not at the top level of the data, but within the `resource` member.
> Fix locked resource box issue

- src/app/pages/institutional-partnership-application/institutional-partnership-application.scss
For: https://github.com/openstax/openstax.org/issues/2248
> Style apply link as button on Institutional Partnership Application

- src/app/components/sticky-footer/button-group-mixin.scss
- src/app/components/sticky-footer/sticky-footer.scss
- src/app/pages/blog/blog-context.js
- src/app/pages/blog/blog.js
- src/app/pages/blog/blog.scss
- src/app/pages/blog/explore/by-subject.scss
- src/app/pages/institutional-partnership/institutional-partnership.scss
- test/src/pages/blog/blog.test.js
For: https://github.com/openstax/openstax.org/issues/2245
> Blog page sticky note

- src/app/pages/webinars/webinar-list/webinar-list.js
- src/app/pages/webinars/webinars.js
For: https://github.com/openstax/openstax.org/issues/2241
> "No upcoming webinars" card

- src/app/components/shell/lower-sticky-note/lsn-content.js
- src/app/models/usermodel.js
- src/app/pages/home/banner/banner.js
For: https://github.com/openstax/os-webview/issues/2401
Address issues as practical:
> Lighthouse issues

- src/app/models/usermodel.js
- src/app/pages/assignable/sections/about/about.js
- src/app/pages/assignable/sections/about/about.scss
For: https://github.com/openstax/openstax.org/issues/2247
Just placeholder images for now
> Assignable image carousel added

- src/app/pages/blog/explore/by-subject.scss
- src/app/pages/blog/explore/collections.scss
For: https://github.com/openstax/openstax.org/issues/2257
> Fix "explore" card layout

- src/app/components/shell/header/menus/main-menu/main-menu.js
For: https://github.com/openstax/openstax.org/issues/1716
> Load menus from the CMS

- src/app/pages/errata-form/form/ErrorSourceSelector.js
For: https://github.com/openstax/openstax.org/issues/2230
> Errata: limit Assignable option to Assignable books

- src/app/pages/home/banner/banner.scss
- src/app/pages/home/features/features.scss
- src/app/pages/home/home.js
- src/app/pages/home/overlapping-boxes/overlapping-boxes.js
- src/app/pages/home/overlapping-boxes/overlapping-boxes.scss
For: https://github.com/openstax/openstax.org/issues/2261
For: https://github.com/openstax/openstax.org/issues/2254
> Add overlay boxes to homepage

- src/app/components/shell/header/menus/main-menu/login-menu/login-menu-with-dropdown.js
- src/app/models/usermodel.js
For: https://github.com/openstax/openstax-cms/issues/1465
> Do not show "Request Instructor Access" for rejected faculty

- src/app/pages/errata-form/errata-form.js
- src/app/pages/errata-form/errata-form.scss
For: https://github.com/openstax/openstax.org/issues/2267
> Handle bad/missing title for errata form

- src/app/pages/details/common/resource-box/resource-box.scss
- src/app/pages/details/common/resource-box/resource-boxes.js
- src/styles/mixins/coming-soon.scss
For: https://github.com/openstax/openstax.org/issues/2239
> Coming soon resources without links

- src/app/pages/blog/more-stories/more-stories.scss
For: https://github.com/openstax/openstax.org/issues/2269
> Fix blog card display

- src/app/pages/general/general.js
- test/helpers/fetch-mocker.js
- test/src/data/kinetic.js
- test/src/general/general.test.js
For: https://github.com/openstax/openstax.org/issues/2270
> Leave noindex off kinetic page

- package.json
- yarn.lock
After the release, rebase the branch, then make it a real PR.
> Merge 2.106.0 changes into main

- src/app/components/shell/microsurvey-popup/adoption-content.js
- src/app/models/usermodel.js
For: https://github.com/openstax/openstax.org/issues/2265
> Show renewal popup to all confirmed faculty; dismiss is permanent

- src/app/components/shell/microsurvey-popup/adoption-content.js
- src/app/pages/renewal-form/renewal-form.js
For: https://github.com/openstax/openstax.org/issues/2275
> Add redirect location to renewal form

- src/app/components/shell/footer/footer.js
- src/app/components/shell/footer/footer.scss
- src/app/pages/details/common/savings-blurb.js
- src/app/pages/subjects/new/info-boxes.js
- src/app/pages/subjects/new/philanthropic-support.js
- src/app/pages/subjects/new/subjects.scss
- src/app/pages/subjects/old/book-viewer/book.js
- src/app/pages/subjects/old/subjects.js
- src/app/pages/subjects/old/subjects.scss
- src/index.html
For: https://github.com/openstax/os-webview/issues/2401
> Lighthouse score improvement

- src/app/pages/details/desktop-view/instructor-resource-tab/instructor-resource-tab.js
For: https://github.com/openstax/openstax.org/issues/2282
> Update "how do I do that" link

- src/app/components/shell/microsurvey-popup/adoption-content.js
For: https://github.com/openstax/openstax.org/issues/2290
> Only display renewal popup to current adopters

- src/app/components/shell/microsurvey-popup/adoption-content.js
- src/app/pages/renewal-form/renewal-form.js
- test/src/pages/renewal-form.test.js
For: https://github.com/openstax/openstax.org/issues/2292
> Update text for renewal popup

- src/app/pages/press/article/article.js
- src/app/pages/press/article/article.scss
For: https://github.com/openstax/openstax.org/issues/2293
> Style press releases more like blog articles

- src/app/pages/subjects/new/specific/context.js
For: https://github.com/openstax/openstax.org/issues/2291
> Add -books to specific-subject slugs

- src/app/pages/subjects/new/subjects-listing.scss
- src/app/pages/subjects/new/subjects.scss
For: https://github.com/openstax/openstax.org/issues/2304 and https://github.com/openstax/openstax.org/issues/2303
> Adjust layout of new subjects

- src/app/pages/details/common/get-this-title-files/give-before-pdf/give-before-pdf.js
- src/app/pages/details/common/get-this-title-files/give-before-pdf/use-give-links.ts
For: https://github.com/openstax/openstax.org/issues/2297
> Tracking donation appeals

- src/app/components/share/share.js
- src/app/components/share/share.scss
- src/app/components/shell/footer/footer.js
- src/app/pages/press/mission/inquiries.js
For: https://github.com/openstax/openstax.org/issues/2305
> Update Twitter logo

- src/app/components/book-tile/book-tile.scss
For: https://github.com/openstax/openstax.org/issues/2308
> Bring book menu to top

- src/app/pages/blog/more-stories/more-stories.js
- src/app/pages/blog/pinned-article/pinned-article.js
- src/app/pages/blog/search-results/no-results.scss
- src/app/pages/blog/search-results/no-results.tsx
- src/app/pages/blog/search-results/search-results.js
- src/app/pages/webinars/search-page/no-results.scss
- src/app/pages/webinars/search-page/no-results.tsx
- src/app/pages/webinars/search-page/search-page.tsx
For: https://github.com/openstax/openstax.org/issues/2298
> Zero search results

- package.json
- src/app/pages/details/common/resource-box/left-content.tsx
- yarn.lock
Merge release changes back to main
> Rc 2.110.0

- src/app/pages/details/common/links-to-translations.tsx
- src/app/pages/details/context.d.ts
- src/app/pages/details/context.js
- src/app/pages/details/desktop-view/desktop-view.js
- src/app/pages/details/details.js
- src/app/pages/details/dual-view.tsx
- src/app/pages/details/phone-view/phone-view.js
- src/app/pages/details/title-image.tsx
No functional changes, just refactoring and cleanup.
> Refactor Details page

- src/app/components/shell/microsurvey-popup/adoption-content.js
- src/app/components/shell/router.js
- src/app/pages/webinars/main-page/main-page.tsx
- src/app/pages/webinars/search-page/no-results.tsx
For: https://github.com/openstax/openstax.org/issues/2311
Also: https://github.com/openstax/openstax.org/issues/2312
> Dismissing renewal popup is permanent

- package.json
- script/dev
- src/app/components/jsx-helpers/raw-html.tsx
- yarn.lock
For: https://github.com/openstax/openstax.org/issues/2313
> Hotfix 2.110.2

- src/app/components/book-tile/book-tile.js
- src/app/pages/details/common/get-this-title-files/options.js
- src/app/pages/details/common/get-this-title-files/order-print-copy/order-print-copy.js
- src/app/pages/webinars/webinar-cards/latest-webinars.tsx
For: https://github.com/openstax/openstax.org/issues/2329
> Order print copy

- src/app/components/book-tile/book-tile.js
- src/app/components/book-tile/book-tile.scss
- src/app/pages/k12/subject/books.scss
For: https://github.com/openstax/openstax.org/issues/2325
and: https://github.com/openstax/openstax.org/issues/2321
> Align Get the book menu; make book tile link to details

- src/app/pages/blog/more-stories/more-stories.scss
- src/app/pages/blog/search-results/no-results.tsx
For: https://github.com/openstax/openstax.org/issues/2298
> Adjust layout of blog search no-results page

- src/app/components/shell/header/menus/main-menu/main-menu.js
- src/app/lang/en.js
- src/app/lang/es.js
- src/app/pages/subjects/new/specific/blog-posts.js
- src/app/pages/subjects/new/specific/webinars.js
For: https://github.com/openstax/openstax.org/issues/2335
> Filter K12 Subject out; add "For K12 Teachers" to Subjects menu

- src/app/components/shell/footer/footer.js
- src/app/pages/press/mission/inquiries.js
- src/app/pages/press/mission/inquiries.scss
For: https://github.com/openstax/openstax.org/issues/2340
> Add YouTube icon

- src/app/components/assignable-badge/assignable-badge.tsx
- src/app/components/book-tile/book-tile.js
- src/app/components/book-tile/book-tile.scss
- src/app/helpers/data.d.ts
- src/app/helpers/use-data.ts
- src/app/models/assignable-snippet.js
- src/app/models/assignable-snippet.ts
- src/app/models/book-titles.js
- src/app/pages/blog/blog-context.js
- src/app/pages/details/desktop-view/details-tab/details-tab.js
- src/app/pages/k12/subject/books.scss
- src/app/pages/subjects/old/book-viewer/book.js
- src/app/pages/subjects/old/subjects.scss
- src/app/pages/subjects/subjects.js
- src/styles/mixins/assignable.scss
For: https://github.com/openstax/openstax.org/issues/2200
> Promote Assignable on book details & Subjects pages

- src/app/helpers/use-debounce-test.ts
- src/app/helpers/use-page-data.d.ts
- src/app/lang/en.js
- src/app/lang/es.js
- src/app/pages/subjects/new/specific/find-translation.tsx
- src/app/pages/subjects/new/specific/specific.js
For: https://github.com/openstax/openstax.org/issues/2339
> Resolve language/subject conflicts for Specific Subjects

- package.json
- src/app/components/shell/header/menus/main-menu/main-menu.js
- src/app/pages/blog/blog-context.js
- src/app/pages/subjects/new/specific/learn-more.js
- yarn.lock
For: https://github.com/openstax/openstax.org/issues/2354
> Merge release back to main

- src/app/components/book-tile/book-tile.js
- src/app/pages/details/common/get-this-title-files/give-before-pdf/give-before-pdf.scss
For: https://github.com/openstax/openstax.org/issues/2352
Added code is pulled almost straight from [the related code on the Details page](https://github.com/openstax/os-webview/blob/main/src/app/pages/details/common/get-this-title-files/options.js#L130)
> Show give dialog when downloading PDF from new Subjects

- src/app/components/book-tile/book-tile.js
For: https://github.com/openstax/openstax.org/issues/2358
> Fix coming soon badge

- src/app/components/book-tile/book-tile.scss
- src/app/components/book-tile/book-tile.tsx
For: https://github.com/openstax/openstax.org/issues/2359
> Don't show Get the book menu on Coming soon books

- src/app/pages/adoption/adoption.js
- src/app/pages/renewal-form/renewal-form.js
For: https://github.com/openstax/os-webview/issues/2486
> Use subject_interest field for adoption, interest, and renewal forms

- src/index.html
For: https://github.com/openstax/openstax.org/issues/2363
> Re-add crazyegg script

- src/app/pages/contact/form.js
For: https://github.com/openstax/openstax.org/issues/2362
> Remove CNX, add Staxly to Contact subject list

- src/app/components/shell/router-helpers/useLinkHandler.ts
- src/app/contexts/user.d.ts
- src/app/models/usermodel.d.ts
- src/app/pages/details/common/get-this-title.js
- src/app/pages/details/common/resource-box/left-content.tsx
- src/app/pages/details/common/track-link.ts
For: https://github.com/openstax/os-webview/issues/2482
Also only use the PDF download dialog if the download is a PDF.
> Do not track resource downloads with incomplete info

- src/app/pages/contact/form.js
For: https://github.com/openstax/openstax.org/issues/2366
> Add Assignable to Contact form topics

- src/app/components/language-selector/language-selector.d.ts
- src/app/components/language-selector/language-selector.js
- src/app/models/amazon-snippet.ts
- src/app/pages/details/common/get-this-title-files/amazon-associates-link.tsx
- src/app/pages/details/common/get-this-title-files/options.js
- src/app/pages/details/common/get-this-title-files/order-print-copy/order-print-copy.js
- src/app/pages/details/common/get-this-title-files/order-print-copy/order-print-copy.scss
- src/app/pages/details/common/get-this-title-files/order-print-copy/use-amazon-iframe.ts
- src/app/pages/details/common/get-this-title.js
- src/app/pages/details/common/links-to-translations.tsx
- src/app/pages/details/context.d.ts
- test/helpers/fetch-mocker.js
- test/src/data/amazon-blurb.js
- test/src/pages/details/get-this-title/get-this-title.test.js
For: https://github.com/openstax/openstax.org/issues/2365
> Show iframe for Amazon listing

- package.json
- src/app/components/book-tile/dropdown-menu.tsx
- src/app/components/shell/takeover-dialog/content-mobile.scss
- src/app/pages/details/common/get-this-title-files/amazon-associates-link.tsx
- src/app/pages/details/common/get-this-title-files/give-before-pdf/give-before-pdf.tsx
- src/app/pages/details/common/get-this-title-files/give-before-pdf/use-give-dialog.tsx
- src/app/pages/details/common/get-this-title-files/options.js
- src/app/pages/details/common/get-this-title-files/order-print-copy/order-print-copy.js
- src/app/pages/details/common/get-this-title-files/order-print-copy/order-print-copy.scss
- src/app/pages/details/common/get-this-title-files/order-print-copy/use-amazon-iframe.ts
- src/app/pages/details/common/get-this-title.js
- src/app/pages/details/common/resource-box/left-content.tsx
- src/app/pages/subjects/new/specific/navigator.js
- src/styles/main.scss
- yarn.lock
For: https://github.com/openstax/openstax.org/issues/2381
This is rebased to the latest release, which fixed some related issues. Review that first. Only the last commit here is actually new work.
> Do not show print copy options when there is no link

- src/app/components/shell/header/menus/give-button/give-button.js
- src/app/components/shell/header/menus/give-button/give-button.scss
- src/app/components/shell/header/menus/main-menu/main-menu.js
For: https://github.com/openstax/openstax.org/issues/2357
> Move and style Give button in main menu

- src/app/pages/subjects/new/specific/navigator.js
For: https://github.com/openstax/openstax.org/issues/2376
> Fix autoscroll issue

- src/app/pages/details/common/get-this-title-files/give-before-pdf/common-elements.tsx
- src/app/pages/details/common/get-this-title-files/give-before-pdf/give-before-online.tsx
- src/app/pages/details/common/get-this-title-files/give-before-pdf/give-before-pdf.tsx
For: https://github.com/openstax/openstax.org/issues/2361
View online download dialog always uses the control variant
> Only use donation experiment for PDF download

- src/app/pages/press/article/article.scss
For: https://github.com/openstax/openstax.org/issues/2384
> Apply blog article styling to press article pages

- src/app/components/shell/router-helpers/useLinkHandler.ts
- src/app/pages/details/common/get-this-title-files/give-before-pdf/give-before-other.tsx
- src/app/pages/details/common/get-this-title-files/give-before-pdf/use-give-dialog.tsx
- src/app/pages/details/common/track-link.ts
- test/src/pages/details/resource-boxes.test.js
For: https://github.com/openstax/openstax.org/issues/2383
**Note**: this is rebased to #2511 (Add source to thank you form). Review that first. Only the latest two commits here are new.
> Allow tracking with no salesforce contact

- src/app/pages/details/common/resource-box/left-content.tsx
For: https://github.com/openstax/openstax.org/issues/2383
Left this item out of the previous PR
> Only track resource downloads for Instructors

- src/app/pages/details/common/get-this-title-files/order-print-copy/order-print-copy.js
For: https://github.com/openstax/openstax.org/issues/2387
> Fix Bookstore order dialog disclosure undefined

- src/app/pages/details/common/get-this-title-files/give-before-pdf/give-before-other.tsx
- src/app/pages/subjects/new/tutor-ad.js
for: https://github.com/openstax/openstax.org/issues/2374
for: https://github.com/openstax/openstax.org/issues/2396
> Add analytics attributes for assignable link and give before online

- src/app/pages/institutional-partnership/institutional-partnership.js
- src/app/pages/institutional-partnership/institutional-partnership.scss
For: https://github.com/openstax/openstax.org/issues/2392
> Remove sticky note footer from Institutional Partner Program page

- src/app/contexts/user.d.ts
- src/app/contexts/user.js
- src/app/pages/details/common/resource-box/resource-box.js
For: https://github.com/openstax/openstax.org/issues/2395
> Only track confirmed_faculty downloads

- src/app/pages/subjects/new/specific/book-viewer.js
- src/app/pages/subjects/new/specific/navigator.js
For: https://github.com/openstax/openstax.org/issues/2376
> Move initial scroll to the book section

- src/app/components/shell/router.js
- src/app/pages/general/general.js
For: https://github.com/openstax/openstax.org/issues/2397
> Fix Kinetic page canonical link

- src/app/components/shell/header/menus/main-menu/dropdown/dropdown.js
- src/app/components/shell/header/menus/main-menu/dropdown/dropdown.scss
- src/app/components/shell/header/menus/main-menu/main-menu.js
- src/app/components/shell/header/menus/menu-expander/menu-expander.js
- src/app/components/shell/header/menus/menus.js
- src/app/components/shell/header/menus/menus.tsx
- src/app/components/shell/header/menus/upper-menu/upper-menu.tsx
- src/app/helpers/events.js
- src/app/helpers/trapTab.js
For: https://github.com/openstax/openstax.org/issues/2385
> Make menus keyboard operable

- src/app/components/sticky-footer/sticky-footer.js
- src/app/pages/blog/blog-context.js
- src/app/pages/blog/blog.js
- src/app/pages/blog/blog.scss
For: https://github.com/openstax/openstax.org/issues/2391
> Move "Write for us" section from sticky footer to blog page

- src/app/pages/adoption/adoption.js
For: https://github.com/openstax/os-webview/issues/2531
> Remove "Have XanEdu contact me" from adoption form

- src/app/components/clipped-image/clipped-image.js
- src/app/components/shell/footer/footer.js
- src/app/components/shell/header/menus/main-menu/dropdown/dropdown.js
- src/app/pages/home/banner/banner.js
- src/app/pages/subjects/new/about-openstax.js
For: https://github.com/openstax/openstax.org/issues/2408
For: https://github.com/openstax/openstax.org/issues/2407
> Mark images as decorative

- src/app/components/shell/header/menus/main-menu/dropdown/dropdown.js
For: https://github.com/openstax/openstax.org/issues/2415
> Do not auto-expand dropdown menus

- src/app/components/shell/header/header.scss
For: https://github.com/openstax/openstax.org/issues/2412
> Set focus color in header for accessible contrast

- src/app/components/shell/header/menus/main-menu/dropdown/dropdown.js
For: https://github.com/openstax/openstax.org/issues/2411
> Make menus arrow-navigable

- src/app/components/shell/header/menus/main-menu/login-menu/login-menu-with-dropdown.js
- src/app/models/usermodel.d.ts
- src/app/models/usermodel.js
For: https://github.com/openstax/os-webview/issues/2530
> Handle new faculty statuses

- src/app/components/carousel/carousel.scss
- src/app/pages/assignable/sections/about/about.js
- src/app/pages/impact/testimonials.js
- src/app/pages/partners/partner-details/carousel/carousel.js
- src/app/pages/press/testimonials/testimonials.js
- src/app/pages/subjects/new/specific/blog-posts.js
- src/app/pages/subjects/new/specific/components/carousel-section.js
- src/app/pages/subjects/new/specific/webinars.tsx
For: https://github.com/openstax/openstax.org/issues/2413
> Add hover text to carousel instances

- src/app/components/carousel/carousel.scss
- src/app/pages/blog/explore-page/explore-page.js
For: https://github.com/openstax/openstax.org/issues/2421
For: https://github.com/openstax/openstax.org/issues/2418
(Two one-line fixes)
> Constrain carousel viewport height

- package.json
- yarn.lock
Release candidate for 21 Feb 2024
> Rc 2.120.0

- package.json
- src/app/components/tablist/tablist.scss
- src/app/components/tablist/tablist.tsx
- src/app/pages/home/features/features.js
- src/app/pages/home/features/features.scss
- test/src/pages/home/home.test.js
- tsconfig.json
- yarn.lock
For: https://github.com/openstax/openstax.org/issues/2400
For: https://github.com/openstax/openstax.org/issues/2401
> Use tablist for dynamic features list on homepage

- src/app/components/shell/header/header.scss
- src/app/components/shell/lower-sticky-note/lower-sticky-note.scss
- src/app/components/shell/takeover-dialog/content-desktop.scss
- src/app/pages/blog/blog.scss
- src/app/pages/errata-summary/hero/hero.scss
- src/app/pages/home/banner/banner.scss
- yarn.lock
For: https://github.com/openstax/openstax.org/issues/2391
Pattern library has been updated
> Use baby-blue color from pattern library

- src/app/components/search-bar/search-bar.scss
- src/app/pages/blog/search-results/search-results.js
For: https://github.com/openstax/openstax.org/issues/2427
> Focus on first blog article when page changes

- package.json
- src/app/components/book-tile/book-tile.tsx
- src/app/components/carousel/carousel.js
- src/app/components/carousel/carousel.scss
- src/app/pages/partners/partner-details/carousel/carousel.js
- src/app/pages/partners/partner-details/partner-details.scss
- src/app/pages/subjects/new/specific/blog-posts.js
- src/app/pages/subjects/new/specific/blog-posts.scss
- src/app/pages/subjects/new/specific/components/carousel-section.js
- src/app/pages/subjects/new/specific/components/carousel-section.scss
- src/app/pages/subjects/new/specific/webinars.scss
- src/app/pages/subjects/new/specific/webinars.tsx
- test/src/pages/subjects/webinars.test.tsx
- yarn.lock
For: https://github.com/openstax/openstax.org/issues/2413
> Use accessible carousel on specific-subjects pages

- src/app/pages/details/common/get-this-title-files/give-before-pdf/common-elements.tsx
- src/app/pages/details/common/track-link.ts
For: https://openstax.atlassian.net/browse/DISCO-146
> [DISCO-146] Set initial focus in give modal

- src/app/pages/confirmation/confirmation.js
[DISCO-170]
[DISCO-170]: https://openstax.atlassian.net/browse/DISCO-170?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Add space to errata confirmation message

- src/app/components/book-selector/book-selector.js
- src/app/pages/adoption/adoption.js
[DISCO-140]
A lot of the updates to book-selector are just `prettier` restyling. Functional changes are lines 57 and 60.
[DISCO-140]: https://openstax.atlassian.net/browse/DISCO-140?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Exclude coming-soon books from adoption form

- src/app/components/shell/footer/footer.js
- src/app/components/shell/footer/footer.scss
[DISCO-44]
[DISCO-44]: https://openstax.atlassian.net/browse/DISCO-44?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Structure lists of links in footer as lists

- src/app/components/shell/lower-sticky-note/lower-sticky-note.js
[DISCO-169]
[DISCO-169]: https://openstax.atlassian.net/browse/DISCO-169?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Hide sticky note give banner on Economics books details pages

- package.json
- src/app/pages/details/details.scss
- yarn.lock
[DISCO-143]
**Note**: first merge the pattern-library PR, then update this one to use the main branch before merging.
[DISCO-143]: https://openstax.atlassian.net/browse/DISCO-143?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Use midnight color theme

- src/app/pages/details/common/get-this-title-files/options.js
[DISCO-148]
[DISCO-148]: https://openstax.atlassian.net/browse/DISCO-148?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Track "View online" and "Download PDF" clicks

- src/app/components/shell/header/header.scss
- src/app/components/shell/header/menus/upper-menu/upper-menu.scss
[DISCO-192]
[DISCO-192]: https://openstax.atlassian.net/browse/DISCO-192?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Use default focus styling for menu items

- src/app/pages/details/desktop-view/details-tab/details-tab.js
- src/app/pages/details/desktop-view/instructor-resource-tab/instructor-resource-tab.js
- src/app/pages/details/desktop-view/instructor-resource-tab/instructor-resource-tab.scss
- src/app/pages/details/desktop-view/promo.tsx
[DISCO-225]
[DISCO-225]: https://openstax.atlassian.net/browse/DISCO-225?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Add promote snippet to Instructor Resources tab

- src/app/pages/details/common/get-this-title-files/give-before-pdf/give-before-other.tsx
- src/app/pages/details/common/get-this-title-files/give-before-pdf/give-before-pdf.tsx
- src/app/pages/details/common/get-this-title-files/give-before-pdf/thank-you-form.js
- src/app/pages/details/common/get-this-title-files/give-before-pdf/use-give-dialog.tsx
- src/app/pages/details/common/get-this-title-files/options.js
[DISCO-215]
[DISCO-215]: https://openstax.atlassian.net/browse/DISCO-215?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Track click on Thank You note bypass

- package.json
- src/app/components/book-selector/book-selector.js
- src/app/pages/adoption/adoption.js
- src/app/pages/errata-form/form/form.js
- yarn.lock
Release candidate for 17 Apr 2024
> Merge mid-April release to main

- src/index.html
[DISCO-237]
[DISCO-237]: https://openstax.atlassian.net/browse/DISCO-237?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Update osano styles in index.html

- src/styles/main.scss
[DISCO-193]
[DISCO-193]: https://openstax.atlassian.net/browse/DISCO-193?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Give sticky note its own space at bottom on mobile

- src/app/components/shell/takeover-dialog/takeover-dialog.scss
[DISCO-202]
[DISCO-202]: https://openstax.atlassian.net/browse/DISCO-202?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Constrain takeover banner width

- src/app/pages/home/banner/banner.js
- src/app/pages/home/features/features.js
- src/app/pages/home/quotes/quotes.js
[DISCO-197]
[DISCO-197]: https://openstax.atlassian.net/browse/DISCO-197?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Fix alt="true" in hidden images

- src/app/components/shell/footer/footer.js
[DISCO-195]
[DISCO-195]: https://openstax.atlassian.net/browse/DISCO-195?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Better descriptions for social media links in footer

- src/app/pages/details/common/resource-box/left-content.tsx
[DISCO-243]
[DISCO-243]: https://openstax.atlassian.net/browse/DISCO-243?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Add resource name to download label

- src/app/pages/details/desktop-view/instructor-resource-tab/partners/partners.js
- src/app/pages/details/desktop-view/instructor-resource-tab/partners/partners.scss
[DISCO-244]
[DISCO-245]
[DISCO-246]
[DISCO-245]: https://openstax.atlassian.net/browse/DISCO-245?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DISCO-246]: https://openstax.atlassian.net/browse/DISCO-246?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DISCO-244]: https://openstax.atlassian.net/browse/DISCO-244?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Technology partners heading and list items

- src/app/pages/home/banner/banner.js
[DISCO-257]
[DISCO-257]: https://openstax.atlassian.net/browse/DISCO-257?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Homepage banner image resolution on mobile

- src/app/pages/subjects/new/about-openstax.js
[DISCO-248]
[DISCO-248]: https://openstax.atlassian.net/browse/DISCO-248?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Remove id from About Openstax section

- src/app/lang/en.js
- src/app/lang/es.js
- src/app/pages/details/common/let-us-know/let-us-know.js
- src/app/pages/details/common/let-us-know/let-us-know.scss
- src/app/pages/details/details.scss
- test/src/pages/details/let-us-know.test.js
[DISCO-229]
[DISCO-229]: https://openstax.atlassian.net/browse/DISCO-229?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Adoption/Interest CTA redesign

- src/app/pages/contact/contact.scss
- src/app/pages/contact/form.js
- src/app/pages/errata-form/form/FileUploader.js
[DISCO-186]
[DISCO-186]: https://openstax.atlassian.net/browse/DISCO-186?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Add assignable topics to contact form

- src/app/components/tracking-parameters/tracking-parameters.tsx
- src/app/pages/adoption/adoption.js
- src/app/pages/interest/interest.js
[DISCO-264]
[DISCO-264]: https://openstax.atlassian.net/browse/DISCO-264?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Submit current URL as tracking_parameters in adoption/interest forms

- package.json
- src/app/components/tracking-parameters/tracking-parameters.tsx
- src/app/pages/details/common/get-this-title-files/order-print-copy/order-print-copy.scss
- src/app/pages/renewal-form/renewal-form.js
- yarn.lock
This release included a last-minute requirement to add a tracking_parameters field to the renewal form
> Merge changes from 15 May 2024 release

- src/app/pages/subjects/new/specific/navigator.js
- src/app/pages/subjects/new/specific/navigator.scss
[DISCO-306]
[DISCO-306]: https://openstax.atlassian.net/browse/DISCO-306?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Headings in specific subjects sidebar

- src/app/components/book-tile/book-tile.tsx
- src/app/helpers/use-document-head.ts
- test/src/components/__snapshots__/book-tile.test.tsx.snap
[DISCO-305]
[DISCO-305]: https://openstax.atlassian.net/browse/DISCO-305?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Differentiate book links from other links in accessible name

- src/app/pages/foundation/foundation.js
[DISCO-284]
[DISCO-284]: https://openstax.atlassian.net/browse/DISCO-284?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Fix alignment on supporters page

- src/app/helpers/use-document-head.ts
[DISCO-309]
[DISCO-309]: https://openstax.atlassian.net/browse/DISCO-309?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Prevent scrolling when focusing on main

- src/app/contexts/user.d.ts
- src/app/pages/details/common/resource-box/left-content.tsx
- src/app/pages/k12/subject/resources.js
- src/app/pages/k12/subject/resources.tsx
[DISCO-276]
[DISCO-276]: https://openstax.atlassian.net/browse/DISCO-276?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Track k12 resource downloads

- src/app/components/book-tile/book-tile.scss
- src/app/components/book-tile/book-tile.tsx
- test/src/components/__snapshots__/book-tile.test.tsx.snap
- test/src/components/book-tile.test.tsx
[DISCO-303]
[DISCO-303]: https://openstax.atlassian.net/browse/DISCO-303?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> One book link on book tile

- package.json
- src/app/components/dialog/dialog.d.ts
- src/app/components/dialog/dialog.js
- src/app/pages/details/common/get-this-title-files/give-before-pdf/give-before-pdf.tsx
- src/app/pages/details/common/get-this-title-files/give-before-pdf/use-give-dialog.tsx
- yarn.lock
[DISCO-301]
[DISCO-301]: https://openstax.atlassian.net/browse/DISCO-301?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Give dialog accessibility issues

- src/app/pages/details/common/resource-box/left-content.tsx
[DISCO-289]
[DISCO-289]: https://openstax.atlassian.net/browse/DISCO-289?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Accessible label for offsite links in resources

- src/app/pages/details/details.scss
[DISCO-282]
[DISCO-282]: https://openstax.atlassian.net/browse/DISCO-282?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> use transparent background color for book icon

- src/app/components/shell/import-normal-app.js
- src/app/components/shell/normal-app.tsx
- src/app/components/shell/shell.js
- src/app/components/shell/shell.tsx
- src/app/contexts/user.d.ts
[DISCO-317]
Reviewer: It may be helpful to look at the commits separately to see the actual changes to shell.js.
[DISCO-317]: https://openstax.atlassian.net/browse/DISCO-317?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Embeddable pages

- src/app/components/paginator/search-results/paginator.js
- src/app/components/paginator/search-results/paginator.scss
- test/src/components/paginator.test.js
[DISCO-311]
[DISCO-311]: https://openstax.atlassian.net/browse/DISCO-311?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Fix paginator accessibility

- src/styles/main.scss
[DISCO-316]
[DISCO-316]: https://openstax.atlassian.net/browse/DISCO-316?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Hide focus outline for main

- src/app/pages/subjects/new/subjects-listing.scss
- src/app/pages/subjects/new/subjects-listing.tsx
- src/styles/main.scss
[DISCO-304]
[DISCO-304]: https://openstax.atlassian.net/browse/DISCO-304?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Label and structure nav links on subjects-listing

- src/app/pages/subjects/new/specific/navigator.js
[DISCO-306]
[DISCO-306]: https://openstax.atlassian.net/browse/DISCO-306?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Use aria-labelledby for specific subject sidebar navs

- src/app/components/shell/header/menus/upper-menu/upper-menu.tsx
- src/app/pages/bookstore-suppliers/bookstore-suppliers.js
- src/app/pages/bookstore-suppliers/bookstore-suppliers.scss
- src/app/pages/details/common/get-this-title-files/order-print-copy/order-print-copy.js
[DISCO-334]
[DISCO-334]: https://openstax.atlassian.net/browse/DISCO-334?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Update bookstore-suppliers page

- src/app/models/amazon-snippet.ts
- src/app/pages/details/common/get-this-title-files/order-print-copy/order-print-copy.js
[DISCO-331]
[DISCO-331]: https://openstax.atlassian.net/browse/DISCO-331?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Remove Amazon blurb from Individual purchase link

- src/app/lang/en.js
- src/app/lang/es.js
- src/app/pages/details/common/get-this-title-files/order-print-copy/use-amazon-iframe.ts
[DISCO-333]
[DISCO-333]: https://openstax.atlassian.net/browse/DISCO-333?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Change orange buy CTA copy

- src/app/pages/details/common/get-this-title-files/order-print-copy/order-print-copy.js
- src/app/pages/details/common/get-this-title-files/order-print-copy/use-amazon-iframe.ts
[DISCO-332]
[DISCO-332]: https://openstax.atlassian.net/browse/DISCO-332?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Remove Amazon Associates disclosure

- package.json
- src/app/pages/k12/subject/resources.tsx
- yarn.lock
> Merge changes from 12 Jun 2024 release

- src/app/components/shell/header/menus/menus.tsx
- src/app/components/shell/router-helpers/use-link-handler.ts
- src/app/components/shell/router.js
- src/app/components/tab-group/tab-group.tsx
- src/app/helpers/use-document-head.ts
- src/app/pages/details/common/resource-box/left-content.tsx
- src/app/pages/details/common/track-link.ts
- src/app/pages/k12/subject/resources.tsx
- test/src/components/shell/header-menus.test.tsx
- test/src/components/shell/microsurvey-popup.test.tsx
- test/src/components/shell/use-link-handler.test.tsx
- test/src/components/tab-group.test.tsx
- test/src/helpers/use-data.test.tsx
- test/src/helpers/use-document-head.test.tsx
- test/src/pages/subjects/specific.test.tsx
- test/src/pages/subjects/subjects.test.js
- test/src/pages/subjects/webinars.test.tsx
[DISCO-355]
[DISCO-355]: https://openstax.atlassian.net/browse/DISCO-355?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Increase code coverage 4

- src/app/components/shell/footer/footer.scss
- src/app/pages/blog/search-results/search-results.scss
[DISCO-353]
[DISCO-353]: https://openstax.atlassian.net/browse/DISCO-353?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> De-truncate blog search results

- src/app/pages/blog/article-summary/article-summary.tsx
- src/app/pages/blog/search-results/search-results.scss
[DISCO-354]
[DISCO-354]: https://openstax.atlassian.net/browse/DISCO-354?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Accessible name for read more link

- src/app/components/book-tile/dropdown-menu.tsx
- src/app/components/shell/header/menus/main-menu/dropdown/use-menu-controls.ts
- src/app/helpers/books.ts
- src/app/models/books.ts
- src/app/pages/details/common/get-this-title-files/give-before-pdf/content-warning.tsx
- src/app/pages/details/common/get-this-title-files/give-before-pdf/give-before-pdf.scss
- src/app/pages/details/common/get-this-title-files/give-before-pdf/use-give-dialog.tsx
- src/app/pages/details/common/get-this-title-files/options.js
- src/app/pages/details/common/resource-box/left-content.tsx
[DISCO-343]
[DISCO-343]: https://openstax.atlassian.net/browse/DISCO-343?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Content warning modal

- src/app/components/shell/header/menus/main-menu/dropdown/dropdown.js
- src/app/components/shell/header/menus/main-menu/login-menu/login-menu.js
- test/src/components/shell/header-menus.test.tsx
[DISCO-351]
[DISCO-351]: https://openstax.atlassian.net/browse/DISCO-351?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Remove aria roles from menu list items

- src/app/pages/impact/testimonials.js
[DISCO-401]
Changes the Lightbox content to display just the selected testimonial, rather than a carousel of all the testimonials, scrolled to the selected one.
[DISCO-401]: https://openstax.atlassian.net/browse/DISCO-401?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Fix Impact page stories lightbox

- src/app/components/book-tile/book-tile.scss
[DISCO-403]
[DISCO-403]: https://openstax.atlassian.net/browse/DISCO-403?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Align dropdown menu to bottom of book tile

- src/app/helpers/page-data-utils.js
- src/index.html
https://openstax.atlassian.net/browse/DISCO-441
BE hookup is in https://github.com/openstax/openstax-cms/pull/1580
> Cms preview

- src/app/pages/impact/testimonials.js
https://openstax.atlassian.net/browse/DISCO-436
there was also a bug here where it was loading the stories O(n^2) times
~need to see if i can make the cms know the correct url for the page....~ done in https://github.com/openstax/openstax-cms/pull/1579
> open non-impact story testimonial links in not a lightbox

- src/app/pages/details/details.js
[CORE-497]
[CORE-497]: https://openstax.atlassian.net/browse/CORE-497?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Get slug from useParams

- src/app/lang/en.js
[CORE-496]
[CORE-496]: https://openstax.atlassian.net/browse/CORE-496?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Fix apostrophe in interest form student message

- src/app/components/select/drop-down/drop-down.js
- src/app/components/select/select.js
- src/app/components/vertical-list/vertical-list.js
- src/app/pages/contact/contact.tsx
- src/app/pages/contact/form.tsx
- test/src/pages/contact.test.tsx
[CORE-540]
[CORE-540]: https://openstax.atlassian.net/browse/CORE-540?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Port contact form to ts

- README.md
- src/app/components/shell/router.js
[CORE-708]
[CORE-708]: https://openstax.atlassian.net/browse/CORE-708?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Strip extra levels off page url

- src/app/components/multiselect/book-tags/sf-book-context.js
- src/app/components/year-selector/year-selector.tsx
- src/app/pages/adoption/adoption.js
- src/app/pages/adoption/adoption.scss
- src/app/pages/adoption/how-using/how-using.js
- src/app/pages/details/details.scss
- src/app/pages/renewal-form/renewal-form.js
- src/app/pages/renewal-form/renewal-form.scss
- test/src/components/year-selector.test.tsx
- test/src/components/year-selector2.test.tsx
[CORE-758]
[CORE-758]: https://openstax.atlassian.net/browse/CORE-758?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Add school year to adoption and renewal forms

- src/app/components/role-selector/role-selector.js
[CORE-768]
[CORE-768]: https://openstax.atlassian.net/browse/CORE-768?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Fetch role snippet by locale

- package.json
- src/app/pages/partners/results/results.scss
- src/app/pages/partners/results/results.tsx
- yarn.lock
[CORE-790]
[CORE-790]: https://openstax.atlassian.net/browse/CORE-790?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Adjust partner page styling

- src/app/pages/adoption/how-using/how-using.js
- src/app/pages/renewal-form/renewal-form.tsx
- test/src/pages/partners/partners.test.tsx
[CORE-758]
[CORE-758]: https://openstax.atlassian.net/browse/CORE-758?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Include base year in each book entry for adoptionJSON

- src/app/components/contact-info/contact-info.tsx
- src/app/components/form-elements/input-props.ts
- src/app/components/form-header/form-header.tsx
- src/app/components/form-input/form-input.d.ts
- src/app/components/form-input/form-input.tsx
- src/app/components/form-radiogroup/form-radiogroup.tsx
- src/app/components/school-selector/school-selector.tsx
- src/app/helpers/use-select-list.ts
- src/app/pages/partners/partner-details/info-request-form/info-request-form.js
- test/src/components/form-input.test.tsx
- test/src/components/form-radiogroup.test.tsx
- test/src/pages/blog/gated-content-dialog.test.tsx
[CORE-827]
The individual commits show the file changes rather than the deleted-and-created.
[CORE-827]: https://openstax.atlassian.net/browse/CORE-827?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Port components to ts 3

- src/app/pages/blog/article/article.tsx
- test/src/data/article-page-data.js
- test/src/pages/blog/article.test.tsx
[CORE-844]
[CORE-844]: https://openstax.atlassian.net/browse/CORE-844?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Include pullquote in blog articles

- package.json
- src/app/pages/renewal-form/renewal-form.tsx
- yarn.lock
This is the hotfix change we released. It needs to get merged into the main branch.
> Hotfix renewal form redirect 15 April 2025

- package.json
- yarn.lock
Changes released 23 April. The only difference from main (at the time) was the change to version number and some upgraded packages.
> April release: Update version number, upgrade packages

- src/app/layouts/default/takeover-dialog/content-desktop.js
- src/app/layouts/default/takeover-dialog/content-mobile.js
- src/app/layouts/default/takeover-dialog/takeover-dialog-content.js
[CORE-964]
[CORE-964]: https://openstax.atlassian.net/browse/CORE-964?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CORE-964: Set aria-labelledby for takeover dialog

- src/app/pages/details/common/hooks.tsx
- test/src/pages/details/common/hooks.test.tsx
[CORE-990]
[CORE-990]: https://openstax.atlassian.net/browse/CORE-990?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CORE-990: Fix display newly published books

- src/app/components/book-tile/dropdown-menu.tsx
- src/app/components/shell/router.js
- test/src/components/book-tile.test.tsx
[CORE-1038]
[CORE-1038]: https://openstax.atlassian.net/browse/CORE-1038?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CORE-1038: Hide "Download a PDF" in tile dropdown when no PDF is available

- src/app/components/byline/byline.tsx
- src/app/pages/press/about-openstax/about-openstax.tsx
- src/app/pages/press/article/article.tsx
- src/app/pages/press/banner/banner.tsx
- src/app/pages/press/faq/faq.tsx
- src/app/pages/press/featured-in/featured-in.tsx
- src/app/pages/press/helpers.tsx
- src/app/pages/press/infographic/infographic.tsx
- src/app/pages/press/mission/inquiries.tsx
- src/app/pages/press/mission/leadership.tsx
- src/app/pages/press/mission/mission.tsx
- src/app/pages/press/news-mentions/news-mentions.tsx
- src/app/pages/press/page-context.tsx
- src/app/pages/press/press-releases/press-releases.tsx
- src/app/pages/press/press.tsx
- test/src/data/press.js
- test/src/pages/press/press-article.test.tsx
- test/src/pages/press/press.test.tsx
[CORE-1061]
The first commit is all the substantial changes; the second commit is reformatting due to prettier. For files that show up as a delete-and-create in the files changed, looking at the initial commit might be nicer.
[CORE-1061]: https://openstax.atlassian.net/browse/CORE-1061?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Core 1061 port press page to ts

- src/app/components/book-selector/after-form-submit.ts
- src/app/pages/partners/results/results.scss
[CORE-586]
[CORE-586]: https://openstax.atlassian.net/browse/CORE-586?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CORE-586: Fix book passed from adoption form to Partners page

- src/app/components/year-selector/year-selector.tsx
- test/src/components/year-selector2.test.tsx
[CORE-1063]
[CORE-1063]: https://openstax.atlassian.net/browse/CORE-1063?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CORE-1063: School year changes on July 1

- package.json
- yarn.lock
[CORE-940]
[CORE-990]
These are just the updates for the latest release (now on Production)
[CORE-940]: https://openstax.atlassian.net/browse/CORE-940?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CORE-990]: https://openstax.atlassian.net/browse/CORE-990?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Release candidate for late May 2024

- src/app/components/shell/router-helpers/use-link-handler.ts
- src/app/helpers/link.ts
- src/app/layouts/landing/header/header.tsx
- yarn.lock
[CORE-1071]
[CORE-1071]: https://openstax.atlassian.net/browse/CORE-1071?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Core 1071 landing page updates

- package.json
- src/app/components/select/select.tsx
- src/app/components/validation-message/validation-message.tsx
- src/app/helpers/link.ts
- src/app/layouts/landing/footer/flex.tsx
- src/app/pages/contact/embedded.js
- src/app/pages/contact/form.tsx
- test/src/pages/contact.test.tsx
- yarn.lock
This PR was to fix the contact form as displayed from landing pages. Then we made it the release candidate and subsequently did a little hotfix.
> 30 July release and hotfix

- src/app/layouts/default/footer/footer.tsx
- src/app/layouts/default/header/menus/upper-menu/upper-menu.tsx
- test/src/layouts/layouts.test.tsx
[CORE-1080]
[CORE-1080]: https://openstax.atlassian.net/browse/CORE-1080?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CORE 1080: Replace Bookstores link with Order Print

- src/app/pages/details/desktop-view/promo.scss
- src/app/pages/details/desktop-view/promo.tsx
[CORE-1083]
[CORE-1083]: https://openstax.atlassian.net/browse/CORE-1083?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CORE-1083: Update style for promote-snippet

- src/app/helpers/rex-portal.ts
- src/app/pages/details/common/get-this-title-files/options.tsx
- src/app/pages/details/common/hooks.tsx
[CORE-903]
[Rex side](https://github.com/openstax/rex-web/pull/2475) appears to be ready.
Wait until the portal changes (#2750) are merged, though.
[CORE-903]: https://openstax.atlassian.net/browse/CORE-903?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Core 903 go to rex portal url from portal details page
